import { getKeywordOwnership } from './seo/keywordStrategy.js';
import { PRIORITY_CAREER_GUIDES } from './prioritySeoContent.js';
import { getJobIntentDepthBlocks, JOB_INTENT_GUIDE_IDS, JOB_INTENT_REVIEW_DATE } from './seo/jobIntentDepth.js';

const GUIDE_AUTHOR = Object.freeze({
  id: 'bharat-singh',
  name: 'Bharat Singh',
  role: 'Founder & Director',
  profilePath: '/about/',
});

const GUIDE_DATE = '2026-09-13';

function paragraph(text) {
  return { type: 'paragraph', text };
}

function heading(text, level = 2) {
  return { type: 'heading', level, text };
}

function list(items, ordered = false) {
  return { type: 'list', ordered, items };
}

function link(label, href, routeId) {
  return { type: 'link', label, href, routeId };
}

function faq(question, answer) {
  return { type: 'faq', question, answer };
}

const GUIDE_DEPTH_ADDITIONS = Object.freeze({
  'finance-operations': [
    heading('How finance operations teams measure quality'),
    paragraph('A finance operations team is usually judged by more than the number of items processed. Useful measures can include accuracy, control completion, ageing of exceptions, turnaround time, service-level performance, rework, and the quality of evidence. The definitions matter: a fast queue with repeated errors is not healthy, and a high completion rate can hide unresolved material items. Learners should ask what the process is designed to protect and how the team knows the control worked.'),
    list([
      'Accuracy: the record, status, amount, date, and supporting information are correct.',
      'Timeliness: work is completed before the relevant cut-off, service level, or reporting deadline.',
      'Control quality: approvals, segregation, evidence, and escalation are visible and consistent.',
      'Exception health: aged, repeated, material, and client-impacting items have clear ownership.',
      'Process improvement: root causes are reduced without bypassing the authorised workflow.',
    ]),
    heading('A practical case method for interviews'),
    paragraph('When asked about an operational problem, explain the expected process first. Then identify the first field or step that differs, the evidence you would check, the immediate risk or deadline, the owner of the next action, and the control used to verify closure. For example, a missing loan document may require checking the intake record, identifying the responsible queue, recording the case status, and escalating according to policy. The answer should show judgement and control awareness, not an assumption that the candidate can approve every correction.'),
    heading('A finance operations learning roadmap'),
    list([
      'Build accounting, banking, payments, lending, and financial-markets vocabulary.',
      'Map one end-to-end workflow and label each hand-off, control, and output.',
      'Practise a reconciliation, exception, or documentation case with fictional records.',
      'Learn how to write a concise status update with evidence, owner, deadline, and next action.',
      'Compare the roadmap with current vacancies and choose the next tool or product skill to practise.',
    ], true),
    heading('Where the role can lead'),
    paragraph('Finance operations foundations may help a learner explore reconciliation, settlements, payments, loan operations, credit administration, reporting, client operations, controls, or related BFSI support roles. The actual title, schedule, eligibility, tools, and progression vary by employer. Use the task language in current vacancies as the source of truth and avoid relying on generic promises about salary or employment outcomes.'),
    link('Read the finance process associate duties and skills guide', '/blog/finance-process-associate-role/'),
    link('Understand risk management in banking operations', '/blog/risk-management-in-banking/'),
    faq('Does finance operations require advanced financial modelling?', 'Not every role does. Many operations roles prioritise accurate processing, records, reconciliations, controls, communication, and workflow tools. Modelling may be important for a different role, so compare the job description before choosing what to study.'),
  ],
  'investment-banking-operations': [
    heading('Connect market participants with the operations workflow'),
    paragraph('Trade processing becomes easier to understand when each participant and record has a defined place. Learn which organisations provide market access, execution, clearing, depository, custody, registrar, or servicing functions, then trace how information and responsibility move between them. The exact structure depends on the product and market, so use current official sources for real transactions.'),
    link('Map financial market intermediaries and their roles', '/blog/financial-market-intermediaries/'),
    heading('Reference data management in operations'),
    paragraph('Reference data management is the controlled upkeep of fields that other finance workflows rely on. Depending on the product and institution, examples can include instrument identifiers, account and counterparty details, settlement instructions, calendars, currencies, and status codes. An operations analyst should check the approved source, effective date, change history, and authorisation path rather than treating a familiar value as automatically correct.'),
    list([
      'Identify which field is wrong or missing and which authorised source owns it.',
      'Check whether the change affects downstream trades, instructions, positions, reports, or reconciliations.',
      'Preserve the original value, evidence, reviewer, effective date, and approved next action.',
      'Escalate an unresolved or high-impact difference instead of editing a record to make a downstream process pass.',
    ]),
    link('See reference-data checks in a settlement investigation', '/career-guides/trade-lifecycle/'),
  ],
  'kyc-aml-analyst': [
    heading('Client onboarding and KYC operations'),
    paragraph('Client onboarding is the controlled process of collecting and reviewing information before an institution establishes or updates a customer relationship. A KYC analyst may check identity, ownership, business activity, screening results, risk indicators, and missing evidence under the organisation\'s approved procedure. The exact requirements and approval boundaries vary by institution and jurisdiction.'),
    list([
      'Separate a missing document, an inconsistent field, and a potential risk indicator in the case record.',
      'Record the source and date of information so another reviewer can understand the decision trail.',
      'Use the documented request, review, escalation, and approval path rather than making an unsupported conclusion.',
      'Keep onboarding information confidential and avoid using real customer data in practice exercises.',
    ]),
    link('Compare customer onboarding with retail banking operations', '/career-guides/retail-banking-operations/'),
  ],
  'trade-lifecycle': [
    heading('Who owns each trade-lifecycle hand-off?'),
    paragraph('A lifecycle diagram is more useful when it names the record and responsible party at each stage. Brokers, exchanges, clearing corporations, depositories, custodians, banks, and operations teams can hold different records and authority. Understanding those boundaries helps a learner explain why matching, settlement status, and reconciliation are separate controls.'),
    link('Read the financial market intermediaries guide', '/blog/financial-market-intermediaries/'),
  ],
  'retail-banking-operations': [
    heading('Connect retail banking work with the product lifecycle'),
    paragraph('Retail banking operations supports products through onboarding, servicing, transactions, monitoring, reconciliation, complaints, changes, and closure. Product terms and approval authority remain separate from the associate\'s processing responsibilities, so learners should map both the customer journey and the internal control hand-offs.'),
    link('Explore financial products and banking services', '/blog/financial-products-and-services-banking/'),
  ],
});

function createGuide({
  id,
  routeId,
  path,
  title,
  description,
  h1,
  breadcrumbLabel,
  primaryKeyword,
  secondaryKeywords,
  body,
  relatedGuideIds,
  relatedRouteIds,
  updatedAt = GUIDE_DATE,
}) {
  return Object.freeze({
    id,
    routeId,
    path,
    title,
    description,
    h1,
    breadcrumbLabel,
    primaryKeyword,
    secondaryKeywords: Object.freeze(secondaryKeywords),
    body: Object.freeze([...body, ...(GUIDE_DEPTH_ADDITIONS[id] || []), ...getJobIntentDepthBlocks(id)]),
    author: GUIDE_AUTHOR,
    publishedAt: GUIDE_DATE,
    updatedAt: JOB_INTENT_GUIDE_IDS.includes(id) ? JOB_INTENT_REVIEW_DATE : updatedAt,
    relatedGuideIds: Object.freeze(relatedGuideIds),
    relatedRouteIds: Object.freeze(relatedRouteIds),
    seo: Object.freeze({ title, description }),
  });
}

export const CAREER_GUIDES = Object.freeze([
  createGuide({
    id: 'investment-banking-operations',
    routeId: 'career-guide-investment-banking-operations',
    path: '/career-guides/investment-banking-operations/',
    title: 'Investment Banking Operations Career Guide | Centaur Careers',
    description: 'Learn what investment banking operations involves, how post-trade workflows work, which skills matter, and how graduates can explore this career direction.',
    updatedAt: '2026-09-29',
    h1: 'Investment Banking Operations: Career, Roles & Skills',
    breadcrumbLabel: 'Investment Banking Operations',
    primaryKeyword: 'what is investment banking operations',
    secondaryKeywords: [
      'investment banking operations meaning',
      'investment banking operations process',
      'investment banking operations workflow',
      'investment banking operations skills',
      'investment banking operations roles and responsibilities',
      'front office middle office back office investment banking',
    ],
    body: [
      paragraph('Investment banking operations is the control, processing, and support work that helps financial-market activity move accurately from a trade decision to completion. It is an operations career direction rather than the deal-making work of the front office.'),
      heading('Investment banking operations meaning and work'),
      paragraph('Operations teams help record transactions, confirm details, coordinate settlement, investigate breaks, maintain records, and support reporting. The exact workflow differs by product and institution, but the common purpose is reliable processing, timely control, and accurate information.'),
      heading('An example of the work behind the role'),
      paragraph('Imagine a trade record lists 100 units while the counterparty confirmation lists 10. An operations analyst would identify the mismatch, compare the source records and trade identifiers, record the break, and ask the responsible team to confirm the correct quantity before the workflow proceeds. The analyst should not change either record just to make the numbers agree. This is an illustrative learning example; actual controls and approval rights belong to the employer.'),
      link('Investigate the 100-versus-10 trade break with a downloadable case', '/blog/settlement-trade-break-worked-example/'),
      link('Follow a trade from capture to settlement', '/career-guides/trade-lifecycle/', 'career-guide-trade-lifecycle'),
      heading('Which task tests which skill?'),
      list([
        'Trade support: compare the trade identifier, security, quantity, price, and dates across records; this tests accuracy and clear exception writing.',
        'Settlement support: check the instruction and status against the confirmed trade; this tests process discipline and timely escalation.',
        'Reconciliation: trace an unmatched balance or position to the first differing source record; this tests evidence handling rather than guesswork.',
      ]),
      heading('What does the investment banking operations process include?'),
      list([
        'Capture and validate transaction details after a trade is agreed.',
        'Confirm instructions and coordinate the movement of cash or securities during settlement.',
        'Reconcile internal records with counterparty, custodian, or platform records.',
        'Investigate exceptions and route unresolved breaks to the right team.',
        'Process events such as dividends, splits, redemptions, or other corporate actions when they apply.',
        'Maintain an audit-friendly record of actions, approvals, and status changes.',
      ], true),
      heading('Core functions and examples'),
      paragraph('Common investment banking operations topics include trade settlements, reconciliation, corporate actions, and fund accounting. A learner may encounter different names for these functions, but each requires attention to data quality, deadlines, controls, and escalation.'),
      list([
        'Settlements: making sure the agreed exchange of cash and securities completes correctly.',
        'Reconciliation: comparing records and explaining differences before they become larger issues.',
        'Corporate actions: updating positions and instructions when an issuer event affects an account or fund.',
        'Fund accounting: supporting the records and calculations used to understand a fund position and activity.',
      ]),
      heading('How to read an investment banking operations job description'),
      paragraph('Job titles vary, so look for the task and control language beneath the title. A posting that mentions trade support or confirmation matching is pointing to transaction-detail checks and exception follow-up. Settlement or clearing language points to instruction, status, deadline, and hand-off monitoring. Reconciliation language means comparing records and explaining breaks. Corporate-actions or fund-accounting language signals product-specific records and events that need careful review.'),
      list([
        'Highlight each verb in the posting: match, validate, reconcile, process, monitor, investigate, report, or escalate. These verbs usually reveal the actual work better than a broad title.',
        'Note the object of the task: trade, cash, position, instruction, client record, event, or report. This tells you which workflow vocabulary to study.',
        'Separate required tools and eligibility from preferred skills. Do not assume that a tool is mandatory if the employer labels it preferred, and do not claim proficiency you cannot demonstrate.',
        'Look for the control boundary: what the analyst checks, what requires approval, and which exceptions must be routed to another team.',
        'Prepare one truthful example that demonstrates a relevant skill, such as checking structured data or documenting an unresolved difference; label classroom or fictional practice accurately.',
      ]),
      heading('Front office, middle office, and back office'),
      paragraph('The front office generally focuses on client activity, markets, and transactions. Middle-office teams support controls, risk, trade support, and information quality. Back-office or operations teams focus on processing, settlement, reconciliation, records, and servicing. Boundaries vary by organization, so job descriptions should be read carefully rather than judged by the label alone.'),
      link('See how operations fits among investment banking teams', '/blog/investment-banking-teams-operations/'),
      heading('Skills required for investment banking operations'),
      list([
        'Accuracy when working with transaction details, dates, quantities, and reference data.',
        'Process discipline and the ability to follow documented controls.',
        'Clear written communication when explaining a break or requesting action.',
        'Comfort with structured data, spreadsheets, workflow tools, and repeatable checks.',
        'Prioritisation when several exceptions have different deadlines or business impact.',
        'Curiosity about how products, counterparties, and post-trade processes fit together.',
      ]),
      heading('How can a graduate start exploring this career?'),
      paragraph('Start by learning the trade lifecycle, settlement, reconciliation, corporate actions, and basic financial terminology. Then practise explaining a process step by step, investigating a sample break, and writing a concise escalation. A course should connect these concepts to realistic scenarios and interview preparation without presenting one job title as the only possible outcome.'),
      link('Explore the Investment Banking Operations module', '/courses/investment-banking-operations/', 'investment-banking-operations'),
      heading('How the Financial Operations Masterclass relates'),
      paragraph('Investment Banking Operations is presented as one subject within Centaur Careers\' Financial Operations Masterclass. The program lists trade settlements, reconciliation, corporate actions, and fund accounting among its practical BFSI topics, alongside other banking and finance operations directions.'),
      link('View the Financial Operations Masterclass', '/courses/', 'courses'),
      faq('Is investment banking operations the same as investment banking?', 'No. Investment banking can refer to front-office activities such as advisory, capital markets, or deal work. Investment banking operations supports the processing, control, settlement, reconciliation, and records connected with financial activity.'),
      faq('Is investment banking operations suitable for freshers?', 'It can be a useful direction for graduates who enjoy structured processes, accuracy, investigation, and financial-market workflows. Entry requirements vary by employer, so candidates should compare each role description and build the skills it requests.'),
    ],
    relatedGuideIds: ['trade-lifecycle', 'finance-careers-after-graduation', 'finance-operations'],
    relatedRouteIds: ['courses', 'investment-banking-operations', 'career-guide-trade-lifecycle', 'career-guide-finance-operations', 'career-guide-finance-careers-after-graduation'],
  }),
  createGuide({
    id: 'kyc-aml-analyst',
    routeId: 'career-guide-kyc-aml-analyst',
    path: '/career-guides/kyc-aml-analyst/',
    title: 'KYC & AML Analyst Career Guide | Centaur Careers',
    description: 'Understand KYC and AML, the customer due-diligence workflow, analyst responsibilities, useful skills, and the relationship to BFSI operations training.',
    updatedAt: '2026-09-26',
    h1: 'KYC & AML Analyst Career Guide',
    breadcrumbLabel: 'KYC & AML Analyst',
    primaryKeyword: 'what is KYC in banking',
    secondaryKeywords: [
      'what is AML in banking',
      'KYC and AML difference',
      'KYC AML process',
      'customer due diligence process',
      'transaction monitoring in AML',
      'how to become KYC analyst',
    ],
    body: [
      paragraph('KYC and AML are related compliance functions used to understand customers, assess risk, and identify activity that needs review. KYC means Know Your Customer. AML means Anti-Money Laundering. A KYC or AML analyst works with information, procedures, alerts, and documented decisions.'),
      heading('What is KYC in banking?'),
      paragraph('KYC is the process of collecting and reviewing customer information so an institution can understand who it is dealing with and the nature of the relationship. The review may include identity, ownership, business activity, risk indicators, and supporting documents, depending on the institution and the type of account.'),
      heading('What is AML in banking?'),
      paragraph('AML is the wider set of controls used to identify, assess, monitor, and report potential money-laundering or related financial-crime risk. AML work can include transaction monitoring, sanctions or screening reviews, investigation, escalation, and record keeping. Procedures vary by institution and jurisdiction.'),
      heading('KYC vs AML: what is the difference?'),
      list([
        'KYC focuses on understanding and verifying the customer and the relationship.',
        'AML covers the broader control framework for detecting and responding to suspicious risk or activity.',
        'KYC information can support AML monitoring, but the two terms describe different parts of the control process.',
        'Both functions depend on accurate records, consistent procedures, documented reasoning, and appropriate escalation.',
      ]),
      heading('A typical KYC and AML workflow'),
      list([
        'Collect customer or entity information and supporting documents.',
        'Review the information for completeness, consistency, and risk indicators.',
        'Apply the relevant customer due-diligence or risk-rating procedure.',
        'Use screening or monitoring tools where the role requires them.',
        'Investigate exceptions and record the reasoning behind the outcome.',
        'Escalate cases that require specialist, compliance, or management review.',
      ], true),
      heading('What does a KYC or AML analyst do?'),
      paragraph('Analyst responsibilities depend on the team. They may review onboarding files, refresh existing customer records, investigate alerts, compare information across documents, prepare case notes, and communicate with internal stakeholders. Good analysts separate observed facts from assumptions and follow the team\'s escalation rules.'),
      heading('A KYC analyst job-description example'),
      paragraph('A typical entry-level task might be checking whether an onboarding file contains the customer and ownership information required by the employer\'s procedure. If two documents show different names or an ownership detail is missing, the analyst records the discrepancy, requests or routes the missing information, and escalates under the approved workflow. The analyst does not invent a value or make an unauthorised risk decision. Job descriptions and regulatory requirements differ by employer and product.'),
      heading('Where the KYC role meets wider financial-crime work'),
      paragraph('An onboarding analyst may collect and verify customer information; a screening or transaction-monitoring analyst may investigate a match or activity alert using that information. Some employers combine these tasks, while others assign them to separate teams. In either case, the analyst documents evidence and follows the assigned review and escalation authority.'),
      link('Compare KYC, AML, and financial-crime analyst work', '/blog/financial-crime-analyst-kyc-aml-career-guide/'),
      link('Work through a fictional KYC onboarding file and case note', '/blog/kyc-onboarding-case-file-example/'),
      heading('Skills that help in KYC and AML roles'),
      list([
        'Careful document and data review.',
        'Pattern recognition without jumping to conclusions.',
        'Clear case writing and evidence-based reasoning.',
        'Confidential handling of customer and business information.',
        'Consistency with checklists, procedures, and quality controls.',
        'Willingness to learn changing products, risks, and internal workflows.',
      ]),
      heading('How can a graduate explore KYC or AML work?'),
      paragraph('A useful starting point is to learn customer onboarding, due diligence, risk indicators, screening, transaction monitoring, and escalation. Practise reviewing a fictional case, listing the facts that are known, identifying the information still needed, and explaining what should be escalated. Do not treat a short course as a substitute for an employer\'s policies or required compliance training.'),
      heading('How the Financial Operations Masterclass relates'),
      paragraph('KYC and AML compliance is one of the subjects listed within Centaur Careers\' Financial Operations Masterclass. Its stated curriculum includes due diligence, transaction monitoring, SAR filing, and regulatory reporting as part of the broader BFSI learning path.'),
      link('Explore the Financial Operations Masterclass', '/courses/', 'courses'),
      faq('Are KYC and AML the same thing?', 'No. KYC is focused on understanding and reviewing the customer relationship. AML is the broader control framework for identifying, assessing, monitoring, and escalating financial-crime risk.'),
      faq('What should a KYC analyst learn first?', 'Start with customer onboarding, identity and entity information, due diligence, risk indicators, screening, clear case notes, and escalation discipline. The exact process should always follow the employer\'s current procedures.'),
      faq('Can KYC and AML work suit a fresher?', 'It can suit graduates who are detail-oriented, comfortable with documentation, and willing to follow controlled review processes. Employers may set different education, communication, tool, and experience requirements.'),
      faq('Does this guide provide an AML certification?', 'No. This is an informational career guide, not an AML certification or exam-preparation offer. Any third-party credential has its own awarding body, eligibility, syllabus, and current requirements; verify those directly with that organisation.'),
      link('Read the finance operations career guide', '/career-guides/finance-operations/', 'career-guide-finance-operations'),
    ],
    relatedGuideIds: ['finance-operations', 'retail-banking-operations', 'digital-payments-operations'],
    relatedRouteIds: ['courses', 'career-guide-finance-operations', 'career-guide-retail-banking-operations', 'career-guide-digital-payments-operations'],
  }),
  createGuide({
    id: 'finance-operations',
    routeId: 'career-guide-finance-operations',
    path: '/career-guides/finance-operations/',
    title: 'Finance Operations Careers in India | Centaur Careers',
    description: 'Learn what finance operations teams do, which workflows and skills matter, and how graduates can prepare for finance operations career paths.',
    updatedAt: '2026-09-29',
    h1: 'Finance Operations Careers: Roles, Skills & Pathways',
    breadcrumbLabel: 'Finance Operations Careers',
    primaryKeyword: 'finance operations career',
    secondaryKeywords: [
      'finance operations jobs',
      'finance operations analyst',
      'finance operations analyst skills',
      'finance operations analyst responsibilities',
      'finance operations analyst jobs for freshers',
      'finance operations analyst salary in India',
      'finance operations analyst interview questions',
      'how to become finance operations analyst',
      'BFSI operations career',
      'credit risk meaning in banking',
      'credit analysis and underwriting',
      'loan processing operations',
    ],
    body: [
      paragraph('Finance operations is the process and control work that keeps financial services activities accurate, timely, and ready for review. It can include transaction processing, reconciliations, lending or NBFC operations, credit-support work, risk controls, reporting, and service operations.'),
      heading('What is finance operations?'),
      paragraph('Finance operations connects a financial product or service to the repeatable work needed to deliver and control it. Teams use procedures, systems, records, approvals, and reconciliations to process information and identify exceptions. The exact responsibilities depend on the employer, product, and team structure.'),
      heading('What do finance operations teams do?'),
      list([
        'Process applications, transactions, instructions, or account activity according to defined procedures.',
        'Check data and documents for completeness, consistency, and required approvals.',
        'Reconcile records and investigate differences or failed processing.',
        'Support loan processing, credit analysis, risk management, or NBFC workflows when those functions belong to the team.',
        'Prepare status updates, reports, and operational records for internal stakeholders.',
        'Escalate exceptions, control issues, or customer-impacting delays through the correct channel.',
      ]),
      heading('Finance operations analyst responsibilities'),
      paragraph('An analyst may be responsible for reviewing queues, updating systems, checking documents, preparing reports, reconciling data, and communicating the status of open items. Strong performance depends on accuracy and consistency as much as speed. A clear work trail helps another person understand what was checked and what remains unresolved.'),
      heading('A finance operations analyst’s typical work cycle'),
      paragraph('The exact day depends on the product, employer, and team, but a controlled workflow often moves from prioritisation to processing, checking, exception handling, and closure. An analyst should follow the team’s current procedures and approval boundaries rather than assume every organisation uses the same sequence.'),
      list([
        'Review assigned work, cut-offs, ageing items, and any handover notes; flag urgent or customer-impacting exceptions through the right channel.',
        'Confirm that each request or transaction has the required identifiers, documents, status, and approvals before processing.',
        'Complete the permitted system or record update, then perform the required second check or reconciliation.',
        'For a mismatch, compare the authoritative source records, identify what is known and unknown, and record the evidence checked.',
        'Assign or escalate the next action to the authorised owner, track the open item, and verify the outcome before marking it complete.',
      ], true),
      heading('Fictional example: investigate a missing settlement record'),
      paragraph('Imagine a payment appears in an internal operations ledger but is absent from the matching bank file at the selected reporting cut-off. This is a fictional example, not a claim about a live payment rail or its processing times. The analyst checks the reference and date against the source records, confirms the file cut-off and latest authorised status, looks for a duplicate or reversal, and documents the difference. If it remains unexplained, the analyst routes it to the responsible team and records the owner and next check; they do not edit either source just to force a match.'),
      heading('How to answer a finance operations analyst interview question'),
      paragraph('For a question such as “What would you do if two records did not reconcile?”, organise the answer around the issue, checks, evidence, next action, and control. Explain which identifiers and dates you would compare, how you would distinguish a timing difference from an unresolved break, when you would escalate, and how you would verify closure. Be clear when an example is fictional practice rather than work you performed for an employer.'),
      link('Practise operations-focused finance interview questions', '/resources/investment-banking-interview-questions/', 'resource-investment-banking-interview-questions'),
      link('Review reconciliation steps and break handling', '/resources/reconciliation-in-finance/', 'resource-reconciliation-in-finance'),
      heading('How to research finance operations analyst salary in India'),
      paragraph('There is no single salary figure that applies to every finance operations analyst role. Compare recent postings for the same job family and location, and note experience level, employer type, shift, responsibilities, and whether a displayed amount is fixed pay or includes variable components. Record the source and posting date, compare several like-for-like roles, and confirm compensation directly with the employer; broad title matches can mix accounting, banking operations, and financial-analysis jobs.'),
      heading('Credit risk, assessment, and underwriting in finance operations'),
      paragraph('Credit assessment is a structured review of information relevant to a borrower and a proposed facility. Depending on the lender, product, and role, an analyst may organise financial and cash-flow information, check documents, compare the request with approved criteria, note risks or gaps, and route the case for an authorised decision. Credit risk describes the possibility that repayment will not happen as agreed; an operations or analyst role supports the documented process but does not independently approve credit unless that authority is part of the job.'),
      paragraph('At a high level, credit risk management means identifying and assessing credit exposure, applying the institution’s approved appraisal and control process, and monitoring for exceptions. A credit-support workflow may include checking the request and source documents, reviewing repayment information, recording gaps or risks, routing the case to an authorised decision-maker, and tracking follow-up under the lender’s procedure. This is not a model-building guide or a universal checklist.'),
      paragraph('The Reserve Bank of India’s lending guidance emphasises objective appraisal and repayment schedules that reflect cash flows. Requirements differ by regulated entity and facility, so this introductory explanation is not lending or regulatory advice.'),
      link('Read RBI guidance on credit appraisal and repayment schedules', 'https://www.rbi.org.in/scripts/NotificationUser.aspx?Id=12822'),
      heading('Skills required for finance operations jobs'),
      list([
        'Numerical and data accuracy.',
        'Working knowledge of spreadsheets and structured information.',
        'Process adherence and control awareness.',
        'Professional email and stakeholder communication.',
        'Problem solving for exceptions and reconciliation breaks.',
        'Time management across queues, deadlines, and follow-ups.',
      ]),
      heading('Finance operations compared with investment banking operations'),
      paragraph('Finance operations is a broad career direction covering several financial-services processes. Investment banking operations is a more specific direction focused on financial-market and post-trade workflows such as settlements, reconciliation, corporate actions, and fund accounting. They share process discipline and control skills, but the products and daily activities can differ.'),
      link('Read the Investment Banking Operations career guide', '/career-guides/investment-banking-operations/', 'career-guide-investment-banking-operations'),
      heading('How can a graduate prepare for finance operations?'),
      paragraph('Build a foundation in financial terminology, process mapping, data checks, reconciliation, documentation, and professional communication. Practise taking a simple workflow, identifying inputs and outputs, recording a control check, and explaining what happens when the information does not match. Then compare roles instead of applying to every job with the same resume.'),
      heading('How the Financial Operations Masterclass relates'),
      paragraph('Finance Operations is one of the career directions shown within Centaur Careers\' Financial Operations Masterclass. The approved program material describes NBFC, loan processing, credit analysis, and risk management as topics associated with this direction.'),
      link('Explore the Finance Operations module', '/courses/finance-operations/', 'finance-operations'),
      faq('What is a finance operations analyst?', 'A finance operations analyst supports controlled processing and review work in a financial-services team. Depending on the role, this can include data checks, reconciliations, documentation, reporting, queue management, and exception handling.'),
      faq('Can a fresher apply for finance operations analyst jobs?', 'Check each employer’s current eligibility and task requirements rather than assuming every analyst vacancy is entry-level. Look for the stated education and experience, spreadsheet or accounting requirements, communication expectations, shift, and location. Prepare one clearly labelled fictional workflow or reconciliation exercise to explain how you check information and escalate an unresolved exception.'),
      faq('What questions may be asked in a finance operations analyst interview?', 'Questions may ask how you check data, investigate a reconciliation difference, prioritise open work, document an exception, or communicate a delay. Use a structured answer: state the issue, describe the checks and evidence, explain the authorised next action, and say how you would verify closure. The actual questions vary by employer and role.'),
      faq('How much does a finance operations analyst earn in India?', 'Pay varies with location, employer, experience, shift, and the work involved, so a single undated number can be misleading. Compare recent postings for closely matched roles, check whether figures describe fixed or total compensation, and verify the current offer with the employer.'),
      faq('Is finance operations a good career direction for graduates?', 'It can be a practical direction for graduates who prefer structured work, data accuracy, process improvement, and financial-services workflows. The best fit depends on the role requirements, the learner\'s interests, and the support available for building job-ready skills.'),
      faq('Does finance operations only mean accounting?', 'No. Some finance operations roles involve accounting-related records, but the wider field can also include banking operations, lending, NBFC processes, reconciliations, risk support, customer or account operations, and other controlled workflows.'),
      faq('What does credit risk mean in a finance operations context?', 'Credit risk is the possibility that a borrower or counterparty will not meet agreed repayment or other credit obligations. In an operations role, work may support accurate documentation, checks, analysis, and escalation; lending criteria and decision authority depend on the institution and product.'),
      faq('What is credit risk management?', 'Credit risk management is the institution’s process for identifying, assessing, controlling, and monitoring credit exposure. In a finance-operations or credit-support role, responsibilities may include accurate checks, records, case routing, and exception follow-up; policies, models, and approval authority are specific to the lender and product.'),
      link('See finance career options after graduation', '/career-guides/finance-careers-after-graduation/', 'career-guide-finance-careers-after-graduation'),
    ],
    relatedGuideIds: ['finance-careers-after-graduation', 'investment-banking-operations', 'kyc-aml-analyst'],
    relatedRouteIds: ['courses', 'finance-operations', 'career-guide-investment-banking-operations', 'career-guide-kyc-aml-analyst', 'career-guide-finance-careers-after-graduation', 'resource-investment-banking-interview-questions', 'resource-reconciliation-in-finance'],
  }),
  createGuide({
    id: 'trade-lifecycle',
    routeId: 'career-guide-trade-lifecycle',
    path: '/career-guides/trade-lifecycle/',
    title: 'Trade Lifecycle in Investment Banking | Centaur Careers',
    description: 'Understand the front-to-back trade lifecycle, settlement, reconciliation, exceptions, and skills used in investment banking operations.',
    updatedAt: '2026-09-29',
    h1: 'Trade Lifecycle in Investment Banking: A Practical Guide',
    breadcrumbLabel: 'Trade Lifecycle',
    primaryKeyword: 'trade lifecycle in investment banking',
    secondaryKeywords: [
      'trade life cycle explained',
      'trade life cycle meaning',
      'trade lifecycle steps',
      'trade lifecycle settlement process',
      'front to back trade lifecycle',
      'settlement analyst roles and responsibilities',
      'reconciliation analyst roles and responsibilities',
    ],
    body: [
      paragraph('The trade lifecycle is the sequence of activities that takes a financial transaction from an initial decision through confirmation, settlement, reconciliation, and ongoing record keeping. In investment banking operations, understanding this sequence helps an analyst see where information is created, checked, transferred, and controlled.'),
      heading('What is the trade life cycle (trade lifecycle)?'),
      paragraph('A trade lifecycle is not one identical checklist for every product. Equity, bond, fund, foreign-exchange, and derivative workflows can have different fields, parties, dates, and settlement requirements. The useful common idea is a controlled path from trade capture to completion, with exceptions managed along the way.'),
      heading('Front-to-back trade lifecycle steps'),
      list([
        'Trade capture: record the agreed transaction in the relevant system.',
        'Enrichment and validation: add reference information and check key fields.',
        'Confirmation and affirmation: compare details with the other party and resolve differences.',
        'Settlement instruction: prepare the cash and securities instructions needed for completion.',
        'Settlement: monitor whether the exchange completes on the expected date.',
        'Reconciliation and reporting: compare records, investigate breaks, and retain the required operational trail.',
      ], true),
      heading('What information moves between lifecycle stages?'),
      paragraph('A useful way to learn the trade lifecycle is to follow both the transaction and its evidence. The next team should be able to tell which authorised record it received, what checks were completed, what status applies, and what action remains. The exact message formats, cut-offs, settlement cycles, and control owners vary by market, product, and institution.'),
      list([
        'Capture and validation: an authorised trade record supplies identifiers, parties, product details, quantity, price, and relevant dates; validation checks required fields and reference data before downstream processing.',
        'Confirmation or affirmation: the parties compare the agreed economic details. A mismatch becomes a visible exception with an owner and next action; it is not resolved by silently overwriting one side.',
        'Instruction and settlement monitoring: the confirmed transaction informs the relevant cash or securities instructions. Operations checks completeness and status against the approved workflow and tracks time-sensitive exceptions.',
        'Reconciliation and closure: internal and external records are compared after processing. The analyst classifies differences, retains evidence, routes any authorised correction, and verifies the closing status.',
      ]),
      heading('Worked example: follow one trade through the lifecycle'),
      paragraph('Suppose an investor agrees to buy 100 shares. This fictional example follows the information and checks, not a prescribed market timetable. Real steps, systems, and approval rights vary by product, market, and institution.'),
      list([
        'Capture: record the security, 100-share quantity, price, parties, trade date, and expected settlement date from the authorised trade record.',
        'Validate and confirm: compare those fields with the counterparty confirmation. If the confirmation says 10 shares, record an unmatched trade and route the discrepancy to the responsible team; do not alter either source to force a match.',
        'Prepare and monitor settlement: after the authorised correction or confirmation, check the cash and securities instructions and follow their statuses through the expected exchange.',
        'Reconcile: compare the resulting internal position and cash records with the relevant external records. Investigate any missing movement or remaining difference.',
        'Close or escalate: retain the evidence, owner, action, approval, and final status under the employer\'s procedure; escalate an unresolved or time-sensitive break.',
      ], true),
      link('Practise the 100-share versus 10-share break with source records', '/blog/settlement-trade-break-worked-example/'),
      heading('Why settlement and reconciliation matter'),
      paragraph('Settlement is the point at which the agreed exchange of cash or securities is completed. Reconciliation checks whether internal records agree with external or related records. A difference may come from timing, missing data, an instruction issue, or a real processing error. The analyst must investigate the cause rather than simply overwrite one record.'),
      heading('Where do exceptions appear?'),
      list([
        'A trade detail does not match the counterparty record.',
        'An instruction is incomplete or reaches the workflow late.',
        'The expected cash or security movement does not appear.',
        'A corporate action changes a position or entitlement that needs review.',
        'Internal and external records show different balances, dates, or statuses.',
      ]),
      link('See how reconciliation finds unmatched records', '/resources/reconciliation-in-finance/', 'resource-reconciliation-in-finance'),
      heading('Roles connected with the trade lifecycle'),
      paragraph('Trade support, settlement, reconciliation, corporate-actions, fund-accounting, and middle-office roles can each own part of the lifecycle. Titles and ownership models vary. What remains consistent is the need to understand upstream and downstream effects, communicate clearly, and document resolutions.'),
      heading('Skills for trade lifecycle work'),
      list([
        'A step-by-step understanding of transaction processing.',
        'Accuracy with dates, identifiers, quantities, currencies, and status fields.',
        'Ability to compare records and isolate the first point of difference.',
        'Clear escalation notes that explain the issue and requested action.',
        'Comfort working with queues, deadlines, procedures, and control evidence.',
      ]),
      heading('How to prepare for trade lifecycle interview questions'),
      paragraph('Practise explaining the lifecycle in your own words, then apply it to a simple transaction example. Be ready to describe what you would check when a trade is unmatched, a settlement fails, or two records disagree. A good answer explains the evidence you would review, the team you would contact, and how you would record the resolution.'),
      link('Explore the Investment Banking Operations module', '/courses/investment-banking-operations/', 'investment-banking-operations'),
      heading('How this guide relates to Centaur Careers'),
      paragraph('Trade settlements and reconciliation are listed within the Investment Banking Operations direction of Centaur Careers\' Financial Operations Masterclass. The course page presents that direction as a module within the wider program, not as a separate program promise.'),
      link('View the Investment Banking Operations module', '/courses/investment-banking-operations/', 'investment-banking-operations'),
      faq('What is the simplest way to explain a trade lifecycle?', 'Explain it as a controlled sequence from trade capture and validation to confirmation, settlement, reconciliation, exception handling, and record keeping. Add that the exact steps depend on the product and institution.'),
      faq('What does a settlement analyst do?', 'A settlement analyst monitors and supports the completion of cash and securities movements, checks instructions and statuses, investigates failed or delayed items, and communicates the next action according to the team process.'),
      link('Read what investment banking operations involves', '/career-guides/investment-banking-operations/', 'career-guide-investment-banking-operations'),
    ],
    relatedGuideIds: ['investment-banking-operations', 'finance-operations', 'digital-payments-operations'],
    relatedRouteIds: ['courses', 'investment-banking-operations', 'career-guide-investment-banking-operations', 'career-guide-finance-operations', 'career-guide-digital-payments-operations'],
  }),
  createGuide({
    id: 'finance-careers-after-graduation',
    routeId: 'career-guide-finance-careers-after-graduation',
    path: '/career-guides/finance-careers-after-graduation/',
    title: 'Finance Careers After Graduation | Centaur Careers',
    description: 'Explore finance career directions after graduation, compare BFSI operations pathways, build practical skills, and choose a focused learning plan.',
    updatedAt: '2026-09-29',
    h1: 'Finance Careers After Graduation: A Practical Guide',
    breadcrumbLabel: 'Finance Careers After Graduation',
      primaryKeyword: 'finance careers after graduation',
    secondaryKeywords: [
      'investment banking operations after BCom',
      'finance jobs after BCom',
      'finance jobs after graduation',
      'banking jobs after BBA',
      'finance operations career after BBA',
      'KYC AML career after BCom',
      'short term finance course after graduation',
    ],
    body: [
      paragraph('After graduation, a finance career is not limited to one job title or one qualification. Graduates can explore investment banking operations, retail banking, finance operations, KYC and AML compliance, digital payments, or FinTech operations. The right starting point depends on interests, strengths, eligibility, learning format, and the actual requirements of the roles being considered.'),
      heading('Finance jobs after BCom, BBA, or graduation: career paths'),
      list([
        'Investment Banking Operations: settlement, reconciliation, corporate actions, and fund accounting workflows.',
        'Retail Banking: relationship management, branch operations, loan officer work, and NRI banking.',
        'Finance Operations: NBFC processes, loan processing, credit analysis, and risk management.',
        'KYC and AML Compliance: due diligence, transaction monitoring, and regulatory reporting support.',
        'Digital Payments: payment operations, disputes, and reconciliation across digital payment workflows.',
        'FinTech and Neo-Banking: digital lending, product operations, compliance, and customer success directions.',
      ]),
      heading('BCom, BBA, MBA, and other graduate backgrounds'),
      paragraph('A BCom or BBA background can provide useful exposure to business, accounting, or finance concepts, while an MBA may add broader management study. Graduates from other fields can also build a finance foundation through structured learning. Centaur Careers states that its program is open to graduates from any field, including BBA, BCom, BA, BSc, BTech, and MBA, with final-year students also able to apply.'),
      heading('How to choose a first finance role'),
      list([
        'Match the role to the work you enjoy: customer interaction, analysis, documentation, controls, or process execution.',
        'Read the job description for product knowledge, tools, communication, shift, and eligibility requirements.',
        'Choose one or two related directions to prepare for instead of using a generic resume everywhere.',
        'Build examples that show accuracy, ownership, problem solving, and professional communication.',
        'Ask how the training or support process works, including current eligibility and participation requirements.',
      ], true),
      heading('Choose a finance direction by the work you would do'),
      paragraph('If you enjoy comparing records and finding differences, investigate reconciliation or trade-support roles. If you prefer document review and case writing, examine KYC and AML analyst work. If you like customer conversations and service follow-up, read retail banking role descriptions. For each direction, save two current vacancies, list their repeated requirements, and build one truthful project or practice example that shows a relevant skill.'),
      heading('Compare finance career paths by daily work and practice evidence'),
      list([
        'Investment banking operations: compare transaction records, monitor settlement status, and investigate unmatched details. A fictional trade-matching worksheet and a concise break note can show process reasoning without claiming employer experience.',
        'Retail banking: support account, loan, or service workflows and communicate status to customers or internal teams. A sample process map can show where document checks, approvals, and follow-up occur.',
        'Finance operations: process financial-service requests, reconcile information, maintain records, and route exceptions. A small fictional queue with an ageing tracker can demonstrate prioritisation and control awareness.',
        'KYC and AML: review customer or entity information, record observed facts, identify missing evidence, and escalate under the applicable procedure. A fictional case note should distinguish evidence from assumptions and should not invent a risk decision.',
        'Digital payments: trace transaction status across records, reconcile a batch, and route disputes or exceptions. A fictional matching exercise can show how you check references, amounts, dates, and status before drawing a conclusion.',
        'FinTech operations: coordinate product, customer, process, and control hand-offs. A simple incident or service-request map can show how an issue is recorded, assigned, updated, and closed.',
      ]),
      paragraph('These are practice ideas, not required portfolio formats or guarantees of employer acceptance. Use only fictional or public-safe information; never include customer, employer, or confidential data.'),
      link('See the investment banking operations role and workflow', '/career-guides/investment-banking-operations/', 'career-guide-investment-banking-operations'),
      link('See KYC and AML analyst tasks', '/career-guides/kyc-aml-analyst/', 'career-guide-kyc-aml-analyst'),
      link('See retail banking operations roles', '/career-guides/retail-banking-operations/', 'career-guide-retail-banking-operations'),
      heading('Skills that transfer across BFSI roles'),
      paragraph('Financial terminology, spreadsheet confidence, data accuracy, process mapping, documentation, communication, and interview practice are useful across several operations teams. Candidates should add role-specific knowledge as they narrow their target: trade lifecycle for investment operations, due diligence for KYC and AML, or lending workflow for finance operations.'),
      link('Read the finance operations career guide', '/career-guides/finance-operations/', 'career-guide-finance-operations'),
      heading('What makes a short-term finance course useful?'),
      paragraph('A short course is most useful when it explains the work clearly, gives learners a structured opportunity to practise, and connects the learning to realistic interview conversations. Before enrolling, confirm the curriculum, duration, delivery format, fees, assessment process, certificate wording, and current placement-support terms with the provider.'),
      link('Use the finance course decision checklist', '/career-guides/choosing-finance-career-course/', 'career-guide-choosing-finance-career-course'),
      heading('How the Financial Operations Masterclass fits'),
      paragraph('Centaur Careers describes a six-week Financial Operations Masterclass, also called the Finance Career Program, with practical BFSI training, finance-track guidance, projects, case studies, mock interviews, and placement support. Ask the team to explain the current program details before making a decision.'),
      link('Explore the Financial Operations Masterclass', '/courses/', 'courses'),
      faq('Can a BCom graduate enter finance operations?', 'A BCom graduate can explore finance operations, banking operations, compliance, lending, and related entry-level directions. The actual entry requirements vary by employer, so build the skills named in the role description and confirm eligibility before applying.'),
      faq('Do graduates need an MBA for BFSI operations roles?', 'Not every BFSI operations role has the same education requirement. Some roles may consider graduates from different backgrounds, while others may request specific study or experience. Check the current job description rather than assuming one qualification is required for every path.'),
      faq('How should a graduate compare finance courses?', 'Compare the curriculum, practical exercises, duration, learning mode, assessment, support terms, certificate wording, and the clarity of the provider\'s conditions. Choose the course whose scope and participation requirements match your current goal.'),
      faq('What is the best finance course after BCom?', 'There is no best course for every BCom graduate. Start with the role you want, compare its current job requirements with the published syllabus and practical work, and check the delivery mode, total fees, credential, and written career-support terms. Centaur Careers offers one six-week Financial Operations Masterclass covering several BFSI operations subjects; review its full scope before deciding whether it fits your goal.'),
      link('Compare finance courses after graduation, including the BTech pathway', '/best-finance-course-after-graduation/', 'lead-best-finance-course-after-graduation'),
      link('Read the investment banking operations career guide', '/career-guides/investment-banking-operations/', 'career-guide-investment-banking-operations'),
    ],
    relatedGuideIds: ['finance-operations', 'investment-banking-operations', 'kyc-aml-analyst', 'retail-banking-operations'],
    relatedRouteIds: ['courses', 'career-guide-finance-operations', 'career-guide-investment-banking-operations', 'career-guide-kyc-aml-analyst', 'career-guide-retail-banking-operations', 'lead-best-finance-course-after-graduation'],
  }),
  createGuide({
    id: 'retail-banking-operations',
    routeId: 'career-guide-retail-banking-operations',
    path: '/career-guides/retail-banking-operations/',
    title: 'Retail Banking Operations Guide | Centaur Careers',
    description: 'Learn what retail banking operations means, how common workflows work, which roles and skills matter, and how graduates can prepare.',
    updatedAt: '2026-09-27',
    h1: 'Retail Banking Operations: Meaning, Roles & Skills',
    breadcrumbLabel: 'Retail Banking Operations',
    primaryKeyword: 'retail banking operations meaning',
    secondaryKeywords: [
      'retail banking operations process',
      'retail banking operations jobs',
      'retail banking analyst',
      'customer onboarding in retail banking',
      'loan operations in retail banking',
      'retail banking career after BCom',
      'bank relationship manager responsibilities',
      'relationship manager role in banking',
    ],
    body: [
      paragraph('Retail banking operations is the process and service work that supports products and activities for individual customers and small businesses. It can include account opening, customer information checks, loan processing, deposits, servicing requests, branch controls, and record maintenance.'),
      heading('What does retail banking operations mean?'),
      paragraph('Retail banking operations connects customer-facing banking activity with the checks and processing needed behind it. Some work happens in a branch or service team, while other work is handled by central operations. The split depends on the bank, product, channel, and operating model.'),
      heading('Common retail banking operations processes'),
      list([
        'Customer onboarding and account-opening checks.',
        'Review and maintenance of customer or account information.',
        'Deposit, payment, and servicing instructions.',
        'Loan application, document, and processing support.',
        'Reconciliation, exception handling, and branch or process controls.',
        'Customer query routing and follow-up on pending actions.',
      ], true),
      heading('Roles in retail banking operations'),
      paragraph('A retail banking team may include relationship managers, branch-operations staff, loan officers, service associates, operations analysts, and specialists supporting onboarding or controls. The responsibilities overlap in places but are not interchangeable. Read the role scope and customer interaction expectations carefully.'),
      heading('What does a bank relationship manager do?'),
      paragraph('A relationship manager in a bank generally maintains a relationship with an assigned customer group, understands service needs, coordinates requests with relevant teams, explains products within the bank’s approved process, and keeps appropriate records. The balance of sales, service, portfolio, and operational responsibilities varies by bank, customer segment, and role. This is a general career explanation, not an official job description or a promise of a particular vacancy.'),
      faq('What skills are useful for a retail bank relationship manager?', 'Customer communication, careful listening, product understanding, follow-up, accurate records, and knowing when to refer a request to a specialist are useful. Employers define role-specific targets, eligibility, and responsibilities in their own job descriptions.'),
      heading('Customer onboarding, KYC, and loan operations'),
      paragraph('Onboarding requires accurate customer information and appropriate checks. Loan operations may involve collecting documents, updating application status, coordinating reviews, and maintaining records. KYC is one part of a controlled onboarding process, while credit and lending workflows may require their own review steps.'),
      heading('Skills for retail banking operations jobs'),
      list([
        'Clear and respectful customer communication.',
        'Accuracy with forms, documents, account information, and status updates.',
        'Understanding of procedures, approvals, controls, and escalation.',
        'Ability to manage follow-ups and pending work.',
        'Basic financial and banking terminology.',
        'Professional judgement about when to ask for help or escalate an exception.',
      ]),
      heading('Retail banking compared with investment banking operations'),
      paragraph('Retail banking operations is usually connected with customer accounts, branches, lending, deposits, and service processes. Investment banking operations is more closely connected with market transactions, settlement, reconciliation, corporate actions, and fund accounting. Both need accuracy and control discipline, but the customers, products, and workflows differ.'),
      link('Read the Investment Banking Operations career guide', '/career-guides/investment-banking-operations/', 'career-guide-investment-banking-operations'),
      heading('How graduates can prepare'),
      paragraph('Learn the basic banking product vocabulary, practise explaining an account or loan workflow, and build examples that show customer focus and process accuracy. Interview preparation should cover the role\'s likely products, documentation, service situations, and escalation expectations.'),
      heading('How the Financial Operations Masterclass relates'),
      paragraph('Retail Banking is one of the career directions within Centaur Careers\' Financial Operations Masterclass. The program material lists relationship management, branch operations, loan officer work, and NRI banking as topics connected with this direction.'),
      link('Explore the Retail Banking module', '/courses/retail-banking/', 'retail-banking'),
      faq('What is retail banking operations in simple words?', 'It is the controlled processing and service work that supports individual-customer banking, including onboarding, account servicing, deposits, lending support, records, and branch or central operations.'),
      faq('Are all relationship manager jobs the same?', 'No. A bank relationship manager, an investment relationship manager, and other relationship-manager roles can have different customers, products, targets, and responsibilities. Check the employer, customer segment, and job description before treating a general explanation as a role specification.'),
      faq('Is retail banking operations suitable after BCom or BBA?', 'It can be a relevant direction for graduates interested in banking products, customers, documentation, and process work. Employers set their own education and role requirements, so compare the actual job description.'),
      faq('Does retail banking operations involve customer interaction?', 'Some roles are customer-facing and others are primarily central or back-office. Check the role description for the expected level of calls, branch work, service handling, and internal processing.'),
      link('Explore finance careers after graduation', '/career-guides/finance-careers-after-graduation/', 'career-guide-finance-careers-after-graduation'),
    ],
    relatedGuideIds: ['finance-careers-after-graduation', 'kyc-aml-analyst', 'finance-operations'],
    relatedRouteIds: ['courses', 'retail-banking', 'career-guide-finance-careers-after-graduation', 'career-guide-kyc-aml-analyst', 'career-guide-finance-operations'],
  }),
  createGuide({
    id: 'digital-payments-operations',
    routeId: 'career-guide-digital-payments-operations',
    path: '/career-guides/digital-payments-operations/',
    title: 'Digital Payment Operations Guide | Centaur Careers',
    description: 'Understand digital payment operations, payment processing, reconciliation, disputes, risk controls, and career skills for payments roles.',
    h1: 'Digital Payment Operations: Process, Roles & Skills',
    breadcrumbLabel: 'Digital Payment Operations',
    primaryKeyword: 'digital payment operations',
    secondaryKeywords: [
      'payments operations career',
      'payment operations analyst',
      'digital payments jobs for freshers',
      'UPI operations',
      'payment reconciliation',
      'chargeback operations',
    ],
    updatedAt: '2026-09-29',
    body: [
      paragraph('Digital payment operations is the processing, monitoring, reconciliation, and support work behind electronic payments. Teams may handle payment status, exceptions, settlements, disputes, merchant or customer queries, risk controls, and records across different products and channels.'),
      heading('What is digital payment operations?'),
      paragraph('A digital payment moves through several systems and parties before it is completed or returned. Operations teams help track that movement, identify exceptions, reconcile expected and actual records, and route issues to the right technical, risk, banking, or service team.'),
      heading('A simplified payment operations flow'),
      list([
        'A payment instruction is created through a customer, merchant, bank, or platform channel.',
        'The transaction is validated and routed through the relevant payment or banking workflow.',
        'The status is monitored for completion, failure, pending action, or return.',
        'Records are reconciled across the platform, bank, gateway, or merchant system.',
        'Disputes, refunds, exceptions, or suspected risk are investigated and escalated.',
        'The final status and supporting action are recorded for service and control purposes.',
      ], true),
      heading('Payment rails and operations topics'),
      paragraph('Centaur Careers lists SWIFT, RTGS, UPI and IMPS operations, payment disputes, and wallet reconciliations among its digital-payments topics. The workflow, cut-off, participant, and exception rules differ by rail, so learners should study each process as its own operating context rather than treating all payments as identical.'),
      heading('Reconciliation, disputes, and risk controls'),
      paragraph('Reconciliation compares records from different systems and helps identify missing, duplicated, delayed, or differently classified transactions. Dispute or chargeback work requires a clear case trail and correct routing. Risk controls may involve monitoring patterns, applying procedures, and escalating activity for specialist review.'),
      heading('Fictional payment reconciliation exercise'),
      paragraph('Consider a fictional merchant batch with three exceptions. The platform marks payment TX-104 for ₹1,250 as settled, while the bank settlement file shows ₹1,220 and a separately identified ₹30 fee. TX-105 for ₹800 is still marked pending in the platform and does not appear in the bank file at the selected cut-off. TX-106 for ₹450 appears twice in an export, but one row carries a reversed status. These examples illustrate investigation questions only; they do not describe a particular payment rail, provider rule, fee schedule, or live transaction.'),
      list([
        'For TX-104, match the reference, amount, status, and settlement date across the source records; verify the fee against the approved fee record before classifying the gross-to-net difference.',
        'For TX-105, confirm the reporting cut-off, expected processing window, and latest status from the authorised system before calling it missing. Record the owner and next check rather than assuming a failure.',
        'For TX-106, compare the unique reference, event status, timestamps, and any reversal record. Do not count both rows as completed payments or delete one just to make the total agree.',
      ], true),
      paragraph('A concise exception note should state the batch and cut-off, records compared, exact difference, evidence checked, provisional classification, risk or deadline, assigned owner, next action, and closure check. If the procedure does not authorise a correction, document and escalate the break instead of changing a source record.'),
      heading('Roles in payment operations'),
      list([
        'Payment operations analyst or processor.',
        'Reconciliation or settlement analyst.',
        'Merchant or customer operations specialist.',
        'Payment disputes or chargeback analyst.',
        'Payment risk or compliance operations analyst.',
        'Product or platform operations support.',
      ]),
      heading('Skills for digital payment jobs'),
      list([
        'Accuracy with transaction identifiers, amounts, dates, and statuses.',
        'Ability to follow a transaction across systems and explain the current state.',
        'Structured investigation of exceptions and mismatches.',
        'Clear communication with customers, merchants, banks, and internal teams.',
        'Awareness of privacy, access control, and operational risk.',
        'Comfort with queues, dashboards, spreadsheets, and documented procedures.',
      ]),
      heading('How to prepare for payments operations work'),
      paragraph('Begin with one payment flow and map its inputs, statuses, parties, controls, and possible exceptions. Practise reconciling a small sample, writing a dispute note, and explaining what evidence you would ask for. Then expand to other rails or products once the basic process is clear.'),
      heading('How the Financial Operations Masterclass relates'),
      paragraph('Digital Payments is listed as one of the subjects taught within Centaur Careers\' Financial Operations Masterclass. It sits alongside investment operations, compliance, retail banking, finance operations, and FinTech directions.'),
      link('View the Financial Operations Masterclass', '/courses/', 'courses'),
      faq('What does a payment operations analyst do?', 'A payment operations analyst monitors and processes payment activity, checks statuses and records, investigates exceptions, supports reconciliation or disputes, and escalates issues according to the team process.'),
      faq('How should an analyst investigate a failed or delayed UPI payment?', 'Start with the transaction reference, timestamp, current status, and the approved system or participant records available to the team. Check the relevant cut-off and procedure, preserve the case trail, communicate only verified status, and route unresolved items through the authorised support path. Processing timelines and next steps vary, so do not infer a universal resolution time from a general guide.'),
      faq('Is digital payment operations a technical job?', 'Some roles are highly operational, while others work closely with technology, product, risk, or data teams. The technical depth depends on the job description; every role still requires process understanding and accuracy.'),
      faq('What should a fresher learn for payment operations?', 'Start with payment flow, transaction statuses, reconciliation, disputes, basic risk controls, professional communication, and spreadsheet or workflow discipline. Then learn the specific rail and tools used by the target employer.'),
      link('Read the KYC and AML analyst guide', '/career-guides/kyc-aml-analyst/', 'career-guide-kyc-aml-analyst'),
    ],
    relatedGuideIds: ['kyc-aml-analyst', 'trade-lifecycle', 'retail-banking-operations'],
    relatedRouteIds: ['courses', 'career-guide-kyc-aml-analyst', 'career-guide-trade-lifecycle', 'career-guide-retail-banking-operations'],
  }),
  createGuide({
    id: 'financial-operations-faq',
    routeId: 'career-guide-financial-operations-faq',
    path: '/career-guides/financial-operations-faq/',
    title: 'Finance Operations Career FAQs | Centaur Careers',
    description: 'Clear answers about investment banking operations, KYC and AML, finance operations, graduate entry paths, and practical BFSI learning.',
    h1: 'Finance Operations Career FAQs',
    breadcrumbLabel: 'Finance Operations FAQs',
    primaryKeyword: 'which course is best for investment banking operations in India',
    secondaryKeywords: [
      'what should I learn for investment banking operations jobs',
      'can a BCom graduate get into investment banking operations',
      'is KYC AML a good career for freshers',
      'is finance operations a good career in India',
      'what skills do banks look for in operations freshers',
    ],
    updatedAt: '2026-09-29',
    body: [
      paragraph('Finance operations careers cover several BFSI directions, including investment banking operations, KYC and AML compliance, retail banking, digital payments, and finance operations. These answers are a starting point for comparison; always confirm the current role requirements before applying.'),
      heading('Choosing a finance operations path'),
      paragraph('Start with the type of work you want to practise. Trade lifecycle and reconciliation suit learners interested in post-trade process work. KYC and AML suit learners interested in controlled review and case investigation. Retail banking involves customer and product operations. Finance operations can include lending, NBFC, credit, risk, and process work.'),
      link('Compare the finance career paths after graduation', '/career-guides/finance-careers-after-graduation/', 'career-guide-finance-careers-after-graduation'),
      faq('What should I learn for investment banking operations jobs?', 'Learn trade capture, confirmation, settlement, reconciliation, corporate actions, fund-accounting concepts, operational controls, and professional escalation. Practise explaining a workflow and investigating a mismatch instead of memorising definitions alone.'),
      faq('Can a BCom graduate get into investment banking operations?', 'A BCom graduate can explore investment banking operations and related BFSI roles, subject to employer eligibility. Build practical process knowledge, financial terminology, accuracy, communication, and interview readiness, then compare the requirements for each role.'),
      faq('Can a BBA graduate work in investment banking operations?', 'A BBA graduate can explore the direction if the role accepts that background and the candidate can demonstrate the required finance, process, data, and communication skills. The employer\'s current description is the deciding reference.'),
      faq('Is KYC and AML a good career for freshers?', 'KYC and AML can suit freshers who prefer document review, controlled investigation, clear case writing, and compliance processes. The work requires patience and careful escalation, and each employer may use different procedures and requirements.'),
      link('Read the KYC & AML analyst guide', '/career-guides/kyc-aml-analyst/', 'career-guide-kyc-aml-analyst'),
      faq('Is finance operations a good career direction in India?', 'Finance operations can be a useful direction for graduates interested in structured financial-services work, including processing, reconciliation, lending, risk support, and reporting. The fit depends on the specific role, work environment, and the skills the learner wants to build.'),
      faq('What skills do banks look for in operations freshers?', 'Accuracy, process discipline, communication, spreadsheet confidence, customer or stakeholder handling, problem solving, and the ability to explain a workflow are useful foundations. Add product-specific knowledge for the role you target.'),
      faq('Do I need CFA or an MBA for investment banking operations?', 'There is no single qualification requirement for every operations role. Some employers may prefer a particular degree or experience, while others assess graduates on role-relevant skills. Review the current job description and do not assume an additional qualification is required for every path.'),
      faq('How long does it take to learn investment banking operations?', 'The answer depends on your starting point, the scope of the curriculum, and the practice required. A short course can introduce core concepts, but job readiness also requires repeated workflow practice, assessments, communication, and interview preparation.'),
      faq('Which course is best for investment banking operations in India?', 'There is no universally best course for every learner. Compare the actual syllabus with the roles you are targeting, then check whether it includes workflow practice, feedback or assessment, delivery mode, eligibility, duration, fees, certificate wording, and written support terms. Centaur Careers offers one Financial Operations Masterclass with investment banking operations as a module, not a separate standalone investment-banking course; review the current programme details before deciding.'),
      heading('What should I check before joining a course?'),
      list([
        'The exact curriculum and whether topics are taught as modules within a wider program.',
        'Learning mode, duration, fees, assessments, projects, and attendance expectations.',
        'Whether certificate wording and placement-support terms are available in writing.',
        'How interview preparation and opportunity access work under the current eligibility criteria.',
        'Whether the course matches the role direction you actually want to explore.',
      ]),
      link('Explore the Financial Operations Masterclass', '/courses/', 'courses'),
      faq('What is the relationship between this guide and Centaur Careers?', 'Centaur Careers presents investment banking operations, KYC and AML, retail banking, digital payments, finance operations, and FinTech as subjects or career directions within its Financial Operations Masterclass. Review the program page for provider-specific details.'),
      link('Read the finance operations career guide', '/career-guides/finance-operations/', 'career-guide-finance-operations'),
    ],
    relatedGuideIds: ['finance-careers-after-graduation', 'investment-banking-operations', 'kyc-aml-analyst', 'finance-operations'],
    relatedRouteIds: ['courses', 'career-guide-finance-careers-after-graduation', 'career-guide-investment-banking-operations', 'career-guide-kyc-aml-analyst', 'career-guide-finance-operations'],
  }),
  createGuide({
    id: 'choosing-finance-career-course',
    routeId: 'career-guide-choosing-finance-career-course',
    path: '/career-guides/choosing-finance-career-course/',
    title: 'How to Choose a Finance Career Course | Centaur Careers',
    description: 'Compare finance-course scope, practical learning, interview preparation, credentials, and published support terms before choosing a path after graduation.',
    updatedAt: '2026-09-26',
    h1: 'How to Choose a Finance Career Course',
    breadcrumbLabel: 'Choosing a Finance Course',
    primaryKeyword: getKeywordOwnership('/career-guides/choosing-finance-career-course/').primaryKeyword,
    secondaryKeywords: getKeywordOwnership('/career-guides/choosing-finance-career-course/').secondaryKeywords,
    body: [
      paragraph('Choosing a finance course is easier when you start with the role and work you want to understand, then compare syllabus, practice, teaching format, assessment, credential wording, and support terms. This guide is for graduates comparing finance learning options; it does not rank providers or promise a particular job outcome.'),
      heading('Start with the kind of finance work you want to explore'),
      paragraph('Investment banking operations focuses on controlled workflows such as trade support, settlements, reconciliations, and corporate actions. KYC and AML work centres on customer due diligence, screening, monitoring, and case documentation. Digital payments covers transaction processing, disputes, and reconciliation. Finance operations may include lending, NBFC processes, credit support, risk controls, and reporting. A broad job-oriented finance course should explain which of these subjects it actually teaches and at what depth.'),
      link('Map finance roles after graduation before selecting a course', '/career-guides/finance-careers-after-graduation/', 'career-guide-finance-careers-after-graduation'),
      list([
        'Read several current job descriptions and note repeated tasks, required tools, eligibility, and location.',
        'Match each course topic to a real workflow or skill—not only a job title in an advertisement.',
        'Ask whether practice, feedback, assessment, and interview preparation are included, and request the details in writing.',
        'Check duration, fees, cohort dates, attendance, delivery mode, certificate wording, and refund terms before paying.',
        'Separate a provider’s published support promise from your personal eligibility and the exact written conditions.',
      ], true),
      heading('Three questions to send before paying a course fee'),
      list([
        'Which exact modules, exercises, live hours, and assessments are included in the cohort I would join?',
        'What is the full amount payable, what does the completion certificate say, and where are the current refund conditions?',
        'What career support and eligibility conditions are written into the current offer, and which parts depend on employer decisions?',
      ], true),
      paragraph('Keep the provider\'s written answers next to the job descriptions you researched. If a course title suggests a separate KYC, payments, or investment banking qualification, ask whether that subject is a standalone course or a module in one broader programme.'),
      heading('Compare the program, not the promotional label'),
      paragraph('People searching for the best short term investment banking course, the best job oriented finance course, or the best finance course for freshers in India should compare like with like. Look at the instructor-led hours, workflow coverage, exercises, review method, current syllabus, and practical next steps. A short duration can make a course easier to schedule, but it does not by itself prove depth, recognition, or fit.'),
      paragraph('The same method applies when comparing the best finance operations course in India, the best KYC AML course in India, or the best banking operations course in India. Confirm whether KYC / AML or payments is a stand-alone offering or a module within a larger program, and whether any certificate is provider-issued or awarded by an outside body.'),
      link('Compare published investment banking operations course scopes and sources', '/compare/investment-banking-operations-courses/', 'comparison-investment-banking-operations'),
      heading('Interview preparation and placement-support wording'),
      paragraph('An investment banking course with interview preparation should state what learners practise: for example, explaining a workflow, answering role questions, or presenting a project. An investment banking course with placement support should define the support in written terms. Do not assume that “support” means a guaranteed selection, a particular employer, location, salary, or number of interviews.'),
      paragraph('Centaur Careers currently describes one course: the Financial Operations Masterclass. Investment Banking Operations, KYC / AML, Digital Payments, Retail Banking, Finance Operations, and FinTech are taught as subjects within it, not as separate courses. The published 100% Job Guarantee Program terms are on the placements page and should be read in full before making a decision.'),
      heading('Professional credentials and degree pathways are different choices'),
      paragraph('A short vocational program, an MBA, and a professional designation have different purposes, entry requirements, time commitments, assessments, and recognition. An investment banking certification vs MBA comparison should begin by checking the credential issuer and the roles each qualification is designed to support. Course completion does not equal a degree or an external professional designation.'),
      paragraph('Investment banking operations course vs CFA is not an apples-to-apples comparison: operations learning is centred on process execution and controls, while the CFA Program covers investment knowledge such as ethics, analysis, valuation, and portfolio management. Investment banking operations course vs financial modelling also depends on the intended work: modelling practice builds forecasting and valuation skills, while operations study focuses on accurate workflows and post-trade activity. Neither path is universally “better.”'),
      link('Review CFA Institute’s current CFA Program curriculum', 'https://www.cfainstitute.org/programs/cfa-program/curriculum'),
      faq('What should I compare in an investment banking operations course vs CFA decision?', 'Compare the work you want to do, syllabus, time and cost commitments, prerequisites, assessment, and the credential each path actually awards. Operations training and the CFA Program serve different learning objectives; confirm the current CFA curriculum on CFA Institute’s official site.'),
      faq('How do investment banking operations vs CFA and investment banking operations vs financial modelling differ?', 'Operations focuses on transaction processing, control, reconciliation, and exception handling. CFA study is a professional investment curriculum, while financial modelling practice focuses on structured forecasts and valuation models. Review actual syllabi before deciding.'),
      faq('Which is the best course for finance jobs after graduation?', 'There is no single best option for every graduate. Choose by target role, current employer requirements, curriculum detail, realistic practice, feedback, credential, total cost, and written career-support terms.'),
      faq('How do I evaluate the best short term investment banking course?', 'Check the real teaching hours, scope of operations workflows, practice and feedback, faculty information, assessment, certificate wording, and current terms. A short timetable alone is not evidence of job readiness.'),
      faq('What does placement support mean for this program?', 'Read the full 100% Job Guarantee Program description, eligibility, process, and terms on the placements page. Ask Centaur Careers to confirm the terms that apply to the current cohort before enrolling.'),
      link('Review the Financial Operations Masterclass', '/courses/', 'courses'),
      link('Read the published placement terms', '/placements/', 'placements'),
    ],
    relatedGuideIds: ['finance-careers-after-graduation', 'investment-banking-operations', 'kyc-aml-analyst'],
    relatedRouteIds: ['courses', 'placements', 'comparison-investment-banking-operations', 'career-guide-finance-careers-after-graduation', 'career-guide-investment-banking-operations', 'career-guide-kyc-aml-analyst'],
  }),
  createGuide({
    id: 'fintech-operations',
    routeId: 'career-guide-fintech-operations',
    path: '/career-guides/fintech-operations/',
    title: 'FinTech Operations Careers for Graduates | Centaur Careers',
    description: 'Learn what FinTech operations teams do, how commerce graduates can explore the field, and which workflows connect digital finance, payments, and compliance.',
    updatedAt: '2026-09-24',
    h1: 'FinTech Operations Careers for Graduates',
    breadcrumbLabel: 'FinTech Operations',
    primaryKeyword: getKeywordOwnership('/career-guides/fintech-operations/').primaryKeyword,
    secondaryKeywords: getKeywordOwnership('/career-guides/fintech-operations/').secondaryKeywords,
    body: [
      paragraph('FinTech combines financial services with technology-enabled products and processes. For a fintech career for BCom graduates, the useful first question is not “Which app is popular?” but “What financial workflow does this role operate, what controls apply, and what evidence or customer outcome must be handled?” The answer varies by employer and product.'),
      heading('What is FinTech operations?'),
      paragraph('What is fintech operations? It is a broad label for the work that keeps a technology-enabled financial product functioning: onboarding, transaction support, servicing, process controls, issue resolution, and coordination across product, technology, risk, compliance, and customer teams. The Reserve Bank of India describes FinTech as technology-driven innovation in financial services; the field and its boundaries continue to evolve.'),
      link('Read the RBI overview of FinTech', 'https://fintech.rbi.org.in/'),
      heading('Examples of FinTech operations work'),
      list([
        'Customer and merchant onboarding, record checks, and service requests.',
        'Digital-lending workflow support, document status, repayment servicing, and exception routing.',
        'Payment-status review, reconciliation, disputes, and customer communication.',
        'Operational risk, quality checks, audit trails, and process reporting.',
        'Product-operations coordination when a system change affects a customer or control process.',
      ]),
      paragraph('Fintech banking operations can sit inside banks, regulated entities, technology providers, or service partners. A neo banking meaning search usually refers to a digital-first banking experience; neo banking operations may therefore involve onboarding, service, payments, partner hand-offs, or controls. The legal entity and regulated responsibilities behind a product matter, so verify those details from authoritative sources rather than assuming every app is itself a bank.'),
      heading('A graduate’s preparation map'),
      paragraph('Fintech jobs for commerce graduates may value financial terminology, careful data handling, process thinking, communication, spreadsheet confidence, and comfort learning digital tools. Fintech jobs in India for freshers are not one uniform occupation: read each current vacancy for degree criteria, shift, location, product knowledge, and required experience.'),
      paragraph('When researching fintech operations jobs, search by the actual workflow—onboarding, servicing, digital lending, transaction support, or controls—in addition to the broad industry label.'),
      paragraph('A fintech analyst career can mean operations analysis, product analysis, business analysis, risk support, or data work. A fintech operations analyst often tracks queues, checks transaction or customer records, investigates exceptions, and reports process issues. These are role examples, not a claim that every employer uses the same title.'),
      heading('FinTech, payments, and compliance overlap'),
      paragraph('Fintech and digital payments overlap when a product supports transfers or payment acceptance, but FinTech is wider: lending, account services, wealth tools, insurance technology, and other financial workflows may also use technology. The National Payments Corporation of India’s UPI information explains the payment system’s participants and operating features; it is a useful primary reference for payment concepts.'),
      link('Read NPCI’s UPI FAQs', 'https://www.npci.org.in/what-we-do/upi/faqs'),
      paragraph('Fintech compliance jobs may involve controls, customer checks, policy implementation, issue escalation, or regulatory coordination. Fintech KYC AML jobs focus more specifically on onboarding due diligence, screening, monitoring, or case review. Exact responsibilities depend on the organisation and authorised process; this guide is educational, not legal or compliance advice.'),
      heading('How to prepare for a FinTech operations interview'),
      paragraph('For fintech operations interview questions, practise describing an end-to-end flow: what starts the request, what information is checked, which status changes matter, what could go wrong, how you would document an issue, and when you would escalate. Use a small mock reconciliation or process map to show structured thinking, but never use confidential customer data.'),
      faq('Can I build a fintech career after BBA?', 'A BBA graduate can explore relevant openings when the employer accepts that background and the candidate can show role-relevant skills. Compare actual job criteria rather than assuming one degree guarantees eligibility.'),
      faq('What should I know about a fintech career after MBA finance?', 'An MBA in Finance may be relevant to some product, analysis, risk, or operations roles, but requirements differ. Check whether a position expects experience, data skills, a particular product background, or an operational rather than strategic focus.'),
      faq('Is FinTech a separate course at Centaur Careers?', 'FinTech & Neo-Banking is a module within the Financial Operations Masterclass. Centaur Careers does not present it as a separate course or external certification.'),
      link('Explore the FinTech module', '/courses/fintech/', 'fintech-neo-banking'),
      link('Explore the Digital Payments module', '/courses/digital-payments/', 'digital-payments'),
      link('Review the complete Financial Operations Masterclass', '/courses/', 'courses'),
    ],
    relatedGuideIds: ['digital-payments-operations', 'finance-careers-after-graduation', 'finance-operations'],
    relatedRouteIds: ['courses', 'fintech-neo-banking', 'digital-payments', 'career-guide-digital-payments-operations', 'career-guide-finance-careers-after-graduation', 'career-guide-finance-operations', 'resources'],
  }),
  ...PRIORITY_CAREER_GUIDES,
]);

export const CAREER_GUIDE_HUB = Object.freeze({
  id: 'career-guides',
  path: '/career-guides/',
  title: 'Finance Operations Career Guides | Centaur Careers',
  description: 'Use this finance operations career guide collection to explore investment banking operations, KYC and AML, finance operations, retail banking, digital payments, trade lifecycle, and graduate pathways.',
  h1: 'Finance Operations Career Guides',
  breadcrumbLabel: 'Career Guides',
  updatedAt: '2026-09-30',
});

// One authoritative path per operations topic keeps the information cluster
// useful without creating a near-duplicate page for every keyword variation.
export const CAREER_GUIDE_TOPIC_MAP = Object.freeze([
  Object.freeze({ id: 'banking-operations', label: 'Banking operations', question: 'How do banking operations teams process and control financial-services work?', primaryPath: '/career-guides/investment-banking-operations/', primaryLabel: 'Read the investment banking operations guide', supportPath: '/career-guides/finance-operations/', supportLabel: 'Compare finance operations work' }),
  Object.freeze({ id: 'kyc-aml', label: 'KYC and AML', question: 'What do KYC, AML, screening, and case-review teams do?', primaryPath: '/career-guides/kyc-aml-analyst/', primaryLabel: 'Read the KYC and AML analyst guide', supportPath: '/courses/kyc-aml/', supportLabel: 'See the KYC and AML module' }),
  Object.freeze({ id: 'trade-operations', label: 'Trade operations', question: 'What happens from trade capture through confirmation, controls, and closure?', primaryPath: '/career-guides/trade-lifecycle/', primaryLabel: 'Follow the trade lifecycle', supportPath: '/career-guides/trade-support-analyst/', supportLabel: 'Explore trade support work' }),
  Object.freeze({ id: 'settlements', label: 'Settlements', question: 'What does a settlement analyst monitor and investigate?', primaryPath: '/career-guides/settlement-analyst/', primaryLabel: 'Read the settlement analyst guide', supportPath: '/blog/failed-settlement-reasons-resolution/', supportLabel: 'Study settlement-failure investigation' }),
  Object.freeze({ id: 'reconciliations', label: 'Reconciliations', question: 'How are cash, trade, position, and ledger breaks investigated?', primaryPath: '/resources/reconciliation-in-finance/', primaryLabel: 'Learn reconciliation in finance', supportPath: '/career-guides/reconciliation-analyst/', supportLabel: 'Explore reconciliation analyst work' }),
  Object.freeze({ id: 'corporate-actions', label: 'Corporate actions', question: 'How do issuer events affect entitlements, cash, positions, and records?', primaryPath: '/resources/corporate-actions-workflow/', primaryLabel: 'Read the corporate-actions workflow', supportPath: '/career-guides/investment-banking-operations/', supportLabel: 'See the operations context' }),
  Object.freeze({ id: 'securities-operations', label: 'Securities operations', question: 'Which records and controls support securities servicing and custody work?', primaryPath: '/career-guides/securities-operations/', primaryLabel: 'Explore securities operations', supportPath: '/resources/capital-market-operations/', supportLabel: 'Review capital-market operations' }),
  Object.freeze({ id: 'reference-data-management', label: 'Reference data management', question: 'Why do identifiers, instructions, calendars, and controlled static fields matter?', primaryPath: '/career-guides/trade-lifecycle/', primaryLabel: 'See reference data in lifecycle hand-offs', supportPath: '/career-guides/investment-banking-operations/', supportLabel: 'Read the operations control context' }),
  Object.freeze({ id: 'fund-accounting', label: 'Fund accounting', question: 'How do fund records, NAV inputs, cash, holdings, and controls connect?', primaryPath: '/career-guides/investment-banking-operations/', primaryLabel: 'Read the fund-accounting operations context', supportPath: '/blog/fund-accounting-nav-workflow-career-skills/', supportLabel: 'Explore fund accounting workflow' }),
  Object.freeze({ id: 'client-onboarding', label: 'Client onboarding', question: 'What information and control steps support a new client relationship?', primaryPath: '/career-guides/kyc-aml-analyst/', primaryLabel: 'Read the onboarding and KYC guide', supportPath: '/career-guides/retail-banking-operations/', supportLabel: 'Compare retail banking onboarding' }),
]);

export function getCareerGuide(id) {
  return CAREER_GUIDES.find((guide) => guide.id === id || guide.routeId === id) || null;
}
