// A crawlable, self-assessment question bank for the finance-career resource
// cluster. Questions are introductory and should not be treated as legal,
// regulatory, investment, or employer-specific operating instructions.

export const FINANCE_QUIZ_CATEGORIES = Object.freeze([
  'Investment Banking Operations',
  'Retail Banking Operations',
  'KYC and AML Compliance',
  'Digital Payments Operations',
  'Finance Operations and Credit',
  'FinTech and Neo-Banking',
]);

export const FINANCE_OPERATIONS_QUIZ = Object.freeze([
  Object.freeze({
    id: 'trade-capture',
    category: 'Investment Banking Operations',
    topic: 'Trade capture',
    question: 'What is the main purpose of trade capture in an investment banking operations workflow?',
    options: ['To record the agreed trade details in the relevant system', 'To market the investment to a new customer', 'To calculate an employee bonus', 'To replace the settlement instruction'],
    answer: 0,
    explanation: 'Trade capture records the economic and reference details of an executed transaction so downstream confirmation, clearing, settlement, and control activities have the right data.',
  }),
  Object.freeze({
    id: 'trade-confirmation',
    category: 'Investment Banking Operations',
    topic: 'Trade confirmation',
    question: 'Which activity best describes trade confirmation?',
    options: ['Checking that parties agree on the transaction details', 'Transferring cash and securities', 'Closing a customer bank account', 'Approving a marketing campaign'],
    answer: 0,
    explanation: 'Confirmation checks the agreed instrument, quantity, price, dates, counterparties, and other relevant details. Settlement is the later delivery or payment step.',
  }),
  Object.freeze({
    id: 'trade-affirmation',
    category: 'Investment Banking Operations',
    topic: 'Trade affirmation',
    question: 'Why does trade affirmation matter before settlement?',
    options: ['It validates that the trade data can move forward for processing', 'It guarantees that no market price will change', 'It replaces all reconciliation controls', 'It creates a new security'],
    answer: 0,
    explanation: 'Affirmation reduces uncertainty by confirming that the relevant parties agree on the transaction information used by later processing. Exact controls differ by market and organisation.',
  }),
  Object.freeze({
    id: 'clearing',
    category: 'Investment Banking Operations',
    topic: 'Clearing',
    question: 'In a simplified securities workflow, what does clearing generally help determine?',
    options: ['The obligations and amounts that need to be settled', 'The employee who will answer a customer call', 'The colour of a bank card', 'The tax return filing date for every investor'],
    answer: 0,
    explanation: 'Clearing helps establish obligations between parties and may involve netting, risk controls, or a central counterparty, depending on the product and market.',
  }),
  Object.freeze({
    id: 'settlement',
    category: 'Investment Banking Operations',
    topic: 'Trade settlement',
    question: 'What is trade settlement?',
    options: ['The completion of the agreed exchange of cash, securities, or other deliverables', 'The first sales conversation with a customer', 'The creation of an investment thesis', 'The deletion of a trade record'],
    answer: 0,
    explanation: 'Settlement is the completion stage where the required cash, securities, or contractual deliverables are exchanged according to the applicable market process.',
  }),
  Object.freeze({
    id: 'settlement-instructions',
    category: 'Investment Banking Operations',
    topic: 'Standing settlement instructions',
    question: 'Why are standing settlement instructions important?',
    options: ['They provide approved routing and account details for settlement', 'They predict the future price of a security', 'They replace customer due diligence', 'They are used only for office attendance'],
    answer: 0,
    explanation: 'Accurate settlement instructions help route cash or securities to the intended account. A change should follow the organisation\'s authentication and control process.',
  }),
  Object.freeze({
    id: 'settlement-fail',
    category: 'Investment Banking Operations',
    topic: 'Settlement failure',
    question: 'What is a sensible first step when investigating a settlement failure?',
    options: ['Identify the trade, expected date, status, and mismatched or missing element', 'Edit the record until it appears settled', 'Close the exception without evidence', 'Ignore it until the next reporting period'],
    answer: 0,
    explanation: 'Start with a precise definition of the failed item, then check instructions, availability, matching status, messages, cut-offs, and the documented escalation path.',
  }),
  Object.freeze({
    id: 'reconciliation',
    category: 'Investment Banking Operations',
    topic: 'Reconciliation',
    question: 'What does a reconciliation compare?',
    options: ['Two records that are expected to agree', 'Two unrelated marketing plans', 'Only a customer\'s identity documents', 'A bank\'s logo against a competitor\'s logo'],
    answer: 0,
    explanation: 'A reconciliation compares records such as an internal position or cash record with an external statement and makes differences visible for investigation.',
  }),
  Object.freeze({
    id: 'timing-break',
    category: 'Investment Banking Operations',
    topic: 'Timing differences',
    question: 'Which is a common possible cause of a reconciliation break?',
    options: ['A timing difference between two systems or statements', 'A correctly documented handover', 'An approved vacation request', 'A completed identity check'],
    answer: 0,
    explanation: 'Timing differences can make two valid records appear different temporarily. The analyst should still document the break, check dates and status, and follow the control procedure.',
  }),
  Object.freeze({
    id: 'exception-prioritisation',
    category: 'Investment Banking Operations',
    topic: 'Exception prioritisation',
    question: 'How should an operations analyst prioritise several exceptions?',
    options: ['Use deadlines, impact, ageing, dependencies, and the team escalation procedure', 'Always process the newest item first', 'Choose the easiest item and hide the rest', 'Wait for every exception to become overdue'],
    answer: 0,
    explanation: 'A controlled queue considers time sensitivity, financial or client impact, dependencies, ageing, and the documented escalation rules rather than convenience alone.',
  }),
  Object.freeze({
    id: 'corporate-actions',
    category: 'Investment Banking Operations',
    topic: 'Corporate actions',
    question: 'What is a corporate action?',
    options: ['An issuer event that can affect a security, entitlement, cash, or position', 'A routine employee performance review', 'A customer password reset', 'A daily office meeting'],
    answer: 0,
    explanation: 'Dividends, interest payments, splits, rights issues, and mergers are examples. Operations teams may capture event details, process elections, check entitlements, and reconcile outputs.',
  }),
  Object.freeze({
    id: 'dividend-entitlement',
    category: 'Investment Banking Operations',
    topic: 'Dividend entitlement',
    question: 'When reviewing a dividend event, which information is especially relevant?',
    options: ['The eligible position, key dates, rate, currency, and resulting entitlement', 'Only the customer\'s preferred communication colour', 'The office seating plan', 'An unrelated loan application'],
    answer: 0,
    explanation: 'Corporate-action processing depends on event terms, eligible positions, record or payment dates, currency, tax treatment where relevant, and the organisation\'s controls.',
  }),
  Object.freeze({
    id: 'stock-split',
    category: 'Investment Banking Operations',
    topic: 'Stock split',
    question: 'What can a stock split change in an operations record?',
    options: ['The number of units and the per-unit price basis, subject to the event terms', 'The customer\'s KYC risk rating automatically', 'The bank\'s telephone number', 'The legal owner of every security'],
    answer: 0,
    explanation: 'A split changes the unit relationship and can require position and price-basis updates. The event terms and approved processing rules determine the exact treatment.',
  }),
  Object.freeze({
    id: 'nav',
    category: 'Investment Banking Operations',
    topic: 'Fund accounting and NAV',
    question: 'What does NAV usually represent in a fund accounting context?',
    options: ['The value of a fund\'s net assets, often expressed per unit or share', 'The number of customer complaints received', 'A payment network reference number', 'A KYC document expiry date'],
    answer: 0,
    explanation: 'Net asset value is based on the fund\'s assets less liabilities, with the precise calculation, valuation, and publication process governed by the fund and applicable rules.',
  }),
  Object.freeze({
    id: 'retail-account-onboarding',
    category: 'Retail Banking Operations',
    topic: 'Customer onboarding',
    question: 'What is a core objective of retail banking account onboarding?',
    options: ['Collect and verify required customer information under the bank\'s process', 'Approve every application without checks', 'Skip identity information for faster service', 'Convert every customer into a borrower'],
    answer: 0,
    explanation: 'Onboarding involves collecting the required information, completing relevant checks, recording decisions, and communicating next steps under the institution\'s current process.',
  }),
  Object.freeze({
    id: 'branch-operations',
    category: 'Retail Banking Operations',
    topic: 'Branch operations',
    question: 'Which activity is commonly associated with branch operations?',
    options: ['Supporting account services, customer requests, records, and controlled transactions', 'Settling every global derivatives trade', 'Writing national monetary policy', 'Publishing a company\'s annual report'],
    answer: 0,
    explanation: 'Branch responsibilities vary, but can include account servicing, cash or transaction support, documentation, customer communication, and control checks.',
  }),
  Object.freeze({
    id: 'relationship-manager',
    category: 'Retail Banking Operations',
    topic: 'Relationship manager',
    question: 'What is a relationship manager generally responsible for?',
    options: ['Understanding customer needs and coordinating suitable banking products or service', 'Performing only system backups', 'Approving every transaction without controls', 'Maintaining the securities settlement ledger'],
    answer: 0,
    explanation: 'A relationship manager usually supports customer relationships, needs assessment, product conversations, and coordination. Exact duties differ by bank and role.',
  }),
  Object.freeze({
    id: 'loan-officer',
    category: 'Retail Banking Operations',
    topic: 'Loan officer',
    question: 'Which activity can form part of a loan officer\'s work?',
    options: ['Collecting application information and coordinating credit or documentation review', 'Changing a customer\'s statement without authority', 'Guaranteeing approval for every applicant', 'Ignoring repayment capacity'],
    answer: 0,
    explanation: 'Loan roles can involve application intake, document checks, customer communication, coordination with credit teams, and status updates. Approval remains subject to policy and review.',
  }),
  Object.freeze({
    id: 'nri-banking',
    category: 'Retail Banking Operations',
    topic: 'NRI banking',
    question: 'Why can NRI banking require specialised process knowledge?',
    options: ['Cross-border status, account rules, documentation, and applicable regulations can differ', 'NRI customers never need identity checks', 'All NRI accounts use the same product and tax treatment', 'NRI banking is unrelated to customer service'],
    answer: 0,
    explanation: 'NRI banking involves specific product, documentation, tax, exchange-control, and service considerations. Staff should follow current bank and regulatory guidance.',
  }),
  Object.freeze({
    id: 'service-request',
    category: 'Retail Banking Operations',
    topic: 'Customer service requests',
    question: 'What makes a customer service request operationally strong?',
    options: ['Clear ownership, accurate details, a tracked status, and documented closure', 'An informal promise with no record', 'Closing it before checking the request', 'Sending the customer between teams without a handover'],
    answer: 0,
    explanation: 'Good service operations create a traceable request, assign ownership, communicate realistic timelines, complete the required checks, and document the outcome.',
  }),
  Object.freeze({
    id: 'loan-processing',
    category: 'Retail Banking Operations',
    topic: 'Loan processing',
    question: 'Which sequence best reflects a simplified loan-processing workflow?',
    options: ['Application, document and eligibility checks, credit review, decision, and fulfilment', 'Disbursement first, then customer identification', 'Marketing only, with no records', 'Account closure, then application'],
    answer: 0,
    explanation: 'Actual lending workflows vary, but a controlled process normally checks the application and documents before decision and fulfilment steps.',
  }),
  Object.freeze({
    id: 'kyc',
    category: 'KYC and AML Compliance',
    topic: 'Know Your Customer',
    question: 'What does KYC mean in a banking and compliance context?',
    options: ['Know Your Customer: understanding and verifying the customer relationship', 'Keep Your Cash: a savings campaign', 'Key Yield Calculation: a trading formula', 'Know Your Coupon: a marketing code'],
    answer: 0,
    explanation: 'KYC is the process of collecting and reviewing information so an institution understands who it is dealing with and the nature of the relationship.',
  }),
  Object.freeze({
    id: 'customer-due-diligence',
    category: 'KYC and AML Compliance',
    topic: 'Customer due diligence',
    question: 'What is customer due diligence designed to support?',
    options: ['A risk-informed understanding of the customer and relationship', 'Automatic approval of every customer', 'A replacement for all transaction monitoring', 'A way to avoid keeping records'],
    answer: 0,
    explanation: 'CDD can involve identity, ownership, business activity, purpose, risk indicators, and ongoing review, depending on the institution and applicable requirements.',
  }),
  Object.freeze({
    id: 'enhanced-due-diligence',
    category: 'KYC and AML Compliance',
    topic: 'Enhanced due diligence',
    question: 'When might enhanced due diligence be relevant?',
    options: ['When higher risk or additional information needs a deeper review', 'When a file is already complete and no review is needed', 'Only for ordinary office purchases', 'Whenever a customer asks for faster service'],
    answer: 0,
    explanation: 'EDD is generally associated with higher-risk situations and additional investigation or approval. The trigger and required evidence come from current policy and rules.',
  }),
  Object.freeze({
    id: 'beneficial-owner',
    category: 'KYC and AML Compliance',
    topic: 'Beneficial ownership',
    question: 'Why is beneficial ownership important in an entity review?',
    options: ['It helps identify the natural person or persons who ultimately own or control an entity', 'It identifies only the company logo', 'It removes the need to understand the business', 'It applies only to personal savings accounts'],
    answer: 0,
    explanation: 'Understanding ownership and control helps an institution assess the relationship and risk. Definitions and thresholds depend on applicable rules and the organisation\'s procedure.',
  }),
  Object.freeze({
    id: 'pep',
    category: 'KYC and AML Compliance',
    topic: 'Politically exposed person screening',
    question: 'What is a PEP screening result?',
    options: ['A risk indicator that may require additional review under policy', 'Proof that a customer committed a crime', 'An automatic account closure instruction', 'A replacement for sanctions screening'],
    answer: 0,
    explanation: 'A PEP match is a risk factor, not proof of wrongdoing. The institution should investigate, document, and apply the current risk-based process.',
  }),
  Object.freeze({
    id: 'sanctions-screening',
    category: 'KYC and AML Compliance',
    topic: 'Sanctions screening',
    question: 'What should an analyst do with a possible sanctions-screening match?',
    options: ['Follow the approved investigation and escalation process before deciding the outcome', 'Treat every name similarity as confirmed', 'Ignore it if the customer is familiar', 'Delete the alert immediately'],
    answer: 0,
    explanation: 'A possible match needs controlled review of identifiers and the relevant list or policy. Analysts should document the disposition and escalate where required.',
  }),
  Object.freeze({
    id: 'transaction-monitoring',
    category: 'KYC and AML Compliance',
    topic: 'Transaction monitoring',
    question: 'What is transaction monitoring intended to help an institution do?',
    options: ['Identify activity that may require review under financial-crime controls', 'Guarantee that every transaction is legitimate', 'Replace customer onboarding checks', 'Forecast a customer\'s investment return'],
    answer: 0,
    explanation: 'Monitoring can surface activity for investigation. An alert is not a final conclusion; it needs analysis, evidence, documentation, and escalation under policy.',
  }),
  Object.freeze({
    id: 'suspicious-activity-reporting',
    category: 'KYC and AML Compliance',
    topic: 'Suspicious activity reporting',
    question: 'What is the safest description of a suspicious activity report process?',
    options: ['A controlled reporting and escalation process governed by applicable rules', 'A public social-media post about a customer', 'An informal message with no case record', 'A guarantee that an investigation will lead to prosecution'],
    answer: 0,
    explanation: 'Reporting requirements and terminology vary by jurisdiction. Analysts should follow the current legal and internal procedure, preserve confidentiality, and avoid making unsupported conclusions.',
  }),
  Object.freeze({
    id: 'case-notes',
    category: 'KYC and AML Compliance',
    topic: 'Case documentation',
    question: 'What makes KYC or AML case notes useful?',
    options: ['They state what was reviewed, which evidence was used, the reasoning, and the next action', 'They contain only a final yes or no', 'They copy unrelated customer information', 'They are written after the file is deleted'],
    answer: 0,
    explanation: 'Clear case notes create an audit trail and help another reviewer understand the facts, checks, reasoning, ownership, and escalation status.',
  }),
  Object.freeze({
    id: 'risk-based-approach',
    category: 'KYC and AML Compliance',
    topic: 'Risk-based approach',
    question: 'What does a risk-based approach mean in compliance operations?',
    options: ['Controls and review intensity are aligned to the assessed risk and current requirements', 'Every customer receives exactly the same review regardless of facts', 'High-risk alerts are ignored', 'The analyst chooses controls without policy'],
    answer: 0,
    explanation: 'A risk-based approach applies proportionate controls based on relevant facts and risk assessment while still following mandatory requirements and documented policy.',
  }),
  Object.freeze({
    id: 'aml-false-positive',
    category: 'KYC and AML Compliance',
    topic: 'False-positive review',
    question: 'What is a false positive in an AML alert workflow?',
    options: ['An alert that appears relevant but is resolved as unrelated after documented review', 'A confirmed criminal offence', 'A missing customer signature in every case', 'A payment that settled on time'],
    answer: 0,
    explanation: 'A false positive is a possible match or pattern that, after appropriate review, is not relevant to the risk being tested. The resolution still needs evidence and documentation.',
  }),
  Object.freeze({
    id: 'swift',
    category: 'Digital Payments Operations',
    topic: 'SWIFT messaging',
    question: 'What is SWIFT primarily known for in financial operations?',
    options: ['Providing standardised messaging used by financial institutions', 'Operating every bank branch in India', 'Guaranteeing that every payment is instant', 'Issuing all debit cards'],
    answer: 0,
    explanation: 'SWIFT provides a secure financial messaging network and standards. Messaging is not the same as moving or settling funds, which involves the relevant institutions and systems.',
  }),
  Object.freeze({
    id: 'rtgs',
    category: 'Digital Payments Operations',
    topic: 'RTGS',
    question: 'Which description best matches RTGS at a high level?',
    options: ['Real-time gross settlement, where transactions are processed individually in real time', 'A retail loyalty programme', 'A securities research report', 'A customer identity document'],
    answer: 0,
    explanation: 'RTGS stands for Real Time Gross Settlement. Consult the Reserve Bank of India and the relevant bank for current eligibility, timings, and operating details.',
  }),
  Object.freeze({
    id: 'neft',
    category: 'Digital Payments Operations',
    topic: 'NEFT',
    question: 'How is NEFT commonly distinguished from RTGS in introductory learning?',
    options: ['NEFT processes transactions in batches or cycles, while RTGS processes them individually in real time', 'NEFT is only for securities custody', 'NEFT never involves banks', 'NEFT is a customer identification framework'],
    answer: 0,
    explanation: 'This is a high-level distinction described in RBI educational material. Current operating windows, limits, and customer processes should be checked with RBI and the bank.',
  }),
  Object.freeze({
    id: 'upi',
    category: 'Digital Payments Operations',
    topic: 'UPI',
    question: 'What is UPI in the Indian payments ecosystem?',
    options: ['An instant payment system developed by NPCI', 'A securities exchange', 'A loan underwriting model', 'A customer due-diligence document'],
    answer: 0,
    explanation: 'NPCI describes UPI as an instant payment system. The customer journey, dispute handling, and bank or app responsibilities depend on the transaction and current operating rules.',
  }),
  Object.freeze({
    id: 'imps',
    category: 'Digital Payments Operations',
    topic: 'IMPS',
    question: 'What is the operational focus when supporting an IMPS transaction issue?',
    options: ['Trace the payment status, reference details, participants, and applicable exception process', 'Change the transaction amount without approval', 'Assume every failed attempt is a fraud case', 'Ignore the customer-facing status'],
    answer: 0,
    explanation: 'Payment support should establish what happened, use the relevant reference and status information, communicate clearly, and follow the bank or network procedure.',
  }),
  Object.freeze({
    id: 'payment-reference',
    category: 'Digital Payments Operations',
    topic: 'Payment reference numbers',
    question: 'Why is a payment reference number useful during investigation?',
    options: ['It helps locate and trace the relevant transaction across records', 'It proves that the customer caused the issue', 'It replaces all reconciliation work', 'It is only used for advertising'],
    answer: 0,
    explanation: 'A reference such as an RRN or other network identifier helps teams find the correct transaction and correlate messages, statuses, and exception records.',
  }),
  Object.freeze({
    id: 'payment-dispute',
    category: 'Digital Payments Operations',
    topic: 'Payment disputes',
    question: 'What is a disciplined first step in a payment dispute?',
    options: ['Capture the transaction details, customer claim, status, and evidence before routing the case', 'Refund every claim automatically', 'Delete the original transaction record', 'Ask the customer to contact an unrelated department'],
    answer: 0,
    explanation: 'Dispute handling starts with accurate intake and evidence. The final outcome depends on the payment type, participants, rules, and investigation procedure.',
  }),
  Object.freeze({
    id: 'wallet-reconciliation',
    category: 'Digital Payments Operations',
    topic: 'Wallet reconciliation',
    question: 'What could wallet reconciliation compare?',
    options: ['Wallet or ledger balances and transaction records across relevant systems', 'Only an employee attendance sheet', 'A customer\'s social-media posts', 'Two unrelated product brochures'],
    answer: 0,
    explanation: 'Wallet reconciliation checks whether internal ledger activity, provider records, settlement data, and balances agree, with breaks investigated and documented.',
  }),
  Object.freeze({
    id: 'payment-exception',
    category: 'Digital Payments Operations',
    topic: 'Payment exceptions',
    question: 'Which detail is most useful when handing over a payment exception?',
    options: ['Reference, current status, amount, timestamps, checks completed, owner, and next action', 'Only the customer\'s first name', 'A guess with no evidence', 'A screenshot with no transaction identifier'],
    answer: 0,
    explanation: 'A structured handover lets the next owner continue the investigation without repeating work and preserves a visible control trail.',
  }),
  Object.freeze({
    id: 'nbfc',
    category: 'Finance Operations and Credit',
    topic: 'NBFC operations',
    question: 'What does NBFC stand for?',
    options: ['Non-Banking Financial Company', 'National Banking Finance Counter', 'New Balance Funding Certificate', 'Network Branch Filing Centre'],
    answer: 0,
    explanation: 'An NBFC is a non-banking financial company. Its products, permissions, processes, and regulatory requirements depend on the applicable framework and institution.',
  }),
  Object.freeze({
    id: 'credit-analysis',
    category: 'Finance Operations and Credit',
    topic: 'Credit analysis',
    question: 'What is the purpose of credit analysis?',
    options: ['To assess repayment capacity, risk, and relevant evidence before a credit decision', 'To guarantee repayment by every borrower', 'To avoid reviewing income or obligations', 'To replace customer service'],
    answer: 0,
    explanation: 'Credit analysis considers financial information, repayment capacity, purpose, collateral or security where relevant, and risk under the lender\'s policy.',
  }),
  Object.freeze({
    id: 'five-cs',
    category: 'Finance Operations and Credit',
    topic: 'Five Cs of credit',
    question: 'Which set is commonly known as the Five Cs of credit?',
    options: ['Character, Capacity, Capital, Collateral, and Conditions', 'Customer, Currency, Coupon, Clearing, and Custody', 'Cash, Card, Code, Counterparty, and Coupon', 'Control, Compliance, Course, Career, and Certificate'],
    answer: 0,
    explanation: 'The Five Cs are a learning framework for discussing credit quality. Actual underwriting uses the lender\'s current policy, data, and applicable rules.',
  }),
  Object.freeze({
    id: 'risk-management',
    category: 'Finance Operations and Credit',
    topic: 'Risk management',
    question: 'What is a practical purpose of risk management in finance operations?',
    options: ['Identify, assess, control, monitor, and escalate risks that could affect objectives', 'Remove every possible risk from a business', 'Approve all transactions without review', 'Focus only on office equipment'],
    answer: 0,
    explanation: 'Risk management does not eliminate all uncertainty. It creates a structured way to identify exposures, apply controls, monitor changes, and escalate issues.',
  }),
  Object.freeze({
    id: 'emi',
    category: 'Finance Operations and Credit',
    topic: 'Loan repayment and EMI',
    question: 'What does EMI usually mean in a loan context?',
    options: ['Equated Monthly Instalment', 'External Market Indicator', 'Entity Matching Instruction', 'Electronic Merchant Identity'],
    answer: 0,
    explanation: 'EMI commonly means equated monthly instalment. The amount and repayment schedule depend on principal, interest, tenure, fees, and the applicable loan terms.',
  }),
  Object.freeze({
    id: 'finance-data-quality',
    category: 'Finance Operations and Credit',
    topic: 'Finance data quality',
    question: 'Which control best supports finance data quality?',
    options: ['Validate required fields, reconcile records, preserve evidence, and investigate exceptions', 'Allow untracked manual changes', 'Use a different customer identifier in every system', 'Delete records that do not match'],
    answer: 0,
    explanation: 'Data-quality controls make information complete, consistent, traceable, and fit for use. A mismatch should be investigated under the approved process, not hidden.',
  }),
  Object.freeze({
    id: 'digital-lending',
    category: 'FinTech and Neo-Banking',
    topic: 'Digital lending',
    question: 'What does digital lending operations commonly coordinate?',
    options: ['Digital application, identity and credit checks, decisioning, disbursement, and servicing workflows', 'Only social-media marketing', 'A securities exchange order book', 'A branch cash-counting process with no systems'],
    answer: 0,
    explanation: 'Digital lending connects customer experience, data, risk, compliance, decisioning, disbursement, repayment, and exception handling. Responsibilities vary by platform.',
  }),
  Object.freeze({
    id: 'fintech-product-operations',
    category: 'FinTech and Neo-Banking',
    topic: 'FinTech product operations',
    question: 'What is a useful product-operations responsibility in a FinTech team?',
    options: ['Coordinate process performance, incidents, controls, user impact, and cross-team resolution', 'Change production data without approval', 'Ignore customer-impacting incidents', 'Treat every release as a marketing activity only'],
    answer: 0,
    explanation: 'Product operations connects the product, support, risk, compliance, and technology teams so that workflows are monitored and issues are resolved with evidence.',
  }),
  Object.freeze({
    id: 'customer-success',
    category: 'FinTech and Neo-Banking',
    topic: 'Customer success',
    question: 'Which outcome is central to customer success in a FinTech context?',
    options: ['Helping customers use the service successfully while surfacing recurring issues and risks', 'Promising an outcome the product cannot provide', 'Closing tickets without checking resolution', 'Avoiding all customer feedback'],
    answer: 0,
    explanation: 'Customer success combines clear communication, issue resolution, product education, and useful feedback to improve the customer journey within the service boundaries.',
  }),
  Object.freeze({
    id: 'fintech-controls',
    category: 'FinTech and Neo-Banking',
    topic: 'FinTech compliance controls',
    question: 'Why do FinTech and neo-banking products need strong operational controls?',
    options: ['Digital scale can amplify data, payment, fraud, service, and compliance issues', 'Technology removes the need for controls', 'Controls make customer records unnecessary', 'Only traditional banks face operational risk'],
    answer: 0,
    explanation: 'Digital delivery changes the speed and scale of activity, but it does not remove the need for accurate records, access controls, monitoring, reconciliation, and escalation.',
  }),
]);

export const FINANCE_QUIZ_TOTAL = FINANCE_OPERATIONS_QUIZ.length;

if (FINANCE_QUIZ_TOTAL !== 50) {
  throw new Error(`Finance operations quiz must contain exactly 50 questions; found ${FINANCE_QUIZ_TOTAL}.`);
}
