import { BLOG_BLOCK_TYPES } from './blog/blogSchema.js';

const paragraph = (text) => ({ type: BLOG_BLOCK_TYPES.PARAGRAPH, text });
const heading = (text, level = 2) => ({ type: BLOG_BLOCK_TYPES.HEADING, level, text });
const list = (items, ordered = false) => ({ type: BLOG_BLOCK_TYPES.LIST, ordered, items });
const link = (label, href, routeId) => ({ type: BLOG_BLOCK_TYPES.LINK, label, href, routeId });

export const NEXT_CAREER_DEPTH_BLOCKS = Object.freeze({
  'risk-operations-analyst': [
    heading('How risk operations work is assessed'),
    paragraph('A risk operations team needs to know whether issues are visible, owned, moving toward resolution, and supported by evidence. Useful measures may include open and overdue actions, repeat incidents, control exceptions by process, remediation ageing, missing evidence, and time to assign an owner. Each measure needs a definition and a clear reporting period. A falling issue count is not automatically improvement if cases are being closed without verification or if reporting criteria have changed.'),
    list([
      'Separate an event, a control failure, an issue, a root cause, and a remediation action in the record.',
      'Show the source and date for every material status or indicator.',
      'Keep overdue work visible and record why a due date or owner changed.',
      'Report repeated causes alongside total counts so patterns are not hidden by averages.',
      'Confirm closure using the review evidence required by the approved process.',
    ]),
    heading('Build a risk case note from evidence'),
    paragraph('Use a fictional example such as a review that did not run on its expected day. A useful case note states the control and period in scope, what the evidence shows, which records were checked, what remains unknown, the immediate owner, the next deadline, and the authorised escalation route. It should not infer that a control failure caused a loss unless evidence supports that conclusion. A second reviewer should be able to follow the reasoning without asking the writer to reconstruct it from memory.'),
    heading('Questions to use in an interview or role review'),
    list([
      'Which risk or control processes would I support, and which team owns the policy?',
      'What evidence is required before an issue can be marked resolved?',
      'How are materiality, ageing, and escalation defined for this team?',
      'Which decisions can an analyst make independently and which require approval?',
      'How does the team identify recurring causes and track remediation quality?',
    ]),
    paragraph('When describing a practice case, explain the control objective, the observed gap, the facts still needed, and the next authorised action. This is stronger than using risk terminology without showing how the evidence changes what the team should do.'),
  ],
  'credit-analyst': [
    heading('A disciplined credit review: from statements to questions'),
    paragraph('Credit analysis begins with data quality. Confirm that periods, currencies, entity names, accounting bases, and source documents are comparable before interpreting a trend. Then connect reported earnings to cash generation, working-capital movements, debt obligations, liquidity, and the stated repayment source. Ratios can organise the review, but they do not replace context: a result may reflect seasonality, a one-off event, a changed accounting treatment, or a business risk that needs more evidence.'),
    list([
      'Reconcile key statement totals and note any restatement, missing period, or mismatch.',
      'Separate historical facts from management projections and analyst assumptions.',
      'Compare cash flow with reported profit and explain material working-capital changes.',
      'List existing obligations and identify the information needed to understand repayment capacity.',
      'Record both supporting and adverse evidence before preparing a recommendation for review.',
    ]),
    heading('A fictional borrower exercise'),
    paragraph('Use two invented years of statements for a small distributor. Sales rise, but receivables grow faster, inventory turns more slowly, and operating cash flow falls. Prepare a one-page note with the business context, data checks, calculations you can explain, positive factors, concerns, unanswered questions, and sensitivities that an authorised reviewer may want to examine. Do not select a lending threshold or declare an approval; those depend on the institution and the mandate of the role.'),
    heading('Presenting analysis clearly'),
    paragraph('An interview answer should walk from source to conclusion: identify the period and borrower, explain the measure, state the result, interpret it in context, and name what additional evidence would change the view. If a calculation uses an assumption, say so. If the source is incomplete, describe the limitation instead of presenting false precision. This approach applies to corporate, small-business, retail, and counterparty work even though their methods and documents differ.'),
    heading('Organise a concise credit assessment'),
    list([
      'Purpose and facility context: what is being assessed and for which period?',
      'Evidence reviewed: which statements, records, and supporting documents were available?',
      'Analysis: which calculations were checked and what business factors affect them?',
      'Key strengths, concerns, assumptions, and questions that remain unresolved.',
      'Recommendation or next step for the authorised decision-maker, within the role mandate.',
    ]),
    paragraph('A structured note lets a reviewer challenge an assumption or request more evidence without losing the analysis trail. Keep calculations reproducible and avoid hiding an adverse indicator in a long narrative.'),
    paragraph('When testing a sensitivity, change one stated assumption at a time and explain why that variable matters to repayment or business resilience. Keep the scenario separate from the base case, show the calculation, and identify which inputs still need verification. This makes the analysis easier to review and avoids presenting a hypothetical as a forecast.'),
    link('Review financial statement analysis fundamentals', '/resources/financial-statement-analysis/', 'resource-financial-statement-analysis'),
  ],
  'business-analyst-in-banking': [
    heading('From a banking problem to testable requirements'),
    paragraph('A banking business analyst helps stakeholders turn a service or control problem into an agreed change that can be built, tested, approved, and measured. Discovery should identify the customer or employee affected, the current process, the point of failure, the systems and records involved, relevant controls, and the desired outcome. Requirements should describe observable behaviour and avoid prescribing a solution before the constraints and dependencies are understood.'),
    list([
      'Map the current journey with actors, decisions, hand-offs, systems, records, and exception paths.',
      'Separate business rules, data needs, access controls, operational procedures, and technical constraints.',
      'Write acceptance criteria that a user or tester can verify with a clear input and expected result.',
      'Trace each requirement to its owner, rationale, test evidence, and downstream process impact.',
      'Record open decisions and assumptions instead of silently treating them as agreed scope.',
    ]),
    heading('Worked example: a customer detail request'),
    paragraph('For a fictional address-change journey, map how a request arrives, how identity and evidence are checked, which records need an update, what happens if a document is missing, and how the customer is told the request is complete. A useful analyst output includes the current and proposed flow, field-level data rules, access or approval questions, negative test cases, and operational reporting needs. The analyst documents and coordinates requirements; approval of policy exceptions remains with the designated owner.'),
    heading('How to build a small portfolio example'),
    list([
      'State the problem and who experiences it without using real customer information.',
      'Show a simple process map and a short list of agreed requirements.',
      'Include normal, incomplete, duplicate, and exception test cases.',
      'Explain dependencies, unresolved questions, and how completion would be measured.',
      'Describe what changed after stakeholder feedback and why.',
    ], true),
    paragraph('This evidence helps distinguish banking business analysis from an operations role that primarily processes a queue. Some vacancies combine both; compare deliverables and decision rights in the job description.'),
    heading('Stakeholder alignment and change readiness'),
    paragraph('Requirements can conflict when a customer journey, operational team, risk owner, and technology team optimise for different outcomes. Record the decision owner, rationale, constraint, and impact rather than silently resolving the conflict yourself. Before a change goes live, confirm that test evidence covers normal and exception paths, that procedures and training have an owner, and that operational reporting can detect an unintended result. These checks help show that a business analyst understands implementation, not only documentation.'),
  ],
  'custody-operations': [
    heading('Custody operations connects positions, cash, and asset servicing'),
    paragraph('Custody operations supports the records and services associated with assets held through a custody arrangement. Depending on the team, work can touch settlement instructions, cash and position records, income, corporate actions, tax data, transfers, client reporting, and reconciliations. The same asset may appear in a trade system, custodian statement, depository record, fund accounting system, and client view. The analyst must know which source is authoritative for each field under the procedure.'),
    list([
      'Check account and security identifiers before comparing quantity, currency, and date.',
      'Distinguish a settled position from a pending trade, a movement, or an event-related adjustment.',
      'Track income and corporate-action items from source notice to expected and received outcome.',
      'Investigate cash or position breaks using the relevant statements and transaction history.',
      'Protect client data and route instruction or standing-data changes through required approvals.',
    ]),
    heading('Practice a custody position break'),
    paragraph('Create an invented case in which an internal record shows 250 units and an external statement shows 245. Before proposing a correction, check the account, instrument identifier, statement date, pending settlements, transfers, corporate actions, and any approved rounding or timing rules. Write the difference, source records, checks completed, unresolved question, owner, and closure evidence. The correct next action may be to wait for a pending event, correct a mapping, or escalate; it should follow the evidence and authorised workflow.'),
    heading('What strong custody work looks like'),
    paragraph('Strong work keeps cash, holdings, instructions, events, and client reporting aligned while preserving a clear audit trail. Teams may monitor unreconciled positions, aged cash items, late instructions, event breaks, repeat data issues, and service deadlines. Ask how the employer defines those measures and what the analyst can change. Custody is an operations and record-keeping context; it does not itself imply investment selection or trading authority.'),
    heading('A custody role research checklist'),
    list([
      'Does the team support institutional clients, funds, asset managers, or another defined group?',
      'Which products, markets, currencies, and service windows are in scope?',
      'How are settlement, income, events, transfers, and reconciliation responsibilities divided?',
      'Which actions require client instruction, maker-checker review, or specialist approval?',
      'How does the team evidence that a position or cash break is resolved?',
    ]),
    paragraph('A useful learning portfolio can show one fictional position reconciliation and one event timeline. Include the records compared, the field that differed, the evidence reviewed, the questions sent to an owner, and the verification that would close the item. Explain how cash and holdings are related but remain separate records. This gives a reviewer a concrete view of your process reasoning without suggesting that you have handled a real custody account.'),
    link('Understand the corporate actions workflow', '/resources/corporate-actions-workflow/', 'resource-corporate-actions-workflow'),
    paragraph('A useful learning portfolio can show one fictional position reconciliation and one event timeline. Include the records compared, the field that differed, the evidence reviewed, the questions sent to an owner, and the verification that would close the item. Explain how cash and holdings are related but remain separate records. This demonstrates process reasoning without suggesting experience with a real custody account.'),
  ],
  'credit-operations-analyst': [
    heading('Credit operations across the facility lifecycle'),
    paragraph('Credit operations often continues after a credit decision has been made. The team may coordinate required documents, conditions, account setup, booking, disbursement checks, covenant or expiry tracking, servicing requests, renewals, and closure records. The precise split between the relationship team, underwriting, legal, operations, servicing, and control functions differs by organisation. A processing analyst should follow the recorded decision and conditions rather than infer approval from an incomplete file.'),
    list([
      'Match the applicant, facility, amount, purpose, terms, and approval reference across the file.',
      'Track each condition as received, checked, pending, waived by an authorised person, or escalated.',
      'Validate required documents and data against the current checklist and source record.',
      'Use maker-checker or release controls required for account setup and disbursement.',
      'Keep renewal, expiry, repayment, servicing, and exception dates visible to responsible owners.',
    ]),
    heading('A safe loan-file simulation'),
    paragraph('Prepare an invented application pack with a decision reference, a facility summary, several required documents, and one missing item. Build a tracker that shows the requirement, source, reviewer, status, due date, and next action. Add a second case where a document is present but its entity name does not match the application. Explain why the item needs resolution and who can decide whether an exception is acceptable. Do not store real identity documents in a learning portfolio.'),
    heading('Measures and role boundaries'),
    paragraph('A team may monitor file completeness, processing turnaround, rework, aged conditions, booking accuracy, and post-disbursement exceptions. A fast turnaround is useful only if required checks and approvals are complete. Credit operations is distinct from credit analysis and sanctioning, although some employers combine activities. Ask which records the team owns and which decisions remain with an approver, relationship manager, legal team, or policy owner.'),
    heading('Keep a facility tracker useful to the next owner'),
    paragraph('A practical tracker should make the facility, condition, source document, current status, owner, due date, reviewer, and next action easy to find. Define statuses so that received, under review, accepted, waived by an authorised person, and unresolved do not collapse into a single green tick. When ownership changes, the history should explain what was checked and what the next person must do. This is a simple way to demonstrate control awareness in a fictional portfolio exercise.'),
    heading('Follow-up should be specific and traceable'),
    paragraph('When a required item is missing, state the document or field needed, the facility or condition it relates to, the responsible contact, the due date, and how receipt will be checked. Avoid broad messages such as "documents pending" that leave the next owner guessing. If an item conflicts with the approval or current record, pause the affected step and route the discrepancy to the authorised decision-maker rather than changing the file to make it appear complete.'),
    link('Compare credit operations with credit analysis', '/career-guides/credit-analyst/', 'career-guide-credit-analyst'),
    paragraph('When a required item is missing, state the document or field needed, the facility or condition it relates to, the responsible contact, the due date, and how receipt will be checked. If an item conflicts with the approval or current record, pause the affected step and route the discrepancy to the authorised decision-maker rather than changing the file to make it appear complete.'),
  ],
  'transaction-monitoring-analyst': [
    heading('Reviewing an alert without jumping to a conclusion'),
    paragraph('Transaction monitoring work starts with an alert generated under an institution\'s approved monitoring framework. An alert is a prompt for review, not proof of misconduct. The analyst checks the case scope, customer or entity context available to the role, activity history, relevant source records, and applicable internal procedure. The goal is a clear and reproducible disposition for the authorised reviewer, with uncertainty and missing information made explicit.'),
    list([
      'Confirm the case identifier, alert period, data completeness, and reason the alert was generated.',
      'Compare observed activity with the available customer or relationship context without assuming intent.',
      'Check relevant records and note source, date, identifiers, and limitations.',
      'Separate facts, reasonable questions, hypotheses, and conclusions in the case narrative.',
      'Escalate under the internal process when the case meets review criteria or remains unresolved.',
      'Maintain confidentiality and do not disclose restricted case information to unauthorised parties.',
    ]),
    heading('Case narrative structure for practice'),
    paragraph('A fictional training note can use five parts: why the alert was created, what was reviewed, what the records show, what remains unclear, and the next action or reviewer decision. Avoid labels such as suspicious, innocent, or confirmed unless the evidence and authorised process support them. Do not include real customer data, create a real-world threshold, or treat an illustrative pattern as a universal rule.'),
    heading('Quality signals and role questions'),
    paragraph('Quality review may consider completeness, consistency, source attribution, timeliness, rationale, and whether escalation followed procedure. Ask what products and alert types the team handles, how training and quality feedback work, what decisions sit with investigators or compliance officers, and how confidentiality is maintained. Requirements and reporting obligations are jurisdiction- and institution-specific; current official rules and the employer\'s approved procedure govern live work.'),
    heading('Common review mistakes to avoid in practice'),
    list([
      'Treating an alert score or system label as a conclusion rather than a review prompt.',
      'Copying customer context without checking whether it applies to the alert period.',
      'Writing a conclusion without naming the source records or missing data.',
      'Using ambiguous language that hides whether something was observed or inferred.',
      'Sharing case details outside approved channels or with an unauthorised audience.',
    ]),
    paragraph('If a reviewer asks for more information, update the note with the new source and date, the additional check, and whether the earlier interpretation changed. Preserve the original audit trail according to the approved case system; do not overwrite a prior review in a way that hides what was known at the time.'),
    link('Read the KYC and AML framework guide', '/resources/kyc-aml-compliance-guide/', 'resource-kyc-aml-compliance-guide'),
  ],
  'middle-office-operations': [
    heading('Middle office sits between transaction activity and control'),
    paragraph('The label middle office can describe different teams across firms. It may include trade support, transaction validation, position or exposure checks, limit monitoring, confirmations, reconciliations, management information, or coordination between front-office activity and downstream processing. Some organisations place a task in another function. The useful way to assess a vacancy is to identify the transaction, record, control, hand-off, and output the role actually owns.'),
    list([
      'Check trade capture fields against approved source records and document material differences.',
      'Monitor confirmation, matching, limit, or exception statuses only within the team\'s assigned scope.',
      'Route booking changes and approvals through the designated control path.',
      'Coordinate unresolved items with the desk, settlements, risk, technology, or counterparties as appropriate.',
      'Confirm the downstream record after a correction or authorised update.',
    ]),
    heading('A trade-support practice case'),
    paragraph('Use fictional trade records that differ on one field, such as settlement date or account. Identify which source governs the field, what downstream teams could be affected, whether a cut-off is approaching, and what evidence is needed before any change. Draft a short update that states the identifier, expected value, observed value, source checked, impact, owner, and next checkpoint. This shows operational judgement without claiming authority to amend a live transaction.'),
    heading('Choosing between middle office and adjacent roles'),
    paragraph('Front-office jobs may focus on client, investment, or transaction decisions; middle-office roles commonly support validation, monitoring, coordination, and control; back-office roles commonly support settlement, custody, records, servicing, and reconciliation. These are broad patterns rather than universal organisational definitions. Ask about the product, shift, team structure, decision rights, systems, and performance measures before comparing titles.'),
    heading('What to learn during the first weeks in a team'),
    paragraph('A new analyst should understand the team\'s product glossary, authoritative records, control calendar, status codes, escalation contacts, service deadlines, and access rules. Shadowing a complete case is often more informative than memorising a system menu: follow the item from receipt through review, hand-off, final status, and reporting. Ask which exceptions are common, what a high-quality case note looks like, and how a new joiner receives feedback.'),
    list([
      'Learn one routine case and explain what makes it complete.',
      'Review a closed exception and trace its evidence and approval history.',
      'Practise the team\'s escalation format using a fictional scenario.',
      'Confirm which metrics the team owns and how each one is defined.',
      'Ask for feedback on accuracy and hand-offs before trying to optimise speed.',
    ], true),
    list(['Learn one routine case and explain what makes it complete.', 'Review a closed exception and trace its evidence and approval history.', 'Practise the team\'s escalation format using a fictional scenario.', 'Confirm which metrics the team owns and how each one is defined.', 'Ask for feedback on accuracy and hand-offs before trying to optimise speed.'], true),
    link('Explore back-office banking job families', '/career-guides/back-office-banking-jobs/', 'career-guide-back-office-banking-jobs'),
  ],
  'back-office-banking-jobs': [
    heading('Back-office banking work is a set of process families'),
    paragraph('Back-office roles can support customer and account maintenance, payment processing, lending records, reconciliations, card operations, document management, settlements, custody, reporting, and control evidence. The term describes where a function may sit in an organisation, not a fixed list of low-skill tasks. A process can be routine and still require product knowledge, accuracy, confidentiality, prioritisation, and sound escalation.'),
    list([
      'Separate transaction processing from exception investigation and approval.',
      'Check customer, account, product, amount, date, status, and supporting evidence as required.',
      'Track queue volume and ageing while prioritising customer impact and deadline risk.',
      'Maintain a complete record of hand-offs, corrections, approvals, and closure.',
      'Look for repeat defects that may indicate a data, training, system, or upstream-process cause.',
    ]),
    heading('Turn a job description into a preparation plan'),
    paragraph('Highlight every action verb in a vacancy, then group the responsibilities into processing, checking, customer communication, exception handling, reporting, and improvement. For each group, write one fictional example you can explain. If a role mentions reconciliation, prepare a small matching exercise; if it mentions onboarding, practise checking completeness and recording a missing item; if it mentions payments, map the status path and escalation points. Do not claim familiarity with a bank\'s private system unless you have actually used it.'),
    heading('Compare roles by the workday, not only the title'),
    paragraph('Ask how the queue is allocated, what a normal day includes, which shifts or cut-offs apply, what quality checks are used, how training is delivered, and what evidence supports progression. Common measures include accuracy, rework, ageing, throughput, service levels, and control completion, but definitions vary. Current job postings and employer conversations provide a more reliable picture than a generic salary or placement claim.'),
    heading('A simple way to demonstrate readiness'),
    paragraph('Choose one process named in a vacancy and create a one-page map with the trigger, required inputs, validation, routine route, exception route, owner, output, and closure evidence. Add a fictional case with one missing field and write the next action. In an interview, explain the assumptions and what you would confirm before acting. This shows practical thinking without claiming experience with the employer\'s confidential data or internal software.'),
    heading('Keep volume and quality measures in context'),
    paragraph('Throughput and turnaround can help describe a queue, but they need quality measures beside them. Compare completed volume with error rates, rework, ageing, customer impact, and control completion. Check whether a metric excludes reopened cases or counts a hand-off as completion. When definitions are stable, the measures help a candidate discuss how an operations process performs without making unsupported claims about a bank\'s actual results.'),
    link('Compare banking and finance career directions', '/compare/banking-vs-finance-careers/', 'comparison-banking-vs-finance-careers'),
    paragraph('Throughput and turnaround need quality measures beside them. Compare completed volume with errors, rework, ageing, customer impact, and control completion. Check whether a metric excludes reopened cases or counts a hand-off as completion. Stable definitions let a candidate discuss how a process performs without making unsupported claims about a bank\'s actual results.'),
  ],
  'settlement-analyst': [
    heading('Settlement processing: validate, instruct, monitor, reconcile'),
    paragraph('Settlement operations coordinates the exchange of cash and securities or other contractual obligations after a transaction. An analyst may validate transaction details, check standing instructions, monitor matching and settlement status, track market or internal cut-offs, investigate failures, and verify resulting cash or position records. Instruments and market infrastructure differ, so settlement dates, procedures, and responsibilities should always be confirmed from current authoritative information.'),
    list([
      'Confirm trade identifiers, parties, accounts, instrument, quantity, currency, and relevant dates.',
      'Check that the instruction uses approved standing data and required approval.',
      'Monitor acknowledgement, matching, clearing, settlement, and post-settlement status.',
      'For a fail or mismatch, identify the first field or hand-off that differs and assign an owner.',
      'Verify the final cash or position outcome and retain the closure evidence.',
    ]),
    heading('A settlement fail investigation exercise'),
    paragraph('Create an invented transaction with a missing acknowledgement before a fictional cut-off. Record the expected status, latest observed status, source and timestamp, parties already contacted, potential downstream effect, escalation point, and next review time. Then write a concise update that another shift could continue. The exercise should not assume that a particular market uses a universal settlement cycle or that an analyst may resend or amend an instruction without approval.'),
    heading('Useful questions for settlement vacancies'),
    list([
      'Which asset classes, markets, counterparties, and time zones does the team cover?',
      'How are market cut-offs and late or failed settlements escalated?',
      'Which system or external record is authoritative for instruction status?',
      'What is the division of responsibility between trade support, settlements, custody, and reconciliation?',
      'How are recurring fails reviewed and process improvements approved?',
    ]),
    heading('Classify a settlement exception before escalating'),
    paragraph('A settlement item can remain pending because of a missing instruction, unmatched economics, insufficient or unavailable records, a counterparty response, a standing-data issue, a market deadline, or a downstream status delay. These are investigation categories, not definitive root causes. Record the last confirmed status and the source timestamp, then test the next plausible hand-off. Avoid describing a case as a market fail or system incident until the evidence and approved definitions support that classification.'),
    paragraph('Teams may review settlement completion, fail volume, ageing, late instructions, recurring causes, and the time between identifying an exception and assigning an owner. A single rate does not explain why an item failed or whether the right control operated. State the period and denominator, distinguish causes only when evidence supports it, and explain how the team verifies closure.'),
    link('Study capital market operations end to end', '/resources/capital-market-operations/', 'resource-capital-market-operations'),
  ],
  'finance-learning-roadmap': [
    heading('A staged finance learning roadmap for graduates'),
    paragraph('A useful roadmap narrows the field over time. Start with shared foundations, sample several role families, then deepen the skills for one target. The sequence below is a self-directed framework; it is not a claim about the duration or guaranteed outcomes of any course or hiring process.'),
    list([
      'Foundation: review accounting entries, financial statements, spreadsheet accuracy, business writing, and basic banking products.',
      'Orientation: map retail banking, payments, lending, investment operations, compliance, finance operations, and FinTech workflows.',
      'Role choice: compare current vacancies and choose one or two families by tasks, eligibility, location, schedule, and required evidence.',
      'Practice: build two fictional work samples such as a reconciliation, case note, process map, or financial statement review.',
      'Application: tailor a resume to evidence you can explain, prepare role-specific examples, and track feedback and skill gaps.',
    ], true),
    heading('A weekly practice rhythm'),
    paragraph('Each study session can combine one concept, one worked example, and one explanation in your own words. For example, learn what a reconciliation compares, work through invented records, and write a short note about an unresolved difference. The next session can focus on a related hand-off or control. Keep a learning log with the source, exercise, mistake found, correction, and question to research. Revisit the exercise after a few days to see whether you can explain the logic without copying notes.'),
    heading('How to know when to specialise'),
    paragraph('Specialise when several current vacancies repeat the same responsibilities and your practice exposes a clear skill gap. A learner interested in transactions may explore settlement and custody; someone drawn to customer and document workflows may explore credit operations or KYC; a learner who prefers statements and assumptions may research credit or financial analysis. These paths overlap in foundational skills but require different depth. The existing Financial Operations Masterclass covers its published topics; this roadmap does not add new course modules or external qualifications.'),
    list(['Can I explain the workflow from trigger to verified output?', 'Can I show a fictional example with sources, checks, exceptions, and limits?', 'Can I connect my evidence to a real vacancy requirement?', 'Can I identify which decision belongs to an authorised specialist?']),
    heading('Keep your learning portfolio honest and useful'),
    paragraph('For each practice item, save the prompt, invented data, assumptions, working, final explanation, and one improvement you would make. Add the date and any public source used. Do not include customer records, employer screenshots, confidential templates, or copied answer keys. A small set of well-explained examples is easier to discuss in an interview than a folder of unrelated certificates.'),
  ],
  'operations-analyst-banking': [
    heading('Banking operations analysts improve flow and control together'),
    paragraph('An operations analyst may process a queue while also examining why items become delayed, incomplete, duplicated, or misrouted. Improvement work begins by defining the process and baseline: what enters, what counts as complete, how the team handles exceptions, and which outcome matters to the customer or control owner. A proposed efficiency change should preserve required approvals, evidence, privacy, and escalation.'),
    list([
      'Measure incoming volume, completed work, backlog, ageing, rework, and unresolved exceptions consistently.',
      'Segment results by product, channel, exception type, or hand-off when the data is reliable.',
      'Confirm that a reduction in cycle time did not increase errors or bypass a required check.',
      'Trace a repeat defect to its earliest supported cause rather than treating the final symptom.',
      'Document the change, owner, approval, test, and post-change review under the organisation\'s process.',
    ]),
    heading('A process improvement portfolio case'),
    paragraph('Build a fictional request queue with routine, incomplete, duplicate, and urgent items. Define the starting measures and a simple process map. Identify one bottleneck, propose a change such as a clearer required-field prompt or an ownership rule, then specify what must be reviewed before the change is adopted. Compare before-and-after results for both speed and quality. Label all data as invented and avoid claiming production savings from a classroom exercise.'),
    heading('How this role differs from a business analyst'),
    paragraph('A banking operations analyst usually supports an ongoing service or process and may report performance, investigate exceptions, or recommend improvements. A business analyst more often elicits and documents requirements for a change, coordinates stakeholders, and supports acceptance testing. The boundary varies: some vacancies blend process ownership and change delivery. Look for the deliverables, stakeholders, and approval responsibilities in each job description.'),
    heading('Describe an operational issue in a structured update'),
    paragraph('A concise update can state the affected process and period, the expected result, what the records show, the checks completed, the customer or control impact known so far, the owner, and the next checkpoint. Separate confirmed information from an estimate. If you are proposing a process change, explain the evidence for the root cause and the control that must remain effective. This makes communication actionable for service teams, technology, risk, and managers.'),
    link('Compare banking and business analysis career tasks', '/career-guides/business-analyst-in-banking/', 'career-guide-business-analyst-in-banking'),
    paragraph('A useful proposal states the problem, evidence, affected users or records, likely cause, suggested change, control impact, owner, test plan, and measure for review. Confirm who approves the change and what would trigger further investigation. An improvement should not move an error to another team or hide unresolved work just to improve one local metric.'),
  ],
});

export const NEXT_RESOURCE_DEPTH_BLOCKS = Object.freeze({
  'corporate-actions-workflow': [
    heading('Corporate action data: fields to reconcile'),
    paragraph('An event record is only useful when the security, event, dates, terms, eligible account, and processing status refer to the same case. Operations teams commonly compare an issuer or agent notice with market or custodian data and internal position records. A source change should be versioned so a reviewer can tell which terms were used when an instruction or entitlement was prepared. Rates and estimated proceeds should remain distinguishable from confirmed outcomes.'),
    list([
      'Security and event identifiers, event type, option, currency, and source version.',
      'Announcement, ex, record, election, response, effective, and payment dates as relevant to that event.',
      'Eligible quantity, pending activity, account mapping, and the basis used for the position.',
      'Election status, authorised instruction, acknowledgement, and deadline ownership.',
      'Expected versus received cash or securities, fees or tax records, and final reconciliation status.',
    ]),
    heading('Common event-processing breaks'),
    paragraph('A date can be correct in one feed but wrong for the task being performed; a position can change because a trade is pending; a voluntary election can be missing or duplicated; or a cash receipt can differ from an estimate because final event terms changed. Investigate the source and event version first, then the position basis and instruction history. Do not force a match by overwriting an unexplained difference.'),
    heading('Keep the event timeline operationally clear'),
    paragraph('Separate the external deadline from any earlier internal review deadline. A team may need time to validate the event, confirm eligible positions, obtain an authorised client or fund instruction, send it through the approved channel, and verify acknowledgement. Record the time zone and source for each deadline where relevant. If a source changes the terms, preserve the prior version and document who assessed the impact on accounts and instructions already in progress.'),
    heading('End-to-end practice case'),
    paragraph('For a fictional rights event, create an event notice with two options, an invented account position, an internal election deadline, and a later external cut-off. Draw the checks needed before an instruction is sent, identify who approves the choice, and show how an acknowledgement and resulting position would be reconciled. Mark all dates and rates as illustrative. Compare your process map with current official investor-education material and the relevant institution\'s procedure before applying it to a real event.'),
    heading('Event closure is more than posting the final amount'),
    paragraph('Close an event only after the expected option or entitlement has been compared with the supported position, the actual cash or security movement has been checked, required fees or tax records are handled under policy, and unresolved items have an owner. Preserve the source notice and approvals used. If an estimated value changes after an amended notice, record the difference and review affected instructions instead of silently replacing the original estimate.'),
    link('Check SEBI Investor material on corporate actions', 'https://investor.sebi.gov.in/iematerial.html'),
  ],
  'capital-market-operations': [
    heading('The post-trade chain and its records'),
    paragraph('A capital-market transaction creates records across participants that may include an order, execution, confirmation, clearing obligation, settlement instruction, cash movement, security position, custody statement, accounting entry, and client report. Each record answers a different question. A trade capture can show agreed economics while a settlement record shows whether delivery completed; a custody record can show a position after processing. Reconciliation compares the relevant records rather than assuming they are interchangeable.'),
    list([
      'Primary issuance records describe the offer, application or allocation, funds, and security creation or credit.',
      'Secondary-market records follow order, execution, confirmation, clearing, settlement, and resulting holdings.',
      'Custody and asset-servicing records support safekeeping, transfers, income, corporate actions, and reporting.',
      'Fund and finance records may connect trades and holdings to valuation, cash, accounting, and investor reporting.',
      'Exception records explain mismatches, failed instructions, late data, ownership, and resolution evidence.',
    ]),
    heading('Why the same transaction can show different statuses'),
    paragraph('One team may have accepted an instruction while another is still awaiting a match; a settlement may be pending even though the trade is confirmed; and an accounting record may update on a different schedule from a custody feed. Status names and timing depend on the market and system. Compare timestamps, identifiers, status definitions, and the authoritative source before describing an item as failed or complete.'),
    heading('Map ownership at each hand-off'),
    paragraph('For each stage, name who creates the record, who validates it, who can approve an exception, and who receives the next hand-off. A broker, clearing participant, depository, custodian, bank, fund administrator, and asset manager may each see a different part of the process. The map should also identify what evidence crosses the boundary and how a delayed acknowledgement is escalated. This makes the lifecycle useful for role research and helps explain why a single team cannot resolve every break alone.'),
    heading('Build a lifecycle map for study or interview prep'),
    list([
      'Choose one fictional instrument and identify the parties involved at each stage.',
      'Write the key record produced at each hand-off and which team uses it next.',
      'Add a mismatch at confirmation and a separate break after settlement.',
      'Show the evidence, owner, deadline, and verification needed to close each case.',
      'Mark which rules require current official market or institutional confirmation.',
    ], true),
    heading('What to include in a market-operations study note'),
    paragraph('For each participant, list its role in the particular transaction, the record it creates or receives, and the next party that relies on it. Add one normal hand-off and one exception. This avoids broad claims that every broker, bank, custodian, or infrastructure provider performs the same function for every instrument. Use official market and regulator material to check the terms, and date your notes so you know when a source should be reviewed again.'),
    link('Read SEBI Investor securities-market learning material', 'https://investor.sebi.gov.in/securities-stockmarket.html'),
    link('Review RBI payment and settlement system information', 'https://m.rbi.org.in/scripts/paymentsystems.aspx'),
  ],
  'financial-system-india': [
    heading('A practical map of India\'s financial-system layers'),
    paragraph('A useful study model separates six layers: users and economic needs; products and contracts; institutions that provide or intermediate services; markets where claims are issued or traded; infrastructure that routes, clears, settles, records, or safeguards activity; and public authorities with mandates set by law. These layers interact, but an institution, a market, and a regulator are not the same thing. Mapping them separately helps explain who holds a record, who moves value, and who oversees a specific activity.'),
    list([
      'Banking and payments connect deposits, credit, customer accounts, and payment instructions.',
      'Securities markets connect issuers, investors, intermediaries, exchanges, clearing, depositories, and custody.',
      'Insurance and pension arrangements pool or manage risks and long-term savings under their relevant frameworks.',
      'Money, debt, equity, derivatives, funds, foreign exchange, and other products create distinct records and risks.',
      'Technology, reporting, grievance, audit, and supervisory processes provide additional connections and checks.',
    ]),
    heading('Trace a financial journey instead of memorising labels'),
    paragraph('Take a fictional household that receives salary into a bank account, pays a bill, buys a mutual-fund unit through an authorised route, and later submits an insurance claim. Draw a separate journey for each action. Identify the customer instruction, provider, key record, payment or asset movement, service hand-off, and place to verify current consumer information. The journeys may touch different institutions and authorities; do not assume one regulator or company owns every step.'),
    heading('How to research a regulator or institution accurately'),
    paragraph('Start with the activity in question, then use the responsible authority\'s current website, legislation, directions, investor material, or official registry. Check the document date and whether it has been amended. A regulator\'s broad mandate is not the same as a current operating rule for a product, entity, or transaction. For career research, this distinction is also useful: an operations employee follows the applicable procedure, while policy interpretation and formal supervisory decisions belong to authorised roles.'),
    heading('Use a flow map to compare products'),
    paragraph('For each journey, note the customer instruction, contract or product, service provider, movement of money or ownership record, supporting infrastructure, customer-facing disclosure, and complaint or escalation route. Then ask which parts are shared and which depend on the product. A payment and a securities investment may both move value, but their records, timing, risks, and oversight are not interchangeable. This method creates a clearer revision note than memorising an unqualified list of institutions.'),
    paragraph('When presenting a system map, include a short note about its limits: product definitions, institutional permissions, market infrastructure, and regulator mandates can change or depend on the exact activity. Add the official source beside each claim rather than citing one general explainer for the entire system. For a career learner, that habit is practical evidence of careful research and helps prevent a broad overview from being mistaken for current legal or investment guidance.'),
    link('RBI financial awareness material', 'https://www.rbi.org.in/commonman/English/Scripts/fame.aspx'),
    link('SEBI Investor education library', 'https://investor.sebi.gov.in/iematerial.html'),
    link('IRDAI: what the authority does', 'https://irdai.gov.in/web/policy-holder/what-we-do'),
    link('PFRDA: authority and regulatory role', 'https://pfrda.org.in/web/pfrda/about-us/authority/about-authority'),
    link('IFSCA: about the authority', 'https://www.ifsca.gov.in/beta/beta/Pages/Contents/About_Us'),
  ],
  'kyc-aml-compliance-guide': [
    heading('Separate the stages of customer due diligence'),
    paragraph('Customer due diligence is not one document check. A regulated organisation\'s framework may define customer identification, verification, understanding the purpose and intended nature of a relationship, beneficial-ownership procedures, risk assessment, ongoing review, and record handling. Screening and transaction monitoring are connected controls but answer different questions. The precise requirements depend on the entity, product, jurisdiction, customer, risk, and current law or direction.'),
    list([
      'Collection: obtain information through the approved channel and record its source and date.',
      'Validation: check completeness, consistency, and required supporting evidence under the current procedure.',
      'Review: route ownership, risk, screening, or unresolved discrepancies to the designated reviewer.',
      'Ongoing work: update records or review activity when the approved trigger or schedule applies.',
      'Disposition: document the authorised outcome, rationale, escalation, and retention requirements.',
    ]),
    heading('A high-quality case note distinguishes evidence from suspicion'),
    paragraph('Use a fictional case with a name-screening potential match and one inconsistent business document. Record the exact source fields that match or differ, the records checked, limitations, the question that remains, and the required reviewer. A potential match is not automatically the same person; unusual activity is not proof of wrongdoing; and an analyst should not make a restricted reporting or relationship decision outside their authority. Follow confidentiality, access, and escalation controls.'),
    heading('Regulatory currency and safe learning practice'),
    paragraph('KYC and AML requirements change through laws, rules, directions, and official amendments. The RBI Master Direction on KYC and FATF Recommendations are useful primary references, but a learner should open the current version, review amendment history, and check the rules relevant to the institution and activity. Treat this page as a learning framework, not legal advice or a universal operational checklist. Never use real customer documents or alert information in a public portfolio.'),
    heading('Screening and transaction monitoring answer different questions'),
    paragraph('Screening compares customer, counterparty, or transaction information with approved lists or other reference data and routes possible matches for review. Transaction monitoring looks for activity that requires assessment under the institution\'s approved scenarios and procedures. A potential match, an alert, and a confirmed finding are separate states. Case records should make clear what was checked, the evidence source, how a difference was resolved or escalated, and who had authority to make the final decision.'),
    paragraph('A defensible learning note can record the document title, issuing authority, publication or update date shown on the source, the exact topic being studied, and any later amendment or notification that must also be reviewed. Do not copy a checklist from an old article into an operational setting. Staff training, record retention, access, quality assurance, and escalation are connected parts of a controlled program, but their detailed requirements must come from the applicable current framework.'),
    link('Open RBI\'s current KYC Master Direction', 'https://www.rbi.org.in/scripts/BS_ViewMasDirections.aspx?id=11566'),
    link('Open the FATF Recommendations and revision history', 'https://www.fatf-gafi.org/en/publications/Fatfrecommendations/Fatf-recommendations.html'),
  ],
});

export const NEXT_LANDING_DEPTH_BLOCKS = Object.freeze({
  'finance-operations-syllabus': [
    heading('Read the syllabus as a sequence of work, not only subjects'),
    paragraph('A topic list becomes useful when it shows how a learner moves from a concept to an operational output. For each published subject, ask what process is being explained, which records are involved, what controls matter, what a learner practises, and how the learning is reviewed. This helps distinguish awareness of a term from the ability to explain a workflow. It also makes it easier to compare the Masterclass with a degree, exam-preparation route, professional qualification, or specialist course that has a different purpose.'),
    list([
      'Investment operations: connect trade details, confirmation, settlement, custody, events, and reconciliation.',
      'Retail banking: follow customer and account requests through evidence, service, and controlled processing.',
      'KYC and AML: understand due-diligence context, screening, monitoring, case evidence, and escalation.',
      'Payments: trace instruction, status, processing, reconciliation, dispute, and exception handling.',
      'Finance operations: connect accounting records, lending, credit, risk, reporting, and control work.',
      'FinTech: examine how product, technology, operations, compliance, and customer support interact.',
    ]),
    heading('Questions that reveal the quality of a syllabus'),
    paragraph('Ask for the current module outline, the order of topics, the practical tasks, the method of feedback, any assessment or completion conditions, and the source of program-specific terms. A clear syllabus should tell you what is included and where the program stops. For example, learning about a credit workflow does not automatically grant credit approval authority, and learning an AML concept does not make a learner a compliance officer.'),
    paragraph('After reviewing the outline, select one target role and compare its current vacancies with the relevant topics. Mark each requirement as covered for awareness, practised, evidenced, or not addressed. This simple gap map makes an enquiry more specific and helps you avoid choosing a broad program based on its title alone.'),
    heading('Turn a module into a reviewable work sample'),
    paragraph('Choose one workflow that appears in the current syllabus and create a compact practice record: a process map, invented input data, checks, one exception, an escalation note, and the expected final output. Add a short reflection that explains which step was difficult and what you would verify against an employer procedure. If an exercise is not reviewed, ask how you can receive feedback before treating it as evidence of skill. Keep the work sample clearly labelled as practice and use no confidential records.'),
    heading('Separate topic coverage from competence'),
    paragraph('A syllabus can introduce a subject without giving equal depth in every product, tool, regulation, or job family. Ask how much time is devoted to the topic, whether it is demonstrated or practised, and how feedback is provided. Then check a few target job descriptions for requirements that sit outside the published program. This lets you judge fit accurately and identify any additional study or employer-specific training you may need.'),
    paragraph('A topic-to-evidence table is a practical way to compare options: write the topic, the task you would practise, the output you would retain, and the feedback available. If a provider cannot explain an item, record it as unconfirmed and ask before you enrol. Recheck the table against the current course version because curricula and cohort arrangements can change.'),
  ],
  'finance-course-fees-eligibility': [
    heading('Use a like-for-like finance course comparison'),
    paragraph('Compare the full cost and learning arrangement for the same period and scope. Record tuition, taxes, instalments, required tools, travel where relevant, access duration, live-session schedule, missed-session policy, assessment, certificate terms, and any career-support conditions. If an item is not stated, mark it as unanswered rather than assuming it is included. Ask the provider to identify the cohort and date that the written answer applies to.'),
    list([
      'Cost: total payable, tax treatment, payment dates, and any separately charged item.',
      'Eligibility: education, documents, language, attendance, devices, and cohort requirements.',
      'Delivery: live or recorded format, time, location, access period, and recovery options.',
      'Learning: current syllabus, exercises, review, assessment, completion, and certificate wording.',
      'Terms: cancellation, refund, transfer, deferral, privacy, and support conditions.',
      'Career support: exact service, learner obligations, eligibility, exclusions, and published guarantee terms.',
    ]),
    heading('A decision worksheet before you pay'),
    paragraph('Write down the role you are exploring, the three skills you most need, the course components that address them, and the evidence you expect to produce. Then note the total cost, schedule fit, unresolved terms, and the written source for each answer. If a decision depends on a job guarantee, certificate recognition, refund, or placement support, read the applicable current terms and ask a direct question. A low price is not proof of value, and a high price is not proof of recognition or employment.'),
    paragraph('The Financial Operations Masterclass is the existing program discussed on this page. Confirm all current cohort details with Centaur Careers before enrolment; this guide does not publish a fixed fee or individual eligibility decision.'),
    heading('How to resolve unanswered terms'),
    paragraph('Send one concise enquiry with the cohort you are considering and list only the details that affect your decision. Ask for the total amount payable, what is included, the schedule and learning mode, the applicable refund or cancellation policy, certificate wording, and the written scope of career support. Save the response with the dated course information. If a term is unclear, request a plain-language explanation before paying instead of relying on a verbal summary or a general marketing statement.'),
    paragraph('Compare responses in writing and check that they refer to the same cohort and program version. If two pages or messages conflict, ask which current term controls and request the applicable policy or enrolment document. Retain the answer with your payment and enrolment records so you can refer to the exact scope later.'),
    paragraph('Eligibility is similarly cohort-specific. Ask about the documents needed, attendance, language, schedule, learning access, and any conditions attached to support. A broad audience description on a page should not be treated as a personal eligibility decision until the provider confirms how the current terms apply to you.'),
  ],
  'finance-course-for-graduates': [
    heading('Match your degree strengths to the role requirements'),
    paragraph('A graduate\'s degree can provide useful foundations, but employers assess the requirements of a particular job. Commerce study may make accounting language familiar; a quantitative degree may support data reasoning; a technology background may help with systems and process logic; and communication-heavy study may support documentation and customer interaction. These are starting points rather than guarantees. Compare actual tasks and eligibility in current vacancies.'),
    list([
      'For reconciliation or accounting support, practise records, matching logic, period checks, and evidence.',
      'For lending operations, practise file completeness, status tracking, conditions, and careful escalation.',
      'For investment operations, learn the trade lifecycle, product fields, cut-offs, settlement, and exceptions.',
      'For KYC or monitoring support, practise factual case writing, source tracking, privacy, and role boundaries.',
      'For analyst paths, explain calculations, assumptions, business context, and unanswered questions.',
    ]),
    heading('A graduate self-assessment before choosing a course'),
    paragraph('Rate your confidence in accounting basics, spreadsheets, business writing, banking products, process mapping, controls, and interview examples. Choose the two gaps most relevant to your target role and create a small fictional exercise for each. If the exercise exposes a need for foundational study, build that foundation first; if you can already explain the basics, seek deeper feedback or role-specific practice. Bring the gap list to a course enquiry so the provider can explain what its current program does and does not cover.'),
    heading('Build evidence that is safe and honest'),
    paragraph('A work sample might be a process map, a reconciliation with invented records, a short case note, or a spreadsheet that shows assumptions and checks. Label it as a practice exercise, explain the source of any public data, and do not present it as employer work. The point is to show how you reason, communicate, and respond to an exception, not to imply access to a bank\'s systems or a guaranteed job outcome.'),
    heading('A practical first set of actions for a graduate'),
    list([
      'Pick two role families and collect current vacancies from employers you would realistically consider.',
      'Record recurring tasks, eligibility, tools, location, schedule, and experience requirements.',
      'Refresh the foundation that appears most often, such as accounting, spreadsheets, product knowledge, or writing.',
      'Complete one fictional task for each role family and ask a knowledgeable reviewer for feedback.',
      'Compare the course syllabus and written terms with the gaps you still have before enrolling.',
    ], true),
    paragraph('This sequence helps graduates make a specific decision while keeping the course\'s published scope distinct from employer hiring criteria.'),
    heading('Review your plan after each application cycle'),
    paragraph('Track the roles you applied for, the requirements that recurred, the interview questions you found difficult, and any feedback you received. Separate a skill gap from a mismatch in location, schedule, eligibility, or experience. Update one work sample or resume example at a time and seek another review before changing your entire learning plan. Hiring decisions depend on employers and candidates; this process improves preparation but cannot promise an offer.'),
  ],
});

export const NEXT_COMPARISON_DEPTH_BLOCKS = Object.freeze({
  'investment-banking-operations-vs-financial-analyst': [
    heading('Compare a sample workday and its output'),
    paragraph('Imagine two fictional tasks. In an investment-operations task, an analyst checks whether a transaction record, confirmation, settlement instruction, and resulting position agree, then documents an exception before a deadline. In a financial-analysis task, an analyst reviews financial statements, explains business drivers, tests assumptions, and prepares a forecast or decision-support note. Both may use spreadsheets and require accuracy, but the questions and outputs are different.'),
    list([
      'Choose operations if you are drawn to controlled transaction flow, records, hand-offs, deadlines, and exception resolution.',
      'Explore financial analysis if you prefer statements, business performance, assumptions, forecasts, valuation, or decision support.',
      'Investigate hybrid roles by reading the actual deliverables and the proportion of each activity.',
      'Check whether a vacancy requires a particular qualification, modelling depth, product knowledge, or prior experience.',
    ]),
    heading('A two-exercise career-fit test'),
    paragraph('Create one fictional trade exception and one fictional company-analysis task. For the first, record the expected and observed fields, evidence, owner, deadline, and control needed for closure. For the second, calculate a simple change across two periods, state the assumptions, explain the business question, and identify missing evidence. Compare which task you enjoyed, where you made errors, and what you would need to learn next. This test is a reflection tool, not a hiring assessment.'),
    heading('Choose learning by the gap you found'),
    paragraph('If your target vacancy focuses on settlement, reconciliation, or transaction processing, prioritise lifecycle and control practice. If it emphasizes forecasting, valuation, or financial statement analysis, seek learning that develops those outputs at the required depth. The Financial Operations Masterclass is positioned around finance and BFSI operations topics; it should not be represented as a separate Financial Analyst course or a substitute for a credential required by an employer.'),
    heading('Questions that make the comparison concrete'),
    list([
      'What deliverable would I produce in a normal week: a controlled transaction record, a case investigation, or an analysis for a decision?',
      'Which data sources and assumptions would I need to explain?',
      'How much of the job is routine processing, exception handling, modelling, communication, or review?',
      'What education, tools, experience, and location constraints are stated in actual vacancies?',
      'Which learning option teaches and assesses the specific skill gap I identified?',
    ]),
    paragraph('Revisit the choice after completing both sample exercises. Interest, demonstrated skill, employer demand, and the required learning path all matter; an industry label alone does not settle the decision.'),
    heading('Resume evidence should match the selected path'),
    paragraph('For an operations application, describe a process you mapped, a fictional exception you investigated, the controls you considered, and how you verified the output. For an analysis application, describe the statements or public data you reviewed, the calculation and assumptions, the insight, and the limitations. Use accurate verbs such as practised, analysed, mapped, or supported. Do not imply that a study project was paid employment or that a course certificate is an external professional designation.'),
    heading('Check role requirements before choosing a credential'),
    paragraph('Some financial-analysis jobs may ask for advanced accounting, modelling, sector knowledge, or a professional qualification; some investment-operations roles may prioritise product, workflow, control, schedule, and communication skills. Requirements are set by each employer and seniority level. Read the vacancy and the issuing body\'s current information before paying for a credential. A course title that contains finance or investment banking does not by itself demonstrate that it teaches the specific outputs the role requires.'),
  ],
  'banking-vs-finance-careers': [
    heading('Banking is an industry; finance spans several industries'),
    paragraph('A bank employs people in customer service, lending, payments, operations, technology, risk, compliance, finance, treasury, and markets. Similar finance work also exists in companies, insurers, funds, market infrastructure, technology providers, and public institutions. This means a person can work in a finance function without working for a bank, and banking roles can involve customer service or operations rather than financial analysis.'),
    heading('Choose by daily tasks and constraints'),
    list([
      'Customer-facing banking: compare service conversations, product knowledge, documentation, and customer outcomes.',
      'Bank operations: compare transaction queues, account records, payments, controls, cut-offs, and exception work.',
      'Corporate finance or accounting: compare budgets, reporting periods, ledger records, forecasts, and business partners.',
      'Markets and investments: compare instruments, investment decisions, research, trade flow, and market-related requirements.',
      'Risk and compliance: compare monitoring, evidence, policies, control testing, case review, and escalation authority.',
      'FinTech: compare product operations, technology dependencies, digital customer journeys, and control responsibilities.',
    ]),
    heading('A practical shortlist exercise'),
    paragraph('Select three current vacancies from two role families. For each, note the daily output, required education, experience, tools, communication needs, work location, shift or deadline, and decision rights. Circle requirements that repeat and build one fictional work sample that demonstrates a relevant skill. Remove roles whose eligibility or working conditions do not fit, then research any qualification or exam the remaining vacancies require. This turns a broad interest in banking or finance into a searchable, testable plan.'),
    paragraph('No single path is best for every graduate. Use current employer requirements and official qualification information when choosing education. The existing Financial Operations Masterclass covers the published operations-oriented subjects; it is one learning option within a much wider financial system.'),
    heading('A checklist for comparing a specific vacancy'),
    list([
      'What customer, transaction, asset, business, or decision does the role support?',
      'What is the recurring output and how is its quality measured?',
      'Which systems, records, regulations, or professional standards does the vacancy name?',
      'What work schedule, location, eligibility, and experience does the employer require?',
      'Which next role family could the experience support, and what additional skills would it need?',
    ]),
    paragraph('Use the answers to make a short list of relevant roles, not to assume that banking and finance have one standard entry route. Requirements differ by employer, product, seniority, and location.'),
    heading('Avoid common career-path assumptions'),
    paragraph('A banking title does not necessarily mean branch sales, and a finance title does not necessarily mean investment analysis. A back-office role can require strong product and control knowledge; a finance analyst vacancy may focus on accounting, planning, commercial performance, or markets depending on the employer. Likewise, a course with banking in its title may not prepare someone for a public-sector recruitment exam or a professional credential. Confirm the actual curriculum and eligibility before comparing options.'),
    heading('Use current evidence to choose a direction'),
    paragraph('A practical comparison starts with several real vacancies rather than a broad claim about which industry is growing faster. Record the posting date, employer, location, seniority, daily tasks, required education, experience, tools, and schedule. Then check whether the pattern repeats across employers. Market conditions and hiring needs change; your own shortlist should be refreshed as you apply. This creates a grounded view of demand without relying on unverified salary ranges or promises of placements.'),
  ],
});
