// Phase 8 regional pages. These are selective market-and-access guides, not
// location pages for Centaur Careers offices or classrooms.

const AUTHOR = Object.freeze({
  name: 'Bharat Singh',
  role: 'Founder & Director, Centaur Careers',
  profilePath: '/about/',
});

export const REGIONAL_PAGES = Object.freeze([
  Object.freeze({
    id: 'delhi-ncr',
    routeId: 'india-delhi-ncr',
    path: '/best-finance-course-in-delhi/',
    title: 'Best Online Finance Course in Delhi? | Centaur Careers',
    description: 'Explore live online finance training for Delhi, Gurugram and Noida. Centaur Careers’ six-week Masterclass is online; in-person sessions are in Lucknow.',
    h1: 'Best Online Finance Course in Delhi? Live NCR Learning Guide',
    image: '/images/blog/banking-sector-india-structure-operations.png',
    imageAlt: 'Illustration of banking operations roles and workflows for Delhi-NCR job research',
    breadcrumbLabel: 'Delhi-NCR',
    primaryKeyword: 'investment banking course in Delhi',
    regionName: 'Delhi-NCR',
    regionSchemaType: 'AdministrativeArea',
    localAreas: Object.freeze(['Delhi', 'Gurugram', 'Noida', 'Ghaziabad', 'Faridabad']),
    localAreaNote: 'Delhi-NCR is not one commute or one hiring market. Use the exact city, office corridor, work model, and shift named in each current posting.',
    updatedAt: '2026-10-05',
    sourceReviewedAt: '2026-09-26',
    author: AUTHOR,
    directAnswer: 'Delhi-NCR learners can join the six-week Financial Operations Masterclass live online. Investment banking operations is one module in this single course; the published in-person option is in Lucknow. For a local job search, compare Delhi, Gurugram, and Noida postings by workflow, office location, work model, and shift.',
    courseQuestion: 'Looking for an online finance course in Delhi with investment banking operations?',
    courseAnswer: 'Centaur Careers offers one six-week Financial Operations Masterclass covering investment banking operations, KYC and AML, retail banking, and finance operations. Delhi-NCR learners can join live online; the published in-person option is in Lucknow. The Job Guarantee Program applies to eligible graduates and job switchers after completing the course and guarantees a finance job, not a Delhi-specific vacancy. Read the current written terms before enrolling.',
    marketSignals: [
      'Delhi-NCR is a multi-city employment market. The region combines Delhi’s financial and public-sector context with business-services activity in Gurugram and Noida; a job search should therefore use the exact work location and operating model in each posting.',
      'Dun & Bradstreet’s 2025 NCR GCC edition reports 465 GCCs and more than 270,000 professionals across the region. Its industry view places BFSI alongside larger technology, consulting, and engineering segments, which means finance operations applicants should search beyond job titles containing only “investment banking”.',
      'A useful Delhi-NCR distinction is between client-facing finance work and controlled operations work. Roles may sit in lending, insurance, payments, fund or asset servicing, reconciliations, onboarding, or risk controls while still requiring careful data handling and process discipline.',
    ],
    roleSignals: [
      'KYC, AML, sanctions-screening, and client-onboarding analyst roles',
      'Loan processing, credit operations, NBFC, and lending support roles',
      'Trade support, settlements, reconciliations, fund administration, and asset-servicing operations',
      'Payments operations, dispute handling, fraud operations, and controls analyst roles',
      'GCC business-process, reporting, quality, and risk-and-control roles in Gurugram or Noida',
    ],
    workflowLinks: Object.freeze([
      Object.freeze({ label: 'KYC and AML analyst guide', path: '/career-guides/kyc-aml-analyst/' }),
      Object.freeze({ label: 'Reconciliation analyst guide', path: '/career-guides/reconciliation-analyst/' }),
      Object.freeze({ label: 'Client onboarding and retail operations guide', path: '/career-guides/retail-banking-operations/' }),
    ]),
    practicalResearch: [
      'Search each posting for the actual location: Delhi, Gurugram, Noida, Ghaziabad, Faridabad, or a remote/hybrid arrangement. “Delhi-NCR” is not one commute or one hiring market.',
      'Map the workflow named in the job description. “Reconciliation”, “exception management”, “client static data”, “KYC refresh”, and “service-level controls” point to different preparation priorities.',
      'For entry-level applications, keep a small evidence portfolio: a reconciled sample, a control checklist, a clear escalation note, and a short explanation of one end-to-end finance workflow.',
    ],
    localResearchExample: Object.freeze({
      title: 'Example: compare a Gurugram KYC role with a Noida operations role',
      situation: 'Imagine one posting asks for KYC refresh and case notes in Gurugram, while another asks for payment reconciliation and exception queues in Noida. These are illustrative postings, not current vacancies.',
      decision: 'For the first, practise a fictional customer-file review and a clear escalation note. For the second, practise matching payment records and explaining a break. Then check each real posting for degree requirements, shift, work model, and commute before applying.',
      guidePath: '/career-guides/kyc-aml-analyst/',
      guideLabel: 'Understand KYC analyst work',
    }),
    accessText: 'Learners in Delhi-NCR can join the Financial Operations Masterclass live online. The published in-person location is Mindsprout Career Hub in Lucknow; Centaur Careers does not list a Delhi-NCR classroom. Ask for the current cohort schedule, fees, and written support terms before enrolling.',
    faqIntro: 'These answers separate Delhi-NCR job-market research from Centaur Careers’ provider-specific delivery information.',
    faqs: Object.freeze([
      Object.freeze({ question: 'Is there a banking operations course in Delhi with placement?', answer: 'Centaur Careers offers its Financial Operations Masterclass live online to Delhi-NCR learners, with banking and finance operations topics and a published Job Guarantee Program after course completion for eligible graduates and job switchers. The promise is a finance job, not a guaranteed Delhi posting or classroom; review the current written terms.' }),
      Object.freeze({ question: 'Is there an investment banking course in Delhi-NCR through Centaur Careers?', answer: 'The published access route for learners outside Lucknow is live online learning through the Financial Operations Masterclass. Confirm the current cohort and fees directly; this page does not claim a Delhi-NCR classroom.' }),
      Object.freeze({ question: 'Which finance operations roles should Delhi-NCR applicants research?', answer: 'Research KYC and AML, lending and NBFC operations, payments and fraud operations, trade support, reconciliations, fund or asset servicing, and GCC controls roles. The workflow and employer requirements matter more than using one broad “investment banking” label.' }),
      Object.freeze({ question: 'Should I search only for jobs in Delhi city?', answer: 'No. Delhi-NCR postings may specify Gurugram, Noida, Ghaziabad, Faridabad, Delhi, or a hybrid arrangement. Read the exact location, shift, and work-model requirements before deciding whether a posting fits.' }),
      Object.freeze({ question: 'Does this page list Delhi-NCR salaries?', answer: 'No. Compensation depends on role scope, employer, experience, shift, and location. Use current employer listings and transparent public sources when comparing pay, and treat any number as time-sensitive rather than as a Centaur Careers promise.' }),
    ]),
    evidence: Object.freeze([
      Object.freeze({ label: 'Dun & Bradstreet, GCC Landscape in NCR 2025', href: 'https://www.dnb.co.in/files/reports/Rethinking-the-Future-of-Global-Capability-Center-NCR-2025.pdf', note: 'Regional GCC footprint, professional base, city distribution, and industry mix.' }),
      Object.freeze({ label: 'NITI Aayog, India’s Services Sector', href: 'https://www.niti.gov.in/node/2028', note: 'Delhi services-employment context and financial/insurance activity reference.' }),
    ]),
  }),
  Object.freeze({
    id: 'bengaluru',
    routeId: 'india-bengaluru',
    path: '/best-finance-course-in-bangalore/',
    title: 'Best Online Finance Course in Bangalore? | Centaur Careers',
    description: 'Explore live online finance training for Bangalore and Bengaluru learners, including investment operations and fintech workflows. In-person sessions are in Lucknow.',
    h1: 'Best Online Finance Course in Bangalore? Bengaluru Course Guide',
    image: '/images/blog/fintech-operations-careers-india.jpg',
    imageAlt: 'Illustration of finance and fintech operations career paths relevant to Bengaluru learners',
    breadcrumbLabel: 'Bengaluru',
    primaryKeyword: 'investment banking course in Bangalore',
    regionName: 'Bengaluru',
    regionSchemaType: 'City',
    regionAlternateName: 'Bangalore',
    localAreas: Object.freeze(['Whitefield', 'Outer Ring Road', 'Electronic City', 'Manyata Tech Park', 'central Bengaluru']),
    localAreaNote: 'Bengaluru roles can sit across technology corridors and business districts. Check the exact office area, commute, hybrid policy, and shift before comparing opportunities.',
    updatedAt: '2026-10-05',
    sourceReviewedAt: '2026-09-26',
    author: AUTHOR,
    directAnswer: 'Bengaluru (Bangalore) learners can study Centaur Careers’ six-week Financial Operations Masterclass live online. Investment banking operations, payments, KYC and AML, and FinTech are modules within one course; in-person sessions are published only in Lucknow. Use this guide to research Bengaluru finance-process and technology-enabled roles by their actual tasks and tools.',
    courseQuestion: 'Looking for an online investment banking course in Bangalore?',
    courseAnswer: 'Centaur Careers offers one six-week Financial Operations Masterclass with investment banking operations topics such as trade lifecycle, settlements, reconciliation, and corporate actions. Bengaluru learners can join live online; the published in-person option is in Lucknow. Eligible graduates and job switchers who complete the course are covered by the Job Guarantee Program for a finance job, not a Bengaluru-specific vacancy. Confirm current cohort details and written terms.',
    marketSignals: [
      'Karnataka Digital Economy Mission’s FinTech Task Group report identifies policy, a Centre of FinTech Excellence, training and talent support, mentorship, and financial literacy as focus areas. That makes it sensible to study both finance workflows and the technology-enabled controls around them.',
      'Karnataka Digital Economy Mission describes IT products, business-process work, and GCC promotion as parts of its state mandate. This is ecosystem context for a learner comparing operations roles; it is not a count of Bengaluru finance vacancies.',
      'Bengaluru postings often mix financial knowledge with operating-system fluency. Applicants should expect job descriptions to mention data quality, product or process operations, automation hand-offs, audit trails, stakeholder communication, and incident or exception management alongside finance terminology.',
    ],
    roleSignals: [
      'Fintech product operations, payments operations, settlement support, and dispute workflows',
      'KYC, AML, transaction monitoring, fraud operations, and compliance controls',
      'Reconciliations, management reporting, data-quality checks, and operational risk support',
      'GCC process analyst, business analyst, service delivery, and quality-assurance roles',
      'Investment operations, fund administration, and middle-office roles requiring careful hand-offs',
    ],
    workflowLinks: Object.freeze([
      Object.freeze({ label: 'Investment banking operations career guide', path: '/career-guides/investment-banking-operations/' }),
      Object.freeze({ label: 'Digital payments operations guide', path: '/career-guides/digital-payments-operations/' }),
      Object.freeze({ label: 'FinTech operations guide', path: '/career-guides/fintech-operations/' }),
    ]),
    practicalResearch: [
      'Separate a finance-domain requirement from a software-engineering requirement. Many Bengaluru roles need spreadsheet, workflow, SQL, dashboard, or ticketing literacy without being software-development jobs.',
      'Look for the operating metric behind the role: accuracy, turnaround time, break resolution, control completion, customer impact, or incident closure. Prepare one example that shows how you would measure and improve that metric.',
      'For fintech and GCC searches, record the product or process in each posting. Payments, lending, brokerage, insurance, and wealth workflows use different vocabulary and control points.',
    ],
    localResearchExample: Object.freeze({
      title: 'Example: separate a payments role from a software role',
      situation: 'Imagine a Whitefield posting asks for payment-status checks, reconciliation, and merchant issue notes, while an Outer Ring Road posting asks for software development. These are illustrative role descriptions, not current openings.',
      decision: 'For the payments role, practise tracing a fictional transaction from instruction to status and documenting an unmatched record. Check whether the real posting expects a coding role, a finance workflow role, or both before choosing preparation.',
      guidePath: '/career-guides/digital-payments-operations/',
      guideLabel: 'Explore digital payments operations',
    }),
    accessText: 'Bengaluru learners can join the Financial Operations Masterclass live online. The published in-person location is Mindsprout Career Hub in Lucknow; Centaur Careers does not list a Bengaluru classroom. Confirm the current schedule, fees, and written support terms with the team.',
    faqIntro: 'These answers connect Bengaluru’s technology-enabled finance market with the provider information that must still be confirmed directly.',
    faqs: Object.freeze([
      Object.freeze({ question: 'Can I take an investment banking operations course in Bangalore with placement?', answer: 'Centaur Careers offers live online access from Bengaluru to its six-week Financial Operations Masterclass, which includes investment banking operations. Its published Job Guarantee Program applies to eligible graduates and job switchers after course completion and promises a finance job, not a specific Bengaluru role or employer. Read the current written terms.' }),
      Object.freeze({ question: 'Can I join Centaur Careers from Bengaluru?', answer: 'The public program information describes live online sessions for learners outside Lucknow. Contact Centaur Careers to confirm the current cohort schedule, learning mode, and fees. No Bengaluru classroom is claimed here.' }),
      Object.freeze({ question: 'What should a Bengaluru finance operations applicant learn first?', answer: 'Start with one complete workflow such as payment processing, reconciliation, KYC review, trade settlement, or exception handling. Then add the spreadsheet, data-quality, reporting, and communication skills named in the specific job descriptions you are targeting.' }),
      Object.freeze({ question: 'Are Bengaluru GCC roles the same as software jobs?', answer: 'No. GCCs can contain finance operations, controls, reporting, service delivery, business analysis, and process-quality work as well as technology roles. Read the responsibilities and required tools instead of classifying a role from the employer label alone.' }),
      Object.freeze({ question: 'Does the Masterclass promise a job in Bengaluru?', answer: "No Bengaluru-specific job or vacancy is promised here. Read Centaur Careers' current Placements page and written program terms for the scope and conditions of its job guarantee, and confirm location expectations before enrolling." }),
    ]),
    evidence: Object.freeze([
      Object.freeze({ label: 'KDEM FinTech Task Group Report 2022', href: 'https://karnatakadigital.in/wp-content/uploads/2023/02/KDEM-FinTech-Task-Force-Report_Final.pdf', note: 'Karnataka fintech policy, talent support, and Bengaluru-cluster context.' }),
      Object.freeze({ label: 'KDEM software, products and GCC promotion', href: 'https://karnatakadigital.in/software-products-services-including-global-capability-centers-gcc/', note: 'Public Karnataka Digital Economy Mission description of GCC and technology-enablement initiatives.' }),
    ]),
  }),
  Object.freeze({
    id: 'mumbai',
    routeId: 'india-mumbai',
    path: '/best-finance-course-in-mumbai/',
    title: 'Best Online Finance Course in Mumbai? | Centaur Careers',
    description: 'Explore live online finance training for Mumbai learners, including investment operations, settlements and reconciliation. In-person sessions are in Lucknow.',
    h1: 'Best Online Finance Course in Mumbai? Investment Operations Guide',
    image: '/images/blog/investment-banking-teams-operations.png',
    imageAlt: 'Illustration of investment banking operations teams and post-trade workflows for Mumbai role research',
    breadcrumbLabel: 'Mumbai',
    primaryKeyword: 'investment banking course in Mumbai',
    regionName: 'Mumbai',
    regionSchemaType: 'City',
    localAreas: Object.freeze(['Bandra Kurla Complex', 'Lower Parel', 'Andheri', 'Navi Mumbai', 'Thane']),
    localAreaNote: 'Mumbai finance roles are distributed across different business and market corridors. Read the exact office location, product workflow, commute, and work model in each posting.',
    updatedAt: '2026-10-05',
    sourceReviewedAt: '2026-09-26',
    author: AUTHOR,
    directAnswer: 'Mumbai learners can study Centaur Careers’ six-week Financial Operations Masterclass live online. Investment banking operations is one module in the course, with trade settlements and reconciliation among its topics. The published in-person option is in Lucknow. For Mumbai career research, distinguish post-trade, fund-servicing, payments, and front-office job descriptions before preparing.',
    courseQuestion: 'Looking for an online investment banking course in Mumbai?',
    courseAnswer: 'Centaur Careers offers one six-week Financial Operations Masterclass that includes investment banking operations, KYC and AML, retail banking, payments, and finance operations topics. Mumbai learners can join live online; the published in-person option is in Lucknow. The 100% Job Guarantee Program covers eligible graduates and job switchers after course completion for a finance job, not a Mumbai-specific vacancy. Confirm the current written terms before enrolling.',
    marketSignals: [
      'SEBI lists its head office in Bandra Kurla Complex, and the National Stock Exchange lists its corporate office there. These official addresses establish market-infrastructure context, not the number of available jobs. Use post-trade processing, reconciliation, settlement, and intermediary controls as lenses when reading actual Mumbai job descriptions.',
      'The Government of Maharashtra’s Mumbai FinTech initiative describes Mumbai as a target global fintech hub and brings together financial institutions, regulators, technology partners, and academic institutions. The page also publishes programme metrics that can change, so this guide links to the source instead of turning them into permanent promises.',
      'Mumbai finance roles can sit in a regulated market workflow or in a technology-enabled service workflow. In both cases, applicants should understand ownership, cut-off times, exception queues, evidence retention, and escalation paths rather than relying on a broad course label alone.',
    ],
    roleSignals: [
      'Trade support, settlements, confirmations, reconciliations, and custody operations',
      'Brokerage, exchange, clearing, market-intermediary, and securities-operations support',
      'KYC, AML, client onboarding, transaction monitoring, and regulatory-control roles',
      'Banking, NBFC, insurance, payments, and fintech process-operations roles',
      'Fund accounting, asset servicing, reporting, and operational-risk support',
    ],
    workflowLinks: Object.freeze([
      Object.freeze({ label: 'Securities operations guide', path: '/career-guides/securities-operations/' }),
      Object.freeze({ label: 'Settlement analyst guide', path: '/career-guides/settlement-analyst/' }),
      Object.freeze({ label: 'Fund accounting and NAV workflow', path: '/blog/fund-accounting-nav-workflow-career-skills/' }),
    ]),
    practicalResearch: [
      'Read the product and event language in a posting: equities, fixed income, derivatives, funds, payments, lending, or insurance each imply different operations knowledge.',
      'Build interview answers around a controlled hand-off. Explain what you would verify, how you would record a break, when you would escalate, and which evidence another team would need to close the item.',
      'Use the regulator or market-infrastructure vocabulary in the employer’s job description, but do not assume that a Mumbai role is automatically front-office investment banking. Many opportunities are in essential middle- and back-office processes.',
    ],
    localResearchExample: Object.freeze({
      title: 'Example: tell post-trade work from deal work',
      situation: 'Imagine a Bandra Kurla Complex posting asks for settlement exceptions and position reconciliation, while another Mumbai posting asks for valuation models and transaction pitches. These are illustrative descriptions, not live vacancies.',
      decision: 'Prepare a trade-lifecycle and break-investigation example for the first. The second calls for different modelling and advisory preparation. Check the actual office, product, shift, and entry requirements before treating both as the same “investment banking” role.',
      guidePath: '/career-guides/trade-lifecycle/',
      guideLabel: 'Follow the trade lifecycle',
    }),
    accessText: 'Mumbai learners can join the Financial Operations Masterclass live online. The published in-person location is Mindsprout Career Hub in Lucknow; Centaur Careers does not list a Mumbai classroom. Confirm the current cohort schedule, fees, and written support terms before enrolling.',
    faqIntro: 'These answers explain how to use Mumbai market evidence without confusing it with Centaur Careers’ own delivery and placement pathway.',
    faqs: Object.freeze([
      Object.freeze({ question: 'Is there a KYC AML course in Mumbai with placement?', answer: 'Centaur Careers teaches KYC and AML as subjects in its six-week Financial Operations Masterclass, available live online to Mumbai learners. Its published Job Guarantee Program applies to eligible graduates and job switchers after course completion and promises a finance job, not a specific Mumbai vacancy or employer. Review the current written terms; the in-person option is in Lucknow.' }),
      Object.freeze({ question: 'Can I take an investment banking operations course from Mumbai?', answer: 'Centaur Careers describes live online sessions for learners who are not in Lucknow. Review the Financial Operations Masterclass and contact the team to confirm current cohort details, fees, and learning mode. This page does not claim a Mumbai centre.' }),
      Object.freeze({ question: 'Which Mumbai roles connect most closely to investment banking operations?', answer: 'Research trade support, settlements, confirmations, reconciliations, custody, fund or asset servicing, market-intermediary controls, KYC and AML, and operational-risk roles. The exact product, process, and shift requirements should come from the current employer posting.' }),
      Object.freeze({ question: 'Why are settlements and reconciliations important for Mumbai roles?', answer: 'Mumbai’s market-infrastructure context means many operations teams protect the accuracy and timeliness of post-trade records, cash or position data, exception handling, and downstream reporting. Applicants should learn the workflow and control logic rather than memorising isolated terms.' }),
      Object.freeze({ question: 'Does Centaur Careers promise a job in Mumbai?', answer: 'No Mumbai-specific vacancy or job location is promised on this guide. Review the current Placements page and written program terms for the scope and conditions of Centaur Careers’ job guarantee, and ask about location expectations.' }),
    ]),
    evidence: Object.freeze([
      Object.freeze({ label: 'Government of Maharashtra, Mumbai FinTech', href: 'https://fintech.maharashtra.gov.in/', note: 'State fintech initiative, Mumbai global-hub context, and programme ecosystem description.' }),
      Object.freeze({ label: 'NSE, Corporate and Branch Offices', href: 'https://www.nseindia.com/static/contact/contact-us', note: 'Official NSE corporate-office address in Mumbai’s Bandra Kurla Complex.' }),
      Object.freeze({ label: 'SEBI, Contact Us', href: 'https://www.sebi.gov.in/contact-us.html', note: 'SEBI head-office reference in Mumbai’s Bandra Kurla Complex.' }),
    ]),
  }),
  Object.freeze({
    id: 'pune',
    routeId: 'india-pune',
    path: '/best-finance-course-in-pune/',
    title: 'Best Online Finance Course in Pune? | Centaur Careers',
    description: 'Explore live online finance training for Pune learners, with finance operations, KYC and payments modules. In-person sessions are held in Lucknow.',
    h1: 'Best Online Finance Course in Pune? Local Career Guide',
    breadcrumbLabel: 'Pune',
    primaryKeyword: 'investment banking course in Pune',
    regionName: 'Pune',
    regionSchemaType: 'City',
    localAreas: Object.freeze(['Hinjawadi', 'Kharadi', 'Viman Nagar', 'Magarpatta', 'central Pune']),
    localAreaNote: 'Pune opportunities can differ materially by technology corridor and office area. Compare the named workflow, commute, shift, and hybrid expectations rather than using Pune as one broad label.',
    updatedAt: '2026-10-05',
    sourceReviewedAt: '2026-09-26',
    author: AUTHOR,
    directAnswer: 'Pune learners can join Centaur Careers’ six-week Financial Operations Masterclass live online. Investment banking operations is one of its modules; the published in-person option is in Lucknow. For Pune career research, compare roles by workflow and office area, including Hinjawadi and other business districts, then confirm the current course schedule and terms directly.',
    courseQuestion: 'Looking for an online finance course in Pune?',
    marketSignals: [
      'Pune’s employment geography spans the central business districts, Hinjawadi, and other technology and industrial corridors. Commute, shift, and hybrid expectations can change which vacancy is practical, so search by the exact work location rather than relying on a broad Pune label.',
      'The Government of Maharashtra’s district-industry reference is useful for understanding local industrial context, while state statistical publications provide dated district-level indicators. Neither source should be treated as a live finance-hiring feed.',
      'STPI-Pune describes Hinjawadi as a significant technology cluster and reports exports by STPI-registered units under its jurisdiction. This is broad IT/ITeS and electronics context, not a count of finance vacancies, investment-banking teams, or entry-level openings. Use it only as one clue that technology-enabled business services are part of the local environment.',
      'Finance-related job titles may appear inside banks, asset or fund services, business-process teams, lending firms, payment providers, and shared-service operations. Search for the task—reconciliation, onboarding, transaction support, loan processing, or controls—as well as the employer category.',
    ],
    roleSignals: [
      'Investment operations, trade support, settlements, and reconciliation roles',
      'KYC, AML, customer onboarding, screening, and compliance operations',
      'NBFC and lending operations, loan documentation, and credit support',
      'Digital payments, dispute handling, transaction support, and process controls',
      'Technology-enabled business services, reporting, and quality roles',
    ],
    workflowLinks: Object.freeze([
      Object.freeze({ label: 'Finance operations guide', path: '/career-guides/finance-operations/' }),
      Object.freeze({ label: 'Reconciliation in finance resource', path: '/resources/reconciliation-in-finance/' }),
      Object.freeze({ label: 'Digital payments operations guide', path: '/career-guides/digital-payments-operations/' }),
    ]),
    practicalResearch: [
      'For every vacancy, record the actual office area, work mode, shift, required experience, and named workflow. Hinjawadi and central Pune are not interchangeable commute locations.',
      'Build a role-based search list: “trade support Pune,” “KYC analyst Pune,” “loan operations Pune,” and “payments reconciliation Pune.” Compare responsibilities before deciding that two titles describe the same work.',
      'Before enrolling, request a dated syllabus, sample exercise, assessment method, total fees, certificate wording, learning mode, and support terms. Check that the practice resembles the tasks in current job descriptions you have collected.',
    ],
    localResearchExample: Object.freeze({
      title: 'Example: compare reconciliation with lending support',
      situation: 'Imagine a Hinjawadi posting asks for reconciliation breaks and control reports, while a Kharadi posting asks for loan-document checks and case routing. These are illustrative descriptions, not current vacancies.',
      decision: 'For reconciliation, practise tracing two unmatched records. For lending support, practise checking a fictional application for missing documents and explaining the next authorised hand-off. Compare the real posting’s shift, commute, and degree criteria before applying.',
      guidePath: '/career-guides/finance-operations/',
      guideLabel: 'Understand finance operations work',
    }),
    accessText: 'Pune learners can join the Financial Operations Masterclass live online. The published in-person option is in Lucknow; Centaur Careers does not list a Pune classroom or promise a Pune job on this guide. Confirm the current schedule, fees, and written support terms with the team.',
    faqIntro: 'Use these answers to compare learning format, Pune role requirements, and written program terms.',
    faqs: Object.freeze([
      Object.freeze({ question: 'How should I compare an investment banking operations course in Pune with deal training?', answer: 'Check whether the syllabus teaches post-trade processing, reconciliations, and controls or valuation and advisory work. Centaur Careers teaches investment banking operations within one six-week Financial Operations Masterclass, available live online from Pune. Match the topic to current employer requirements.' }),
      Object.freeze({ question: 'Do investment banking classes in Pune require a local classroom?', answer: 'A city label does not establish a classroom. Ask any provider for the current teaching venue or live online format, schedule, practice, and feedback. Centaur Careers publishes an in-person option in Lucknow and live online access from Pune.' }),
      Object.freeze({ question: 'How do I verify an investment banking institute in Pune?', answer: 'Check the provider identity, instructor, dated syllabus, total fees, assessment, certificate issuer, and refund terms. Ask for the physical address if local attendance matters; Centaur Careers does not list a Pune classroom.' }),
      Object.freeze({ question: 'Which roles should a finance operations course in Pune help me prepare for?', answer: 'Compare current Pune postings for reconciliation, trade support, lending, payments, KYC, and controls. A Hinjawadi reconciliation role and a Kharadi lending role need different examples, so record the office area, workflow, shift, and tools before choosing practice.' }),
      Object.freeze({ question: 'Is there a separate KYC AML course in Pune from Centaur Careers?', answer: 'No. KYC and AML is a module within the Financial Operations Masterclass. Ask which due-diligence, case-record, and escalation exercises the current cohort includes; the program is available live online from Pune.' }),
      Object.freeze({ question: 'Does a finance course with placement assistance in Pune include a Pune job?', answer: 'Do not infer a Pune vacancy from that phrase. This guide promises no city-specific job. Read the current Placements page and written program terms for the scope and conditions of Centaur Careers’ job guarantee, then ask about location expectations.' }),
      Object.freeze({ question: 'What is the best investment banking course in Pune for my target role?', answer: 'The best fit depends on the actual job. For operations roles, compare workflow practice, feedback, schedule, cost, and written terms with recent postings. For deal or modelling roles, check whether the syllabus actually teaches those skills before enrolling.' }),
    ]),
    evidence: Object.freeze([
      Object.freeze({ label: 'Software Technology Parks of India, STPI-Pune', href: 'https://stpi.in/about-stpi-pune', note: 'Official overview of the Hinjawadi centre and STPI-Pune’s broad technology-services ecosystem; it is not finance-job or vacancy data.' }),
      Object.freeze({ label: 'District Pune, District Industries', href: 'https://pune.gov.in/document/district-industries/', note: 'Official district-industry reference; it provides broad local context and is not a count of finance vacancies.' }),
    ]),
  }),
  Object.freeze({
    id: 'hyderabad',
    routeId: 'india-hyderabad',
    path: '/best-finance-course-in-hyderabad/',
    title: 'Best Online Finance Course in Hyderabad? | Centaur Careers',
    description: 'Explore live online finance training for Hyderabad learners, including GCC, KYC, payments and investment operations workflows. In-person sessions are in Lucknow.',
    h1: 'Best Online Finance Course in Hyderabad? Local Career Guide',
    breadcrumbLabel: 'Hyderabad',
    primaryKeyword: 'investment banking course in Hyderabad',
    regionName: 'Hyderabad',
    regionSchemaType: 'City',
    localAreas: Object.freeze(['HITEC City', 'Gachibowli', 'Financial District', 'Madhapur', 'Secunderabad']),
    localAreaNote: 'Hyderabad finance-process roles are spread across several business zones. Check the precise office area, travel expectations, shift, and work model before treating two listings as comparable.',
    updatedAt: '2026-10-05',
    sourceReviewedAt: '2026-09-26',
    author: AUTHOR,
    directAnswer: 'Hyderabad learners can study Centaur Careers’ six-week Financial Operations Masterclass live online. Investment banking operations, KYC and AML, and payments are modules within that single course; the published in-person option is in Lucknow. Use this guide to compare Hyderabad finance-process and GCC role descriptions by their actual workflow, tools, location, and shift.',
    courseQuestion: 'Looking for an online finance course in Hyderabad?',
    marketSignals: [
      'Hyderabad’s technology and business-services ecosystem includes a range of IT, IT-enabled services, global capability centre, and shared-service activity. Telangana government policy documents describe these sectors as strategic areas; a policy direction is context for research, not proof that a particular employer is hiring today.',
      'The city’s employment market is distributed across areas such as HITEC City, Gachibowli, the Financial District, and other business zones. Check commute, work model, shift, and the exact employer address in each listing rather than treating “Hyderabad” as one uniform location.',
      'Finance-process work can sit within banking, insurance, lending, payments, consulting, and multinational service organisations. Some vacancies combine product knowledge with reporting, controls, client onboarding, or exception management, so read the actual responsibilities instead of inferring them from the company’s sector.',
    ],
    roleSignals: [
      'KYC, AML, onboarding, screening, and transaction-monitoring support',
      'Investment operations, trade support, settlements, and reconciliation',
      'Lending, NBFC, loan servicing, documentation, and credit operations',
      'Payment operations, dispute workflows, wallet or transaction reconciliation',
      'GCC process analysis, reporting, controls, quality, and service delivery',
    ],
    workflowLinks: Object.freeze([
      Object.freeze({ label: 'KYC and AML analyst guide', path: '/career-guides/kyc-aml-analyst/' }),
      Object.freeze({ label: 'Client onboarding and retail operations guide', path: '/career-guides/retail-banking-operations/' }),
      Object.freeze({ label: 'FinTech operations guide', path: '/career-guides/fintech-operations/' }),
    ]),
    practicalResearch: [
      'Search both the role and its work area, then check on-site, hybrid, or remote expectations and any shift requirement. A role located in Gachibowli may not be a practical match for every Hyderabad commute.',
      'Translate each job description into a workflow map: input, validation, decision or control point, exception route, record, and hand-off. This helps identify what knowledge or practice is actually relevant.',
      'Compare programs using a written syllabus, realistic exercises, instructor access, assessment and feedback, credential issuer, fees, delivery format, and transparent career-support terms. Save the dated information because cohorts and vacancies change.',
    ],
    localResearchExample: Object.freeze({
      title: 'Example: compare onboarding with process controls',
      situation: 'Imagine a Gachibowli posting asks for client-onboarding checks and case notes, while a Financial District posting asks for exception reports and control follow-up. These are illustrative descriptions, not live vacancies.',
      decision: 'Prepare a fictional onboarding-file review for the first and an exception log for the second. Check the current employer’s product, tools, shift, office area, and experience requirements before choosing a course topic or applying.',
      guidePath: '/career-guides/fintech-operations/',
      guideLabel: 'Explore technology-enabled finance work',
    }),
    accessText: 'Hyderabad learners can join the Financial Operations Masterclass live online. The published in-person option is in Lucknow; Centaur Careers does not list a Hyderabad classroom or promise a Hyderabad job on this guide. Confirm the current schedule, fees, and written support terms with the team.',
    faqIntro: 'These answers connect Hyderabad role research with the actual online learning and placement terms.',
    faqs: Object.freeze([
      Object.freeze({ question: 'How should I compare an investment banking operations course in Hyderabad with deal training?', answer: 'Operations learning should show workflows such as trade support, reconciliation, and controls; deal training uses different modelling and advisory skills. Centaur Careers teaches operations within the Financial Operations Masterclass, available live online from Hyderabad. Choose from the duties in current postings.' }),
      Object.freeze({ question: 'Do investment banking classes in Hyderabad require a local venue?', answer: 'Ask the provider whether the current cohort meets at a verified Hyderabad venue or live online. Centaur Careers lists live online access from Hyderabad and an in-person option in Lucknow, with no Hyderabad classroom listed.' }),
      Object.freeze({ question: 'How do I evaluate an investment banking institute in Hyderabad?', answer: 'Verify the provider, instructor, dated syllabus, practical exercise, assessment, fees, credential issuer, and refund terms. Check the address if classroom attendance matters. A city keyword alone does not confirm a venue.' }),
      Object.freeze({ question: 'What should a finance operations course in Hyderabad help me practise?', answer: 'Start with the duties in current Hyderabad postings: onboarding checks, KYC case records, payment exceptions, reconciliation, lending support, or controls. Compare the actual tasks, tools, shift, and office area before deciding which exercises are relevant.' }),
      Object.freeze({ question: 'Is there a separate KYC AML course in Hyderabad through Centaur Careers?', answer: 'No. KYC and AML is a module within the Financial Operations Masterclass, not a separate Hyderabad offering. Ask how the current cohort teaches due diligence, documentation, monitoring, and escalation.' }),
      Object.freeze({ question: 'Does a finance course with placement assistance in Hyderabad promise a local job?', answer: 'This guide promises no Hyderabad-specific vacancy or job location. Review the current Placements page and written program terms for the scope and conditions of Centaur Careers’ job guarantee, and ask about location expectations.' }),
      Object.freeze({ question: 'Which is the best investment banking course in Hyderabad for my goal?', answer: 'There is no single best option for every role. Match the syllabus, exercises, teaching format, feedback, cost, and written support terms to the workflow in current employer postings, whether in Gachibowli, the Financial District, or another area.' }),
    ]),
    evidence: Object.freeze([
      Object.freeze({ label: 'Government of Telangana, Information Technology, Electronics & Communications', href: 'https://www.telangana.gov.in/departments/information-technology-electronics-and-communications/', note: 'Official department overview of the state’s IT and electronics remit, policy, investment, and skills priorities.' }),
      Object.freeze({ label: 'Telangana’s Second ICT Policy 2021', href: 'https://invest.telangana.gov.in/wp-content/uploads/2024/07/Telanganas-2nd-ICT-Policy-2021-1.pdf', note: 'Dated state policy describing Hyderabad’s IT/ITeS and related business-services context; policy statements are not current vacancy counts.' }),
    ]),
  }),
]);

// Local expansion is deliberately selective. A market can enter the public
// regional cluster only after it has distinct evidence and a truthful access
// explanation; a keyword alone never creates a city page.
export const REGIONAL_EXPANSION_POLICY = Object.freeze({
  publishedGuideLimit: 5,
  selectionRule: 'Publish a regional guide only when unique public market evidence, role context, and a learner-access boundary have been reviewed.',
  accessBoundary: 'Confirm current cohort access and delivery directly; the published in-person learning location is in Lucknow.',
  localScopeRule: 'Every published regional guide must expose exact market areas and explain that they are job-research filters, not Centaur Careers facilities.',
});

export const REGIONAL_EXPANSION_QUEUE = Object.freeze([
  ...REGIONAL_PAGES.map((page) => Object.freeze({
    id: page.id,
    routeId: page.routeId,
    path: page.path,
    regionName: page.regionName,
    primaryKeyword: page.primaryKeyword,
    status: 'published',
  })),
]);

export function getRegionalPage(id) {
  return REGIONAL_PAGES.find((page) => page.id === id) || null;
}
