import { BLOG_BLOCK_TYPES } from './blog/blogSchema.js';
import { PRIORITY_RESOURCES } from './prioritySeoContent.js';

const RESOURCE_AUTHOR = Object.freeze({
  id: 'bharat-singh',
  name: 'Bharat Singh',
  role: 'Founder & Director',
  profilePath: '/about/',
});

const RESOURCE_PUBLISHER = Object.freeze({
  id: 'centaur-careers',
  type: 'Organization',
  name: 'Centaur Careers',
  role: 'Publisher',
  profilePath: '/',
});

const RESOURCE_DATE = '2026-09-13';

function paragraph(text) {
  return { type: BLOG_BLOCK_TYPES.PARAGRAPH, text };
}

function heading(text, level = 2) {
  return { type: BLOG_BLOCK_TYPES.HEADING, level, text };
}

function list(items, ordered = false) {
  return { type: BLOG_BLOCK_TYPES.LIST, ordered, items };
}

function link(label, href, routeId) {
  return { type: BLOG_BLOCK_TYPES.LINK, label, href, routeId };
}

function faq(question, answer) {
  return { type: BLOG_BLOCK_TYPES.FAQ, question, answer };
}

const RESOURCE_DEPTH_ADDITIONS = Object.freeze({
  'reconciliation-in-finance': [
    heading('How to classify a reconciliation break'),
    paragraph('Classification helps a team choose the next action; it is not a substitute for evidence. A timing difference may clear when the next file or statement arrives. A missing or duplicate item may need source-system investigation. An amount, date, identifier, or status variance may require the responsible team to confirm which record is authoritative. An unresolved item should retain its ageing, owner, risk, and escalation path until the explanation is verified.'),
    list([
      'Timing: the event is expected but appears in different periods or processing windows.',
      'Missing: one side has no corresponding record and the delivery or source needs checking.',
      'Duplicate: two records appear to represent the same event and require controlled review.',
      'Reference mismatch: the amount may agree but the identifier, account, or status does not.',
      'Amount or currency variance: the values differ and the source, rate, fee, or adjustment must be evidenced.',
      'Unresolved: available evidence is insufficient and the item must remain visible and escalated.',
    ]),
    heading('A reviewer-friendly reconciliation note'),
    paragraph('A reviewer should be able to follow the conclusion without asking the preparer to recreate the investigation. Include the scope, control total, records compared, first difference found, evidence checked, classification, materiality or deadline, owner, expected action, and closure test. Avoid writing only "investigated" or "fixed". State what changed, who approved it, and how the next output was checked.'),
    heading('Practice exercise using fictional data'),
    paragraph('Create two small tables with transaction ID, value date, currency, amount, account, and status. Introduce one timing difference, one duplicate, one missing item, and one amount variance. Apply a documented matching rule, build an ageing list, and write one escalation for each unresolved case. This exercise demonstrates the analyst\'s reasoning without exposing real customer, employer, or account data.'),
    heading('What a strong reconciliation control protects'),
    list([
      'Accurate balances, positions, and operational status.',
      'Timely detection of missing, duplicate, or incorrect records.',
      'Evidence for reviewers, audit, and authorised corrections.',
      'Clear ownership across upstream and downstream teams.',
      'Reliable reporting and reduced repeat exceptions.',
    ]),
    faq('Can a reconciliation analyst close a break without an approval?', 'Only where the organisation\'s approved procedure gives that authority. Otherwise the analyst should document the evidence, route the item to the responsible owner or approver, and verify the result after the authorised action.'),
  ],
});

export const RESOURCES = Object.freeze([
  Object.freeze({
    id: 'investment-banking-interview-questions',
    routeId: 'resource-investment-banking-interview-questions',
    path: '/resources/investment-banking-interview-questions/',
    keywordOwnerUrl: '/resources/investment-banking-interview-questions/',
    kind: 'interview-preparation',
    label: 'Interview preparation resource',
    title: 'Investment Banking Interview Questions | Centaur Careers',
    description: 'Practise investment banking operations interview questions for freshers covering trade lifecycle, settlement, reconciliation, and common operations scenarios.',
    h1: 'Investment Banking Operations Interview Questions for Freshers',
    breadcrumbLabel: 'Investment Banking Interview Questions',
    primaryKeyword: 'investment banking operations interview questions for freshers',
    secondaryKeywords: Object.freeze([
      'investment banking operations interview preparation',
      'investment banking operations mock interview',
      'trade lifecycle interview questions for freshers',
      'settlement interview questions banking',
      'reconciliation interview questions finance',
      'corporate actions interview questions',
      'finance operations interview questions for freshers',
      'finance interview questions for freshers',
      'finance interview questions and answers',
      'finance resume for freshers',
      'LinkedIn profile for finance freshers',
    ]),
    author: RESOURCE_AUTHOR,
    publishedAt: RESOURCE_DATE,
    updatedAt: '2026-09-26',
    body: Object.freeze([
      paragraph('Investment banking operations interview preparation should combine process knowledge with clear, structured explanations. For a fresher, practise trade capture, confirmation, settlement, reconciliation, corporate actions, exception handling, and escalation, then prepare examples that show accuracy, communication, and calm prioritisation.'),
      paragraph('This resource is for operations and post-trade interviews. A front-office advisory or valuation interview tests a different set of skills; use the job description to choose the right preparation path.'),
      heading('How to use this interview resource'),
      paragraph('Read each question as a prompt to explain a process, not as a definition to memorise. A strong answer usually names the purpose of the activity, places it in the wider workflow, identifies the checks involved, and explains what you would do when the expected information does not match.'),
      list([
        'Begin with the simplest accurate explanation and define specialist terms when you use them.',
        'Use a short workflow or example to show how you would think through the task.',
        'Separate what you know from what you would verify in a procedure, system, or escalation path.',
        'Finish with the control, record, or communication step that prevents the issue from being missed.',
      ]),
      heading('Core investment banking operations questions'),
      faq('What is investment banking operations?', 'Investment banking operations is the process and control work that supports financial transactions after a deal or trade is agreed. It can include trade capture, confirmation, settlement, reconciliation, corporate actions, reporting, and exception management. The exact activities depend on the product, team, market, and employer process.'),
      faq('Can you explain the trade lifecycle?', 'A trade lifecycle commonly moves from execution and trade capture through confirmation or affirmation, clearing, settlement, and post-settlement reconciliation. The operations team checks that the economic details and settlement instructions are complete, monitors status, investigates exceptions, and records the actions needed to complete the process.'),
      faq('What is the difference between trade confirmation and trade settlement?', 'Trade confirmation checks that the parties agree on the transaction details, such as the instrument, quantity, price, date, and parties involved. Settlement is the later exchange of cash and securities or other contractual deliverables. A confirmation issue can prevent a trade from progressing, while a settlement issue appears when delivery or payment is not completed as expected.'),
      faq('What is trade affirmation?', 'Trade affirmation is the agreement or validation of transaction details by the relevant parties before the trade moves through later processing. In an interview, explain that affirmation reduces uncertainty by confirming the data to be used for clearing and settlement. The exact control and platform can vary by market and organisation.'),
      faq('What would you check when a settlement fails?', 'First identify the failed trade, the expected settlement date, the missing or mismatched element, and the latest status. Then check settlement instructions, cash or security availability, matching status, market or counterparty messages, and any documented cut-off or escalation procedure. Record the investigation, communicate clearly, and follow the team process for resolution.'),
      faq('What is reconciliation in finance operations?', 'Reconciliation compares two records that should agree, such as an internal position or cash record and an external statement. The analyst identifies breaks, classifies the likely cause, checks source data and timing, and follows the appropriate resolution or escalation path. The aim is accurate records and visible exceptions, not simply making two numbers look alike.'),
      faq('How would you investigate a reconciliation break?', 'Define the break by account, transaction, value date, currency, and amount, then compare the relevant source records and recent activity. Check timing differences, duplicate entries, missing postings, incorrect static data, and upstream processing status. Preserve an audit trail of the check, owner, next action, and escalation where the break cannot be resolved within the procedure.'),
      faq('What are corporate actions?', 'Corporate actions are events initiated by an issuer that can change a security, its holder entitlement, or the related cash or position records. Examples include dividends, interest payments, splits, rights issues, and mergers. Operations work can include capturing event details, validating elections or entitlements, calculating or checking outputs, and reconciling the result.'),
      faq('What is the difference between middle-office and back-office work?', 'The labels vary between organisations, but middle-office teams often provide controls, trade support, risk or process oversight between execution and settlement, while back-office teams commonly handle confirmation, settlement, reconciliation, and records. A good interview answer acknowledges that responsibilities differ by organisation and then focuses on the workflow and control assigned to the role.'),
      faq('How are KYC and AML relevant to operations roles?', 'KYC and AML processes help organisations understand customers, review risk, monitor activity, and escalate cases under their applicable procedures. An operations candidate should show careful document handling, consistent review, clear case notes, and disciplined escalation. Avoid presenting a general interview answer as legal or regulatory advice because requirements depend on the employer and jurisdiction.'),
      heading('Behavioural and scenario questions'),
      faq('Tell me about a time you found an error in a process.', 'Use a real academic, project, internship, or work example. Explain the expected result, how you noticed the difference, the checks you performed, who you informed, and what changed afterwards. Keep the focus on accuracy and learning. Do not claim ownership of systems, controls, or outcomes that you did not actually handle.'),
      faq('How would you prioritise several operations exceptions?', 'Start with deadlines, financial or client impact, ageing, dependencies, and the team procedure for escalation. Address time-sensitive items first while keeping a visible queue for the remaining work. Communicate a realistic status, ask for help when priorities conflict, and document the reasoning so the handover is clear.'),
      faq('What would you do if you did not know the answer in an interview?', 'Be honest about the boundary of your knowledge, explain the related concept you do understand, and describe how you would verify the answer using the approved procedure, system record, or experienced team member. This demonstrates judgement and control awareness. Guessing a transaction detail can be less useful than showing a safe method of verification.'),
      faq('How should a fresher answer a technical question?', 'Use a simple structure: define the activity, place it in the lifecycle, name two or three checks, and explain the exception or escalation step. If the question covers a product or market you have not studied, state the assumption and explain the general process before identifying what would need confirmation.'),
      heading('Sample answer: a settlement record does not match'),
      paragraph('A concise answer could be: "I would identify the trade and expected settlement date, compare the security, quantity, cash amount, counterparty, and instructions in the relevant records, and check whether the difference is a timing or data issue. I would record what I found, follow the team procedure for correction or escalation, and confirm the final status." This is a practice framework, not a universal employer procedure. Do not claim you have performed this work unless you have.'),
      heading('Self-check your exception answer'),
      paragraph('Try this fictional prompt aloud: an internal trade record shows 100 shares for settlement tomorrow, while the counterparty confirmation shows 10. Score one point for each check you explain clearly. This is a practice rubric, not an employer assessment.'),
      list([
        'Identify the trade, security, settlement date, and the exact quantity difference before proposing an action.',
        'Compare both original records and relevant trade identifiers; do not assume which record is correct.',
        'Check the approved source or confirmation workflow and state what information remains uncertain.',
        'Record the break, owner, deadline, and evidence, then escalate under the team procedure before the cut-off.',
        'Explain that only an authorised correction with an audit trail can resolve the mismatch, followed by a status check.',
      ], true),
      heading('Finance interview questions for freshers'),
      paragraph('Finance interviews can test basic accounting and banking concepts, role-specific workflows, communication, and how a candidate handles an unfamiliar scenario. First read the job description: an operations role, an analyst role, and a customer-facing role may test different knowledge. Keep answers tied to what you have actually studied or done.'),
      faq('How should a fresher prepare for finance interview questions and answers?', 'Review the role description, revise relevant finance and accounting foundations, and practise explaining one or two workflows in plain language. For scenario questions, state the facts, checks, assumptions, and next step; do not invent work experience or claim authority you did not have.'),
      faq('What should I say in a finance interview if I do not know an answer?', 'Be direct about what you do not know, explain any related concept you understand, and describe how you would verify the answer using an approved source, procedure, or experienced colleague. This is safer and more credible than guessing a regulatory or transaction detail.'),
      heading('Interview preparation checklist'),
      list([
        'Revise trade capture, confirmation, affirmation, clearing, settlement, reconciliation, corporate actions, and exception management.',
        'Prepare one accurate example that demonstrates attention to detail and one that demonstrates teamwork or communication.',
        'Practise explaining a workflow aloud in under two minutes before adding deeper detail.',
        'Review the employer job description and identify the products, systems, controls, and communication skills it actually names.',
        'Keep a short list of questions about the team, training, role scope, shift expectations, assessment process, and next steps.',
      ], true),
      heading('Finance fresher resume and LinkedIn preparation'),
      paragraph('Your resume and LinkedIn profile should make the relevant evidence easy to find. Describe projects, coursework, internships, spreadsheets, process exercises, communication, and problem-solving with truthful detail. Use role language only when it accurately describes what you studied or performed; keywords cannot replace evidence in an interview.'),
      list([
        'Lead with a concise summary of the finance operations direction you are exploring.',
        'Show the process, tool, analysis, or outcome for each relevant project instead of listing only a subject name.',
        'Keep dates, education, contact details, and role descriptions consistent across your resume and LinkedIn profile.',
        'Proofread names, numbers, formatting, and attachments before submitting an application.',
      ]),
      heading('Practise with the right learning context'),
      paragraph('The Financial Operations Masterclass covers finance operations topics such as investment banking operations, KYC and AML, digital payments, retail banking, and related BFSI processes. Review the current curriculum and support terms to understand how interview preparation fits within the provider-specific program, rather than treating this resource as a promise about any particular employer process.'),
      link('Review the Investment Banking Operations module', '/courses/investment-banking-operations/', 'investment-banking-operations'),
      link('Explore the Financial Operations Masterclass', '/courses/', 'courses'),
      link('Read the trade lifecycle career guide', '/career-guides/trade-lifecycle/', 'career-guide-trade-lifecycle'),
      link('Read the KYC and AML analyst career guide', '/career-guides/kyc-aml-analyst/', 'career-guide-kyc-aml-analyst'),
      heading('Questions to ask before choosing interview support'),
      paragraph('Before joining any course or preparation service, ask what is taught, how practice is reviewed, how current role requirements are handled, and which support terms are available in writing. Confirm the current details directly with the provider and compare them with the role requirements you want to pursue.'),
      link('Read the program FAQs', '/faqs/', 'faqs'),
      link('Review the 100% Job Guarantee Program', '/placements/', 'placements'),
      link('Contact Centaur Careers', '/contact/', 'contact'),
    ]),
    relatedRouteIds: Object.freeze([
      'courses',
      'investment-banking-operations',
      'career-guide-trade-lifecycle',
      'career-guide-kyc-aml-analyst',
      'faqs',
      'placements',
      'contact',
    ]),
    seo: Object.freeze({
      title: 'Investment Banking Interview Questions | Centaur Careers',
      description: 'Practise investment banking operations interview questions for freshers covering trade lifecycle, settlement, reconciliation, and common operations scenarios.',
    }),
  }),
  Object.freeze({
    id: 'accounting-interview-questions',
    routeId: 'resource-accounting-interview-questions',
    path: '/resources/accounting-interview-questions/',
    keywordOwnerUrl: null,
    kind: 'interview-preparation',
    label: 'Technical accounting interview practice',
    title: 'Accounting Interview Questions and Answers | Centaur Careers',
    description: 'Practise accounting interview questions with a fictional journal-entry case, trial balance, bank break, answer key, and self-check rubric.',
    h1: 'Accounting Interview Questions and Answers: A Worked Operations Case',
    breadcrumbLabel: 'Accounting Interview Questions',
    primaryKeyword: 'accounting interview questions and answers',
    secondaryKeywords: Object.freeze(['basic accounting interview questions', 'accounting interview questions for finance operations']),
    author: RESOURCE_PUBLISHER,
    publishedAt: '2026-09-26',
    updatedAt: '2026-09-26',
    body: Object.freeze([
      paragraph('Basic accounting interview questions test whether you can explain what a transaction changes, record both sides correctly, trace the result into statements, and investigate a mismatch. This practice page gives worked answers for entry-level accounting and finance operations roles. Its fictional case is a learning exercise, not a record from an employer or a prediction of interview questions.'),
      heading('How to answer a technical accounting question'),
      paragraph('Start with the economic event, name the accounts affected, state the debit and credit, then explain the resulting balance and the evidence you would check. If a fact is missing, say which document or policy you would inspect before deciding. A balanced entry is a necessary arithmetic check, but it does not prove the account, date, or treatment is correct.'),
      heading('Basic accounting interview questions and short answers'),
      faq('What is the accounting equation?', 'Assets = Liabilities + Equity. It describes the relationship between what an entity controls and the claims on those resources. Income and expenses affect equity through the period’s result; in a real interview, explain the transaction rather than reciting only the formula.'),
      faq('What does double-entry bookkeeping mean?', 'A transaction affects at least two accounts so that total debits equal total credits for the entry. The debit and credit depend on the account types and the actual event. For example, a cash contribution by an owner increases Bank (debit) and Capital (credit).'),
      faq('Is a debit always money received?', 'No. Debit and credit are accounting sides, not synonyms for cash in and cash out. A debit can increase an asset or expense; a credit can increase a liability, equity, or income. Identify the account and its change before choosing the side.'),
      faq('When a customer is invoiced, is cash already received?', 'Usually not in an ordinary credit-sale example. A valid invoice for services already provided creates a receivable and revenue in this simplified exercise; Bank changes only when the customer pays. Real revenue recognition and tax treatment depend on the contract and applicable policies.'),
      faq('What does a trial balance prove?', 'Equal debit and credit totals show that the ledger balances are arithmetically in balance. They do not prove that every transaction was captured, entered in the correct account, supported by evidence, or recorded in the right period.'),
      faq('How do profit and the balance sheet connect?', 'In the simplified case below, service revenue less rent and bank charges gives the period’s profit. That result increases closing equity. The balance sheet then shows Bank plus Receivables equal to Capital plus retained profit, assuming no other transactions or drawings.'),
      faq('What do you do if the bank statement and cash book differ?', 'First confirm the account, cut-off date, opening position, transaction references, and amounts. Separate timing items from missing or incorrect entries, retain the source evidence, and follow the authorised posting or escalation procedure. Never edit a source record only to force a match.'),
      heading('Try a complete fictional transaction exercise'),
      paragraph('The case below uses one small service business, four source events, and a bank fee discovered at period end. Work through the entries and balances before reading the answer key. Taxes, opening balances, depreciation, drawings, and other transactions are excluded to keep the arithmetic inspectable.'),
    ]),
    caseStudy: Object.freeze({
      name: 'Aster Services: five-step accounting interview case',
      sourceEvents: Object.freeze([
        Object.freeze({ id: '1', event: 'Owner pays ₹20,000 into the business bank account.', amount: 20000, debit: 'Bank', credit: 'Capital' }),
        Object.freeze({ id: '2', event: 'Business pays ₹3,000 rent from the bank account.', amount: 3000, debit: 'Rent expense', credit: 'Bank' }),
        Object.freeze({ id: '3', event: 'Business invoices a customer ₹7,000 for services already provided; payment is due later.', amount: 7000, debit: 'Trade receivables', credit: 'Service revenue' }),
        Object.freeze({ id: '4', event: 'Customer pays ₹5,000 against that invoice into the bank account.', amount: 5000, debit: 'Bank', credit: 'Trade receivables' }),
      ]),
      bankFee: Object.freeze({ event: 'At the same cut-off, the bank statement shows a ₹200 service fee absent from the cash book.', amount: 200, debit: 'Bank charges expense', credit: 'Bank' }),
      closingBalances: Object.freeze([
        Object.freeze({ account: 'Bank', debit: 21800, credit: 0 }),
        Object.freeze({ account: 'Trade receivables', debit: 2000, credit: 0 }),
        Object.freeze({ account: 'Rent expense', debit: 3000, credit: 0 }),
        Object.freeze({ account: 'Bank charges expense', debit: 200, credit: 0 }),
        Object.freeze({ account: 'Capital', debit: 0, credit: 20000 }),
        Object.freeze({ account: 'Service revenue', debit: 0, credit: 7000 }),
      ]),
      profit: 3800,
      closingAssets: 23800,
      rubric: Object.freeze([
        'Identify the event and evidence before naming accounts.',
        'Choose the correct debit and credit for each event.',
        'Show a balanced ₹27,000 trial balance after the fee.',
        'Explain ₹3,800 profit and ₹23,800 closing assets/equity.',
        'Investigate the bank difference and request an authorised fee posting; retain an audit trail.',
      ]),
    }),
    relatedRouteIds: Object.freeze(['resources', 'resource-accounting-basics', 'resource-reconciliation-in-finance', 'career-guide-finance-operations', 'courses']),
    seo: Object.freeze({
      title: 'Accounting Interview Questions and Answers | Centaur Careers',
      description: 'Practise accounting interview questions with a fictional journal-entry case, trial balance, bank break, answer key, and self-check rubric.',
    }),
  }),
  Object.freeze({
    id: 'finance-gk',
    routeId: 'resource-finance-gk',
    path: '/resources/finance-gk/',
    keywordOwnerUrl: null,
    kind: 'learning',
    label: 'Finance & BFSI learning resource',
    title: 'Finance and BFSI Basics for Beginners | Centaur Careers',
    description: 'Learn finance and BFSI basics through clear concepts and short quizzes for learners exploring banking, payments, securities and finance operations careers.',
    h1: 'Finance & BFSI Basics: Learn Key Concepts and Test Your Knowledge',
    breadcrumbLabel: 'Finance & BFSI Basics',
    primaryKeyword: 'finance and BFSI concepts for beginners',
    secondaryKeywords: Object.freeze([
      'finance GK quiz for freshers',
      'Indian financial system basics',
      'banking awareness for finance operations',
      'BFSI concepts for beginners',
      'finance interview preparation basics',
    ]),
    author: RESOURCE_AUTHOR,
    publishedAt: '2026-09-17',
    updatedAt: '2026-09-27',
    body: Object.freeze([
      paragraph('This learning hub introduces finance and BFSI ideas that are useful context for people exploring entry-level banking, digital payments, securities-market, and finance-operations roles in India. It is designed for learners who want to understand the terms and workflows before an interview or course—not as a complete competitive-exam syllabus, investment recommendation, or promise of employment.'),
      heading('Who this learning resource is for'),
      paragraph('Use it if you are a student, graduate, or early-career learner building a foundation in financial services. You can read one concept at a time, answer the short quiz, and follow the linked career guides for a deeper view of what operations work can involve. The explanations are introductory; actual responsibilities, systems, and controls vary by organisation, product, and market.'),
      heading('A simple map of finance and BFSI'),
      paragraph('BFSI stands for banking, financial services, and insurance. This resource focuses on the banking, payment, securities, and operations concepts most relevant to Centaur Careers’ finance-career learning topics. A useful first step is to distinguish the organisations and activities involved: a payment system moves funds between participants; a securities market supports the issuance or trading of securities; and operations teams help process, check, reconcile, and resolve transactions according to their organisation’s procedures.'),
      heading('Concept 1: Primary and secondary securities markets'),
      paragraph('The primary market is where new securities are offered by an issuer. In the secondary market, investors trade securities that have already been issued. For a learner, the key distinction is whether the security is being issued for the first time or changing hands after issuance. SEBI’s investor-education material explains the difference and gives examples.'),
      link('Read SEBI Investor’s explanation of the securities market', 'https://investor.sebi.gov.in/securities-stockmarket.html'),
      heading('Concept 2: UPI, NEFT, and RTGS are not the same thing'),
      paragraph('UPI is an instant payment system developed by NPCI. RBI’s consumer FAQ describes NEFT as processing received transactions in batches, while RTGS processes transactions continuously on a transaction-by-transaction basis. These are useful high-level distinctions; for an actual payment, customer support issue, cut-off, eligibility question, or operating procedure, consult the relevant bank and the latest official guidance.'),
      link('Read NPCI’s UPI product overview', 'https://www.npci.org.in/product/upi'),
      link('Read RBI’s NEFT and RTGS FAQs', 'https://www.rbi.org.in/scripts/FS_FAQs.aspx?Id=65'),
      heading('Concept 3: Reconciliation and exceptions in operations'),
      paragraph('A reconciliation compares records that are expected to agree—for example, a transaction or balance in one record against the corresponding record from another source. A break is a difference that needs investigation, not a value to change just to make the records match. A careful learner should check identifiers, dates, amounts, status, timing, and source records; document what was checked; and use the relevant team procedure to resolve or escalate an unexplained difference.'),
      paragraph('This is an introductory learning example rather than a universal control procedure. Employers define their own systems, control steps, evidence requirements, and escalation paths.'),
      heading('A repeatable method for learning a finance workflow'),
      list([
        'Define the term in plain language and expand any acronym the first time you use it.',
        'Place the activity in its workflow: what happens before it, and what should happen after it?',
        'Name the records, parties, dates, or statuses that a learner would need to understand.',
        'Ask what can go wrong, what evidence helps identify the cause, and which procedure governs the next step.',
        'Explain the concept in your own words, then check it against an authoritative source or the relevant employer procedure.',
      ], true),
      heading('Mini quiz: check your understanding'),
      faq('A company offers a new issue of shares to investors. Is this the primary or secondary market?', 'Answer: the primary market. It concerns new securities being issued. A trade between investors in securities that have already been issued is an example of secondary-market activity. See SEBI Investor’s explanation linked above.'),
      faq('Which system is described by RBI as processing transactions received up to a particular time in batches: NEFT or RTGS?', 'Answer: NEFT. RBI contrasts this with RTGS, where transactions are processed continuously on a transaction-by-transaction basis. This is a conceptual distinction; check RBI and your bank for current operational details.'),
      faq("Who developed UPI, according to NPCI's product overview?", 'Answer: the National Payments Corporation of India (NPCI). NPCI describes UPI as an instant payment system. Follow NPCI’s product page linked above for its official overview.'),
      faq('Two records for a transaction do not agree. Should an analyst simply edit one so the numbers match?', 'Answer: no. First establish which records and transaction are being compared, check timing and source details, identify and document the break, then follow the organisation’s approved resolution or escalation procedure. The control trail matters as much as the final status.'),
      heading('Keep learning with related guides'),
      paragraph('For deeper role context, continue with these Centaur Careers resources. Review the current program page separately for provider-specific curriculum, delivery modes, fees, and support terms; those details can change and should not be inferred from a general learning resource.'),
      link('Explore the Financial Operations Masterclass', '/courses/', 'courses'),
      link('Understand finance operations roles', '/career-guides/finance-operations/', 'career-guide-finance-operations'),
      link('Learn about digital payments operations', '/career-guides/digital-payments-operations/', 'career-guide-digital-payments-operations'),
      link('Explore the trade lifecycle', '/career-guides/trade-lifecycle/', 'career-guide-trade-lifecycle'),
      link('Understand financial products and banking services', '/blog/financial-products-and-services-banking/'),
      link('Map financial market intermediaries and their roles', '/blog/financial-market-intermediaries/'),
      link('Practise investment banking operations interview questions', '/resources/investment-banking-interview-questions/', 'resource-investment-banking-interview-questions'),
      heading('Official sources and learning note'),
      paragraph('The definitions and distinctions above are based on the official educational references linked on this page from SEBI Investor, NPCI, and the Reserve Bank of India. Regulations and operating arrangements may be updated, so use the current primary source and applicable organisation procedure for decisions. This page is general educational material, not investment, legal, or compliance advice.'),
      link('Browse SEBI Investor’s official reading material', 'https://investor.sebi.gov.in/iematerial.html'),
    ]),
    relatedRouteIds: Object.freeze([
      'courses',
      'career-guide-finance-operations',
      'career-guide-digital-payments-operations',
      'career-guide-trade-lifecycle',
      'resource-investment-banking-interview-questions',
    ]),
    seo: Object.freeze({
      title: 'Finance and BFSI Basics for Beginners | Centaur Careers',
      description: 'Learn finance and BFSI basics through clear concepts and short quizzes for learners exploring banking, payments, securities and finance operations careers.',
    }),
  }),
  Object.freeze({
    id: 'accounting-basics',
    routeId: 'resource-accounting-basics',
    path: '/resources/accounting-basics/',
    keywordOwnerUrl: null,
    kind: 'learning',
    label: 'Accounting foundations',
    title: 'Accounting Basics for Finance Operations | Centaur Careers',
    description: 'Understand accounting principles and standards, debit and credit, the journal-to-ledger and trial-balance sequence, golden rules, and simple examples.',
    h1: 'Accounting Basics for Finance Operations: Debit, Credit and Records',
    breadcrumbLabel: 'Accounting Basics',
    primaryKeyword: 'accounting basics for finance operations',
    secondaryKeywords: Object.freeze([
      'accounting rules',
      'accounting principles',
      'general accounting principles',
      'basic accounting principles',
      'debit and credit accounting basics',
      'financial accounting basics',
      'accounting standards in India',
      'journal ledger and trial balance',
      'carriage inward and carriage outward',
    ]),
    author: RESOURCE_AUTHOR,
    publishedAt: '2026-09-17',
    updatedAt: '2026-09-24',
    body: Object.freeze([
      paragraph('The golden rules of accounting are a traditional way to remember how debits and credits are recorded for personal, real, and nominal accounts. They are a useful starting point for learners, but they do not replace an organisation’s accounting policies, chart of accounts, or professional guidance.'),
      heading('What accounting helps an organisation do'),
      paragraph('Accounting provides a structured record of financial transactions so that an organisation can prepare reports, review balances, and explain how amounts changed. A transaction should be supported by appropriate source information, recorded consistently, and checked under the relevant process. For finance and BFSI learners, understanding the logic behind an entry is more useful than memorising labels without context.'),
      heading('Debit and credit: the foundation'),
      paragraph('In double-entry bookkeeping, a transaction is recorded in at least two accounts, with total debits equal to total credits for the entry. Debit and credit describe the two sides of an accounting record; by themselves, they do not mean “good” and “bad,” or “money in” and “money out.” The effect depends on the account type and the accounting framework being used.'),
      paragraph('A basic accounting equation is: Assets = Liabilities + Equity. Recording a transaction should preserve the relationship between the organisation’s resources and the claims against those resources. Actual reporting rules and account treatment depend on the entity and applicable standards.'),
      heading('The three traditional golden rules'),
      list([
        'Personal accounts: debit the receiver and credit the giver. This is a traditional rule for accounts associated with people or organisations.',
        'Real accounts: debit what comes in and credit what goes out. Real accounts are traditionally associated with assets or property.',
        'Nominal accounts: debit expenses and losses; credit incomes and gains. These accounts collect income and expense activity for a period.',
      ]),
      paragraph('These rules are commonly taught as introductory memory aids. Modern accounting systems often present transactions through account codes and debit/credit conventions, so learners should also understand the specific account and transaction rather than rely only on a mnemonic.'),
      heading('Simple example: paying office rent in cash'),
      paragraph('Suppose a business pays ₹1,000 of rent from its cash balance. In a simplified journal entry, Rent Expense is debited by ₹1,000 and Cash is credited by ₹1,000. The rent expense increases, while the cash asset decreases. Both sides are equal, and the entry should be supported by the appropriate payment evidence and recorded in the correct period.'),
      heading('A practical sequence for recording a transaction'),
      list([
        'Read the source document and identify what actually happened, when it happened, and which entity is involved.',
        'Identify the accounts affected and classify their purpose; do not choose an account just because its name sounds similar.',
        'Determine whether each account increases or decreases under the applicable accounting convention.',
        'Record the debit and credit with clear narration, date, amount, and reference to the supporting document.',
        'Review the entry and related balances through the organisation’s approved checks; investigate errors rather than changing a record merely to force a balance.',
      ], true),
      heading('Common beginner mistakes'),
      list([
        'Assuming every debit is a loss or every credit is a gain.',
        'Recording a transaction without understanding which accounts it affects.',
        'Treating a balanced journal entry as proof that the transaction is correct; balanced entries can still use the wrong account or period.',
        'Changing source records without authority or leaving no audit trail for a correction.',
      ]),
      heading('Accounting principles and accounting standards'),
      paragraph('Accounting principles are broad ideas used to organise and explain financial records. Accounting standards are formal requirements issued or adopted under an applicable reporting framework. Which standards apply depends on the entity, jurisdiction, and reporting context; an introductory summary should not be used to decide compliance. The Institute of Chartered Accountants of India’s Accounting Standards Board develops and supports accounting standards in India.'),
      link('Visit ICAI’s Accounting Standards Board', 'https://asb.icai.org/'),
      heading('From journal entries to ledger and trial balance'),
      paragraph('In a basic bookkeeping sequence, transactions are first recorded in a journal or relevant subsidiary book, then posted to the affected ledger accounts. The ledger balances can be summarised in a trial balance and used in preparing financial statements. A trial balance with equal debit and credit totals is a useful arithmetic check, but it does not prove that every transaction was recorded or classified correctly.'),
      heading('Carriage inward and carriage outward'),
      paragraph('In traditional final-accounts examples, carriage inward is the transport cost of bringing purchased goods to the business; it is commonly treated as a direct purchase-related cost. Carriage outward is the cost of delivering sold goods to customers and is commonly shown as a selling or distribution expense. These labels and their presentation depend on the transaction and applicable reporting framework, so use the entity’s accounting policy for real records.'),
      link('Read NCERT material on final accounts and carriage outward', 'https://www.ncert.nic.in/textbook/pdf/leac204.pdf'),
      heading('Mini quiz'),
      faq('Do debit and credit always mean cash out and cash in?', 'No. They are the two sides of an accounting entry. Their effect depends on the account type and the applicable accounting convention.'),
      faq('Under the traditional nominal-account rule, where is an expense recorded?', 'It is debited. The complete entry still depends on the other account affected by the transaction.'),
      faq('In traditional final accounts, is carriage inward or outward debit or credit?', 'Both are generally shown as debit-side costs in traditional final-account examples: carriage inward is a purchase-related direct cost, while carriage outward is a selling or distribution cost. The ledger account and presentation depend on the entity’s chart of accounts, transaction, and applicable framework.'),
      faq('Is carriage inward a purchase return?', 'No. Carriage inward is the cost of bringing purchased goods to the business. A purchase return is goods returned to a supplier; it is a different transaction and should be recorded separately.'),
      faq('How might carriage appear in a traditional trial balance?', 'Carriage inward and carriage outward commonly have debit balances when recorded as expenses in traditional bookkeeping exercises. The actual balance shown depends on the entries and adjustments posted; use the supporting records and applicable accounting policy.'),
      faq('If total debits equal total credits, does that prove the entry is correct?', 'No. The entry may still use the wrong account, date, amount, or supporting reference. Additional review and controls are needed.'),
      heading('Continue with finance operations learning'),
      paragraph('Accounting fundamentals support finance operations learning, but day-to-day role procedures vary by employer, product, and system. Use the linked resources to see how accounting basics connect with reconciliation and entry-level operations work.'),
      link('Learn what reconciliation means in finance', '/resources/reconciliation-in-finance/'),
      link('Practise accounting interview questions with a worked answer key', '/resources/accounting-interview-questions/', 'resource-accounting-interview-questions'),
      link('Study core finance and BFSI concepts', '/resources/finance-gk/'),
      link('Practise finance operations interview questions', '/resources/investment-banking-interview-questions/'),
      link('Read the finance operations career guide', '/career-guides/finance-operations/', 'career-guide-finance-operations'),
      link('Study golden rules with worked entries', '/blog/golden-rules-of-accounting/'),
      heading('Official learning references'),
      paragraph('The linked Institute of Chartered Accountants of India study materials provide formal accounting and bank-reconciliation learning references. This page is an introductory explanation, not accounting, tax, audit, or investment advice; consult the applicable standards, course materials, and professional guidance for real reporting decisions.'),
      link('Browse ICAI study material', 'https://www.icai.org/post/17894'),
      link('Read ICAI introductory accounting-process material', 'https://kb.icai.org/pdfs/PDFFile5b27976545f667.12985834.pdf'),
    ]),
    relatedRouteIds: Object.freeze([
      'resources',
      'resource-finance-gk',
      'resource-reconciliation-in-finance',
      'resource-accounting-interview-questions',
      'resource-investment-banking-interview-questions',
      'career-guide-finance-operations',
      'courses',
    ]),
    seo: Object.freeze({
      title: 'Accounting Basics: Golden Rules | Centaur Careers',
      description: 'Understand accounting principles and standards, debit and credit, the journal-to-ledger and trial-balance sequence, golden rules, and simple examples.',
    }),
  }),
  Object.freeze({
    id: 'reconciliation-in-finance',
    routeId: 'resource-reconciliation-in-finance',
    path: '/resources/reconciliation-in-finance/',
    keywordOwnerUrl: null,
    kind: 'learning',
    label: 'Finance operations workflow guide',
    title: 'Reconciliation in Accounting and Finance | Centaur Careers',
    description: 'Understand reconciliation meaning, finance examples, break investigation, and why differences should be documented instead of forced to match.',
    h1: 'Reconciliation in Finance: Meaning, Process, Types and Examples',
    breadcrumbLabel: 'Reconciliation in Finance',
    primaryKeyword: 'reconciliation meaning',
    secondaryKeywords: Object.freeze([
      'reconciliation',
      'reconciliation meaning in accounting',
      'what is reconciliation',
      'bank reconciliation meaning',
      'reconciliation process in finance',
      'reconciliation process in banking',
      'types of reconciliation in finance',
    ]),
    author: RESOURCE_AUTHOR,
    publishedAt: '2026-09-17',
    updatedAt: '2026-09-26',
    body: Object.freeze([
      paragraph('Reconciliation is the process of comparing two records that should agree, identifying differences, and investigating them through an appropriate control process. It is used in many settings, from a basic bank reconciliation to cash, securities, trade, and ledger checks. The exact records, frequency, ownership, and resolution steps depend on the organisation and activity.'),
      heading('What does reconciliation mean?'),
      paragraph('In plain language, reconciliation asks: do these two records describe the same activity and balance, and if not, why are they different? An analyst matches records using relevant details such as account, transaction reference, currency, date, amount, and status. An unmatched item is a break to investigate; it is not a reason to overwrite a source record or adjust a value simply to make the totals agree.'),
      heading('Examples of reconciliation in finance'),
      list([
        'Bank reconciliation compares an organisation’s cash-book or ledger record with a bank statement and explains timing items, fees, credits, or errors.',
        'Trade or securities reconciliation compares internal transaction, cash, or position records with records from another system or counterparty.',
        'Account reconciliation compares balances or entries in related ledgers, sub-ledgers, clearing accounts, or other approved records.',
        'Payment reconciliation checks whether expected payment instructions, acknowledgements, credits, and settlement records can be matched.',
      ]),
      paragraph('These are examples, not a universal taxonomy. A bank reconciliation is one specific form; the meaning of a break and the permitted correction path depend on the records and procedure involved.'),
      link('Work through a fictional trade settlement break with source records', '/blog/settlement-trade-break-worked-example/'),
      heading('A careful reconciliation workflow'),
      list([
        'Define the scope: accounts or records, reporting period, currency, source systems, and the expected matching basis.',
        'Match items using approved identifiers and tolerances; retain visibility into unmatched and partially matched items.',
        'Classify each break, for example a timing difference, missing entry, duplicate, incorrect reference, amount variance, or unresolved item.',
        'Investigate the source records and relevant event history. Check that the records refer to the same transaction and period before proposing a correction.',
        'Document the evidence, owner, action, ageing, and escalation required by the organisation’s procedure.',
        'Resolve or escalate through the authorised process, then verify the outcome and retain the review trail.',
      ], true),
      heading('Simple bank-reconciliation example'),
      paragraph('A business records a customer payment in its cash book near the end of the day, but the credit appears on the bank statement the next day. The two records differ temporarily because they were updated at different times. The analyst confirms the payment reference and date, records the item as an explained timing difference under the applicable process, and checks that it clears in the next period. A bank fee that appears on the statement but has not yet been recorded in the cash book is a different kind of difference and may require an authorised accounting entry.'),
      heading('Why reconciliation matters in operations jobs'),
      paragraph('Reconciliation work helps teams identify incomplete, duplicated, mistimed, or inconsistent records and keep exceptions visible for review. Entry-level roles may involve matching, queue monitoring, investigating breaks, preparing evidence, communicating with other teams, and escalating items that remain unresolved. Employers use different systems and control procedures, so candidates should explain the reasoning process rather than claim one workflow is universal.'),
      heading('Questions learners often ask'),
      faq('Is reconciliation the same as correcting an account?', 'No. Reconciliation identifies and explains differences between records. A correction, if needed, should follow the authorised process and preserve supporting evidence and approvals.'),
      faq('What is a reconciliation break?', 'It is an unmatched or inconsistent item that needs investigation. The cause may be timing, a missing or duplicate record, a data mismatch, an error, or another issue; it should not be assumed without checking.'),
      faq('What does reconciliation mean in accounting?', 'In accounting, reconciliation means comparing balances or transaction records that should agree, identifying the differences, and investigating them against supporting information. The correction, if any, must follow the entity’s authorised accounting and control process.'),
      faq('What are common types of reconciliation in finance?', 'Examples include bank, account or balance-sheet, intercompany, payment, cash, and trade or securities reconciliation. The names, scope, frequency, and ownership vary by organisation; a specific procedure should define what records are compared and how breaks are handled.'),
      faq('Does every break mean that one record is wrong?', 'No. One record may be updated earlier than another, creating a timing difference. The analyst should validate the facts and follow the applicable procedure before classifying or resolving it.'),
      faq('What skills help with reconciliation work?', 'Careful comparison, attention to detail, spreadsheet and system literacy, clear case notes, prioritisation, and disciplined escalation are useful. The exact tools and responsibilities depend on the role and employer.'),
      heading('Continue learning'),
      paragraph('Reconciliation connects accounting foundations with transaction and trade workflows. Continue with the focused resources below, and review the current course information separately for provider-specific curriculum and support terms.'),
      link('Learn the golden rules of accounting', '/resources/accounting-basics/'),
      link('Apply accounting basics in a worked interview case', '/resources/accounting-interview-questions/', 'resource-accounting-interview-questions'),
      link('Explore finance and BFSI basics', '/resources/finance-gk/'),
      link('Understand the investment banking trade lifecycle', '/career-guides/trade-lifecycle/', 'career-guide-trade-lifecycle'),
      link('Explore finance operations careers', '/career-guides/finance-operations/', 'career-guide-finance-operations'),
      link('Practise finance operations interview questions', '/resources/investment-banking-interview-questions/'),
      heading('References and learning note'),
      paragraph('ICAI’s study material includes bank-reconciliation examples, while regulator and industry guidance describes reconciliation controls in specific contexts. These references support introductory learning only; they do not define a universal employer procedure. Always follow the current policy and authorised systems for real transactions.'),
      link('Read ICAI bank reconciliation study material', 'https://kb.icai.org/pdfs/PDFFile5b27976545f667.12985834.pdf'),
      link('Read RBI guidance on reconciliation controls in banking', 'https://www.rbi.org.in/commonman/english/scripts/Notification.aspx?Id=810'),
      ...(RESOURCE_DEPTH_ADDITIONS['reconciliation-in-finance'] || []),
    ]),
    relatedRouteIds: Object.freeze([
      'resources',
      'resource-finance-gk',
      'resource-accounting-basics',
      'resource-accounting-interview-questions',
      'career-guide-trade-lifecycle',
      'career-guide-finance-operations',
      'resource-investment-banking-interview-questions',
      'courses',
    ]),
    seo: Object.freeze({
      title: 'Reconciliation in Accounting and Finance | Centaur Careers',
      description: 'Understand reconciliation meaning, finance examples, break investigation, and why differences should be documented instead of forced to match.',
    }),
  }),
  ...PRIORITY_RESOURCES,
]);

export const RESOURCE_HUB = Object.freeze({
  id: 'resources',
  path: '/resources/',
  title: 'Finance Career Resources | Centaur Careers',
  description: 'Practical finance-career resources for interview preparation, banking operations workflows, resumes, and informed next steps from Centaur Careers.',
  h1: 'Finance Career Resources',
  breadcrumbLabel: 'Resources',
});

export function getResource(id) {
  return RESOURCES.find((resource) => resource.id === id || resource.routeId === id) || null;
}
