function createRoleIntent({
  id,
  kind,
  label,
  guideId,
  canonicalPath,
  primaryQuestion,
  searchQuestions,
  summary,
  quizDomainId,
  coursePath,
  coursePathLabel = 'Compare the course path',
  articleLinks = [],
}) {
  return Object.freeze({
    id,
    kind,
    label,
    guideId,
    canonicalPath,
    primaryQuestion,
    searchQuestions: Object.freeze(searchQuestions),
    summary,
    quizDomainId,
    coursePath,
    coursePathLabel,
    articleLinks: Object.freeze(articleLinks.map((article) => Object.freeze(article))),
  });
}

// This registry is the source of truth for role-intent ownership. Each entry
// has one canonical answer and a deliberate next step, so similar searches do
// not compete across guides, blogs, quizzes, and course pages.
export const ROLE_INTENTS = Object.freeze([
  createRoleIntent({
    id: 'investment-banking-operations-role',
    kind: 'guide',
    label: 'Investment Banking Operations',
    guideId: 'investment-banking-operations',
    canonicalPath: '/career-guides/investment-banking-operations/',
    primaryQuestion: 'What is investment banking operations?',
    searchQuestions: [
      'What is investment banking operations?',
      'What does an investment banking operations analyst do?',
      'What skills are needed for investment banking operations?',
      'How does the investment banking operations process work?',
    ],
    summary: 'A practical starting point for understanding post-trade processing, settlements, reconciliation, corporate actions, fund accounting, and the skills used in investment banking operations.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [
      { label: 'Trade-break source records and worked answer', path: '/blog/settlement-trade-break-worked-example/' },
      { label: 'Corporate actions analyst career path', path: '/blog/corporate-actions-analyst-career-path/' },
      { label: 'Fund accounting and NAV workflow', path: '/blog/fund-accounting-nav-workflow-career-skills/' },
      { label: 'Financial market intermediaries and workflow', path: '/blog/financial-market-intermediaries/' },
    ],
  }),
  createRoleIntent({
    id: 'kyc-aml-analyst-role',
    kind: 'guide',
    label: 'KYC & AML Analyst',
    guideId: 'kyc-aml-analyst',
    canonicalPath: '/career-guides/kyc-aml-analyst/',
    primaryQuestion: 'What is KYC in banking?',
    searchQuestions: [
      'What is KYC in banking?',
      'What is the difference between KYC and AML?',
      'What does a KYC or AML analyst do?',
      'How can a graduate start a KYC analyst career?',
    ],
    summary: 'A direct explanation of KYC, AML, customer due diligence, screening, transaction monitoring, case writing, and escalation for people exploring compliance operations.',
    quizDomainId: 'financial-crime-compliance',
    coursePath: '/courses/kyc-aml/',
    coursePathLabel: 'Explore the KYC / AML Masterclass module',
    articleLinks: [
      { label: 'KYC onboarding case file and model note', path: '/blog/kyc-onboarding-case-file-example/' },
      { label: 'Financial crime analyst and KYC/AML career guide', path: '/blog/financial-crime-analyst-kyc-aml-career-guide/' },
      { label: 'How to choose a KYC/AML course in India', path: '/blog/how-to-choose-kyc-aml-course-india/' },
    ],
  }),
  createRoleIntent({
    id: 'finance-operations-role',
    kind: 'guide',
    label: 'Finance Operations',
    guideId: 'finance-operations',
    canonicalPath: '/career-guides/finance-operations/',
    primaryQuestion: 'What is a finance operations career?',
    searchQuestions: [
      'What is a finance operations career?',
      'What does a finance operations analyst do?',
      'What skills are needed for finance operations jobs?',
      'How can a graduate prepare for finance operations?',
    ],
    summary: 'A role-level overview of controlled processing, reconciliations, lending and NBFC workflows, reporting, exception handling, and the skills finance operations teams use.',
    quizDomainId: 'accounting-finance-operations',
    coursePath: '/courses/finance-operations/',
    articleLinks: [
      { label: 'Payment reconciliation source records and answer', path: '/blog/payment-reconciliation-process-breaks-controls/' },
      { label: 'Finance operations portfolio projects for freshers', path: '/blog/finance-operations-portfolio-projects-freshers/' },
      { label: 'Loan operations roles, skills, and career path', path: '/blog/loan-operations-banking-roles-skills-career-path/' },
      { label: 'Finance process associate duties and skills', path: '/blog/finance-process-associate-role/' },
      { label: 'Risk management in banking', path: '/blog/risk-management-in-banking/' },
    ],
  }),
  createRoleIntent({
    id: 'trade-lifecycle-role',
    kind: 'guide',
    label: 'Trade Lifecycle',
    guideId: 'trade-lifecycle',
    canonicalPath: '/career-guides/trade-lifecycle/',
    primaryQuestion: 'What is the trade lifecycle in investment banking?',
    searchQuestions: [
      'What is the trade lifecycle in investment banking?',
      'What happens after a trade is executed?',
      'What is the role of settlement and reconciliation in trade operations?',
      'How do trade lifecycle exceptions get resolved?',
    ],
    summary: 'A front-to-back explanation of trade capture, confirmation, clearing, settlement, reconciliation, breaks, and the control mindset needed in post-trade roles.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [
      { label: 'Corporate actions analyst career path', path: '/blog/corporate-actions-analyst-career-path/' },
      { label: 'Fund accounting and NAV workflow', path: '/blog/fund-accounting-nav-workflow-career-skills/' },
      { label: 'Financial market intermediaries and workflow', path: '/blog/financial-market-intermediaries/' },
    ],
  }),
  createRoleIntent({
    id: 'finance-careers-after-graduation-role',
    kind: 'guide',
    label: 'Finance Careers After Graduation',
    guideId: 'finance-careers-after-graduation',
    canonicalPath: '/career-guides/finance-careers-after-graduation/',
    primaryQuestion: 'Which finance career is best after graduation?',
    searchQuestions: [
      'Which finance career is best after graduation?',
      'What finance roles can a BCom graduate explore?',
      'Which finance skills should a fresher learn first?',
      'How should a graduate compare banking and finance career paths?',
    ],
    summary: 'A comparison-first guide for graduates choosing among banking operations, compliance, payments, lending, accounting, and investment-operations directions.',
    quizDomainId: 'banking-career-roles',
    coursePath: '/courses/',
    articleLinks: [
      { label: 'FinTech operations careers after graduation', path: '/blog/fintech-operations-careers-after-graduation/' },
      { label: 'Finance operations portfolio projects for freshers', path: '/blog/finance-operations-portfolio-projects-freshers/' },
    ],
  }),
  createRoleIntent({
    id: 'retail-banking-operations-role',
    kind: 'guide',
    label: 'Retail Banking Operations',
    guideId: 'retail-banking-operations',
    canonicalPath: '/career-guides/retail-banking-operations/',
    primaryQuestion: 'What is retail banking operations?',
    searchQuestions: [
      'What is retail banking operations?',
      'What does a retail banking operations officer do?',
      'What skills are needed for branch and retail banking operations?',
      'How can a fresher start in retail banking operations?',
    ],
    summary: 'A practical guide to customer onboarding, branch operations, deposits, service requests, NRI banking, controls, and customer-facing operations skills.',
    quizDomainId: 'retail-banking-operations',
    coursePath: '/courses/retail-banking/',
    articleLinks: [
      { label: 'Loan-file review packet and answer key', path: '/blog/loan-operations-banking-roles-skills-career-path/' },
      { label: 'Financial products and banking services', path: '/blog/financial-products-and-services-banking/' },
    ],
  }),
  createRoleIntent({
    id: 'digital-payments-operations-role',
    kind: 'guide',
    label: 'Digital Payments Operations',
    guideId: 'digital-payments-operations',
    canonicalPath: '/career-guides/digital-payments-operations/',
    primaryQuestion: 'What is digital payments operations?',
    searchQuestions: [
      'What is digital payments operations?',
      'What does a digital payments operations analyst do?',
      'What skills are needed for UPI and payments operations?',
      'How are payment exceptions and reconciliations handled?',
    ],
    summary: 'An explanation of payment processing, UPI and card workflows, reconciliation, disputes, fraud controls, settlement, and operational investigation.',
    quizDomainId: 'digital-payments-operations',
    coursePath: '/courses/digital-payments/',
    coursePathLabel: 'Explore the Digital Payments Masterclass module',
    articleLinks: [
      { label: 'Card dispute evidence packet and model note', path: '/blog/chargeback-process-evidence-operations/' },
      { label: 'Payment reconciliation worked example', path: '/blog/payment-reconciliation-process-breaks-controls/' },
      { label: 'Digital payments operations careers in India', path: '/blog/digital-payments-operations-career-india/' },
    ],
  }),
  createRoleIntent({
    id: 'financial-operations-faq-role',
    kind: 'guide',
    label: 'Financial Operations FAQs',
    guideId: 'financial-operations-faq',
    canonicalPath: '/career-guides/financial-operations-faq/',
    primaryQuestion: 'Which course is best for investment banking operations in India?',
    searchQuestions: [
      'Which course is best for investment banking operations in India?',
      'What should I learn before applying for finance operations roles?',
      'How do I compare finance operations courses?',
      'What questions should I ask before choosing a banking course?',
    ],
    summary: 'A decision-support page for comparing finance-operations learning options, understanding role fit, and preparing better questions before choosing a course.',
    quizDomainId: 'banking-interview-preparation',
    coursePath: '/courses/',
    articleLinks: [
      { label: 'Investment banking operations versus CFA and financial modelling', path: '/blog/investment-banking-operations-vs-cfa-financial-modelling/' },
      { label: 'How to choose a KYC/AML course in India', path: '/blog/how-to-choose-kyc-aml-course-india/' },
    ],
  }),
  createRoleIntent({
    id: 'finance-course-selection-role',
    kind: 'guide',
    label: 'Choosing a Finance Career Course',
    guideId: 'choosing-finance-career-course',
    canonicalPath: '/career-guides/choosing-finance-career-course/',
    primaryQuestion: 'How should I choose a finance career course after graduation?',
    searchQuestions: [
      'How should I choose a finance career course after graduation?',
      'What should a finance course include for practical job preparation?',
      'How do I compare a finance certificate, MBA, and professional qualification?',
      'What placement-support terms should I check before enrolling?',
    ],
    summary: 'A neutral checklist for comparing course scope, practice, credentials, costs, and provider-published career-support terms.',
    quizDomainId: 'banking-career-roles',
    coursePath: '/courses/',
    articleLinks: [
      { label: 'Compare operations learning with CFA and financial modelling', path: '/blog/investment-banking-operations-vs-cfa-financial-modelling/' },
      { label: 'How to choose a KYC / AML course', path: '/blog/how-to-choose-kyc-aml-course-india/' },
    ],
  }),
  createRoleIntent({
    id: 'fintech-operations-role',
    kind: 'guide',
    label: 'FinTech Operations',
    guideId: 'fintech-operations',
    canonicalPath: '/career-guides/fintech-operations/',
    primaryQuestion: 'How do FinTech operations support digital finance services?',
    searchQuestions: [
      'How do FinTech operations support digital finance services?',
      'How can a commerce graduate explore FinTech operations?',
      'How do digital payments and FinTech operations connect?',
      'Which skills appear in entry-level FinTech operations roles?',
    ],
    summary: 'A practical overview of technology-enabled finance workflows, payments, onboarding, lending operations, compliance support, and graduate preparation.',
    quizDomainId: 'fintech-neo-banking',
    coursePath: '/courses/fintech/',
    coursePathLabel: 'Explore the FinTech Masterclass module',
    articleLinks: [
      { label: 'FinTech operations careers after graduation', path: '/blog/fintech-operations-careers-after-graduation/' },
      { label: 'Digital payments operations career guide', path: '/blog/digital-payments-operations-career-india/' },
    ],
  }),
  createRoleIntent({
    id: 'reconciliation-analyst-role',
    kind: 'guide',
    label: 'Reconciliation Analyst',
    guideId: 'reconciliation-analyst',
    canonicalPath: '/career-guides/reconciliation-analyst/',
    primaryQuestion: 'What does a reconciliation analyst do?',
    searchQuestions: [
      'What does a reconciliation analyst do?',
      'What skills are needed for reconciliation analyst jobs?',
      'How does a reconciliation analyst investigate a break?',
      'Can a fresher become a reconciliation analyst?',
    ],
    summary: 'A practical role path for matching records, investigating breaks, documenting evidence, and escalating controlled finance operations exceptions.',
    quizDomainId: 'accounting-finance-operations',
    coursePath: '/courses/finance-operations/',
    articleLinks: [
      { label: 'Payment reconciliation worked example', path: '/blog/payment-reconciliation-process-breaks-controls/' },
      { label: 'Trade-break source records and answer', path: '/blog/settlement-trade-break-worked-example/' },
      { label: 'Reconciliation and trial-balance workflow', path: '/blog/trial-balance-format-errors-reconciliation/' },
    ],
  }),
  createRoleIntent({
    id: 'investment-banking-operations-roles-role',
    kind: 'guide',
    label: 'Investment Banking Operations Roles',
    guideId: 'investment-banking-operations-roles',
    canonicalPath: '/career-guides/investment-banking-operations-roles/',
    primaryQuestion: 'Which investment banking operations role should I explore?',
    searchQuestions: [
      'Which investment banking operations role should I explore?',
      'What are common investment banking operations roles?',
      'What is the difference between trade support and settlements?',
      'Which investment banking roles can a graduate research?',
    ],
    summary: 'A role-family map for trade support, settlements, reconciliation, corporate actions, fund accounting, and client or compliance operations.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [
      { label: 'Investment banking teams and operations', path: '/blog/investment-banking-teams-operations/' },
      { label: 'Corporate actions analyst career path', path: '/blog/corporate-actions-analyst-career-path/' },
    ],
  }),
  createRoleIntent({
    id: 'trade-support-analyst-role',
    kind: 'guide',
    label: 'Trade Support Analyst',
    guideId: 'trade-support-analyst',
    canonicalPath: '/career-guides/trade-support-analyst/',
    primaryQuestion: 'What does a trade support analyst do?',
    searchQuestions: [
      'What does a trade support analyst do?',
      'What skills are needed for trade support analyst jobs?',
      'How does trade support handle an exception?',
      'What is trade support in investment banking operations?',
    ],
    summary: 'A direct guide to trade capture checks, confirmations, settlement statuses, stakeholder hand-offs, exception notes, and entry-level preparation.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [{ label: 'Settlement trade-break worked example', path: '/blog/settlement-trade-break-worked-example/' }],
  }),
  createRoleIntent({
    id: 'securities-operations-role',
    kind: 'guide',
    label: 'Securities Operations',
    guideId: 'securities-operations',
    canonicalPath: '/career-guides/securities-operations/',
    primaryQuestion: 'What does a securities operations analyst do?',
    searchQuestions: [
      'What does a securities operations analyst do?',
      'What is securities operations?',
      'How do securities operations teams support settlement?',
      'What skills are needed for securities operations jobs?',
    ],
    summary: 'A securities-processing path covering trade records, settlement, custody, positions, income events, reconciliations, and operational controls.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [{ label: 'Financial markets participants and operations', path: '/blog/financial-markets-instruments-participants-operations/' }],
  }),
  createRoleIntent({
    id: 'what-is-investment-banking-role',
    kind: 'guide',
    label: 'Investment Banking Explained',
    guideId: 'what-is-investment-banking',
    canonicalPath: '/career-guides/what-is-investment-banking/',
    primaryQuestion: 'What is investment banking and where do operations roles fit?',
    searchQuestions: [
      'What is investment banking and where do operations roles fit?',
      'What does investment banking mean for a fresher?',
      'What are the main investment banking business lines?',
      'How is investment banking different from investment advice?',
    ],
    summary: 'A plain-language definition of investment banking, its business lines, role families, operations pathway, and learning boundaries.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [{ label: 'Investment banking teams and operations', path: '/blog/investment-banking-teams-operations/' }],
  }),
  createRoleIntent({
    id: 'risk-operations-analyst-role',
    kind: 'guide',
    label: 'Risk Operations Analyst',
    guideId: 'risk-operations-analyst',
    canonicalPath: '/career-guides/risk-operations-analyst/',
    primaryQuestion: 'What does a risk operations analyst do?',
    searchQuestions: [
      'What does a risk operations analyst do?',
      'Which controls does a risk operations analyst monitor?',
      'How can a graduate prepare for risk operations work?',
      'What evidence belongs in an operational risk issue record?',
    ],
    summary: 'A role-level path for incidents, controls, issue records, remediation evidence, reporting, escalation, and responsible graduate preparation.',
    quizDomainId: 'risk-management-operations',
    coursePath: '/courses/finance-operations/',
    coursePathLabel: 'Explore the Finance Operations module',
  }),
  createRoleIntent({
    id: 'credit-analyst-role',
    kind: 'guide',
    label: 'Credit Analyst',
    guideId: 'credit-analyst',
    canonicalPath: '/career-guides/credit-analyst/',
    primaryQuestion: 'What does a credit analyst do?',
    searchQuestions: [
      'What does a credit analyst do?',
      'Which financial and non-financial evidence does a credit analyst review?',
      'How can a fresher practise credit analysis responsibly?',
      'What is the difference between credit analysis and credit operations?',
    ],
    summary: 'A practical overview of financial and business evidence, credit writing, assumptions, role boundaries, and preparation for analyst vacancies.',
    quizDomainId: 'lending-credit-operations',
    coursePath: '/courses/finance-operations/',
    coursePathLabel: 'Explore the Finance Operations module',
  }),
  createRoleIntent({
    id: 'business-analyst-in-banking-role',
    kind: 'guide',
    label: 'Business Analyst in Banking',
    guideId: 'business-analyst-in-banking',
    canonicalPath: '/career-guides/business-analyst-in-banking/',
    primaryQuestion: 'What does a business analyst do in banking?',
    searchQuestions: [
      'What does a business analyst do in banking?',
      'Which requirements and process skills help a banking business analyst?',
      'How is a banking business analyst different from a financial analyst?',
      'What portfolio exercise can demonstrate banking business analysis?',
    ],
    summary: 'A banking-domain path for discovery, process maps, requirements, acceptance criteria, controls, stakeholder decisions, and safe portfolio evidence.',
    quizDomainId: 'banking-career-roles',
    coursePath: '/courses/',
  }),
  createRoleIntent({
    id: 'custody-operations-role',
    kind: 'guide',
    label: 'Custody Operations',
    guideId: 'custody-operations',
    canonicalPath: '/career-guides/custody-operations/',
    primaryQuestion: 'What does a custody operations analyst do?',
    searchQuestions: [
      'What does a custody operations analyst do?',
      'How do custody teams maintain cash and securities records?',
      'Which skills support custody banking operations?',
      'How do settlement and asset servicing connect with custody?',
    ],
    summary: 'A securities-servicing path covering instructions, positions, cash, settlement, events, reconciliations, client records, and control boundaries.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
  }),
  createRoleIntent({
    id: 'credit-operations-analyst-role',
    kind: 'guide',
    label: 'Credit Operations Analyst',
    guideId: 'credit-operations-analyst',
    canonicalPath: '/career-guides/credit-operations-analyst/',
    primaryQuestion: 'What does a credit operations analyst do?',
    searchQuestions: [
      'What does a credit operations analyst do?',
      'How does credit administration handle documents and conditions?',
      'Which skills are needed for credit operations roles?',
      'How should a credit operations analyst handle an incomplete approval condition?',
    ],
    summary: 'A workflow path for approved terms, documents, conditions, booking, servicing, exceptions, evidence, and authorised lending hand-offs.',
    quizDomainId: 'lending-credit-operations',
    coursePath: '/courses/finance-operations/',
    coursePathLabel: 'Explore the Finance Operations module',
    articleLinks: [{ label: 'Fictional loan-file review and model answer', path: '/blog/loan-operations-banking-roles-skills-career-path/' }],
  }),
  createRoleIntent({
    id: 'transaction-monitoring-analyst-role',
    kind: 'guide',
    label: 'Transaction Monitoring Analyst',
    guideId: 'transaction-monitoring-analyst',
    canonicalPath: '/career-guides/transaction-monitoring-analyst/',
    primaryQuestion: 'What does a transaction monitoring analyst do?',
    searchQuestions: [
      'What does a transaction monitoring analyst do?',
      'How does an AML alert investigation workflow operate?',
      'Which skills help with transaction monitoring case work?',
      'Why is a transaction monitoring alert not proof of wrongdoing?',
    ],
    summary: 'A careful alert-review path covering customer context, transaction evidence, case narratives, confidentiality, quality, and escalation authority.',
    quizDomainId: 'financial-crime-compliance',
    coursePath: '/courses/kyc-aml/',
    coursePathLabel: 'Explore the KYC / AML Masterclass module',
  }),
  createRoleIntent({
    id: 'middle-office-operations-role',
    kind: 'guide',
    label: 'Middle Office Operations',
    guideId: 'middle-office-operations',
    canonicalPath: '/career-guides/middle-office-operations/',
    primaryQuestion: 'What does a middle-office operations analyst do?',
    searchQuestions: [
      'What does a middle-office operations analyst do?',
      'How does middle office connect front office and settlement teams?',
      'Which controls appear in middle-office trade support?',
      'How should graduates read a middle-office job description?',
    ],
    summary: 'A role-family guide to transaction validation, risk and data hand-offs, trade support, exceptions, segregation, and downstream control.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
  }),
  createRoleIntent({
    id: 'back-office-banking-jobs-role',
    kind: 'guide',
    label: 'Back Office Banking Jobs',
    guideId: 'back-office-banking-jobs',
    canonicalPath: '/career-guides/back-office-banking-jobs/',
    primaryQuestion: 'Which back office banking jobs can a graduate explore?',
    searchQuestions: [
      'Which back office banking jobs can a graduate explore?',
      'What do bank back-office teams process and control?',
      'Which skills appear across banking operations jobs?',
      'How can a fresher compare back-office role families?',
    ],
    summary: 'A process-first map of customer, payments, lending, securities, compliance, reconciliation, reporting, and other banking operations roles.',
    quizDomainId: 'banking-career-roles',
    coursePath: '/courses/',
    articleLinks: [{ label: 'Finance operations portfolio projects for freshers', path: '/blog/finance-operations-portfolio-projects-freshers/' }],
  }),
  createRoleIntent({
    id: 'settlement-analyst-role',
    kind: 'guide',
    label: 'Settlement Analyst',
    guideId: 'settlement-analyst',
    canonicalPath: '/career-guides/settlement-analyst/',
    primaryQuestion: 'What does a settlement analyst do?',
    searchQuestions: [
      'What does a settlement analyst do?',
      'How does a settlement analyst investigate a failed trade?',
      'Which instruction and status fields matter in settlements?',
      'How can a fresher prepare for settlement operations?',
    ],
    summary: 'A role-specific path for instructions, matching, cut-offs, failed trades, cash and securities outcomes, evidence, and reconciliation.',
    quizDomainId: 'investment-banking-operations',
    coursePath: '/courses/investment-banking-operations/',
  }),
  createRoleIntent({
    id: 'finance-learning-roadmap-role',
    kind: 'guide',
    label: 'Finance Learning Roadmap',
    guideId: 'finance-learning-roadmap',
    canonicalPath: '/career-guides/finance-learning-roadmap/',
    primaryQuestion: 'How should a graduate build a finance learning roadmap?',
    searchQuestions: [
      'How should a graduate build a finance learning roadmap?',
      'Which finance skills should a fresher learn in sequence?',
      'How can a graduate build safe finance portfolio evidence?',
      'When should a learner choose a finance course or credential?',
    ],
    summary: 'A sequenced path from role choice and foundations through one workflow, fictional projects, interview evidence, feedback, and the next learning decision.',
    quizDomainId: 'banking-career-roles',
    coursePath: '/courses/',
  }),
  createRoleIntent({
    id: 'operations-analyst-banking-role',
    kind: 'guide',
    label: 'Operations Analyst in Banking',
    guideId: 'operations-analyst-banking',
    canonicalPath: '/career-guides/operations-analyst-banking/',
    primaryQuestion: 'What does an operations analyst do in banking?',
    searchQuestions: [
      'What does an operations analyst do in banking?',
      'Which queues and records does a bank operations analyst manage?',
      'How is a banking operations analyst different from a business analyst?',
      'What practical exercise can prepare a graduate for banking operations?',
    ],
    summary: 'A banking-qualified operations path covering records, queues, service levels, exceptions, reports, controls, and cross-team hand-offs.',
    quizDomainId: 'retail-banking-operations',
    coursePath: '/courses/retail-banking/',
    coursePathLabel: 'Explore the Retail Banking module',
  }),
  createRoleIntent({
    id: 'corporate-actions-analyst-role',
    kind: 'guide',
    label: 'Corporate Actions Analyst',
    guideId: 'corporate-actions-analyst',
    canonicalPath: '/career-guides/corporate-actions-analyst/',
    primaryQuestion: 'What does a corporate actions analyst do?',
    searchQuestions: [
      'What does a corporate actions analyst do?',
      'What skills are needed for corporate actions operations?',
      'How do dividends and stock splits affect securities operations?',
    ],
    summary: 'A specialist workflow path for issuer events, entitlements, elections, record dates, position updates, and corporate-actions exception control.',
    quizDomainId: 'corporate-actions-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [],
  }),
  createRoleIntent({
    id: 'fund-accounting-analyst-role',
    kind: 'guide',
    label: 'Fund Accounting Analyst',
    guideId: 'fund-accounting-analyst',
    canonicalPath: '/career-guides/fund-accounting-analyst/',
    primaryQuestion: 'What does a fund accounting analyst do?',
    searchQuestions: [
      'What does a fund accounting analyst do?',
      'What is the fund accounting and NAV workflow?',
      'What skills are needed for fund operations roles?',
    ],
    summary: 'A specialist workflow path for fund accounting, NAV inputs, portfolio records, reconciliations, unit pricing, and review evidence.',
    quizDomainId: 'asset-management-operations',
    coursePath: '/courses/investment-banking-operations/',
    articleLinks: [],
  }),
  createRoleIntent({
    id: 'loan-operations-analyst-role',
    kind: 'guide',
    label: 'Loan Processing Analyst',
    guideId: 'loan-processing-analyst',
    canonicalPath: '/career-guides/loan-processing-analyst/',
    primaryQuestion: 'What does a loan operations analyst do?',
    searchQuestions: [
      'What does a loan operations analyst do?',
      'What skills are needed for loan operations in banking?',
      'How does a loan operations workflow work?',
    ],
    summary: 'A specialist workflow path for loan processing, documentation, disbursement, servicing, credit controls, reconciliations, and exception handling.',
    quizDomainId: 'lending-credit-operations',
    coursePath: '/courses/finance-operations/',
    articleLinks: [],
  }),
  createRoleIntent({
    id: 'finance-process-associate-role',
    kind: 'specialist',
    label: 'Finance Process Associate',
    canonicalPath: '/blog/finance-process-associate-role/',
    primaryQuestion: 'What does a finance process associate do?',
    searchQuestions: [
      'What does a finance process associate do?',
      'What skills are needed for finance process associate roles?',
      'How does a finance process associate handle an exception?',
      'Can a fresher prepare for a finance process associate role?',
    ],
    summary: 'A specialist workflow path for finance queues, record checks, reconciliation, exception notes, hand-offs, controls, and entry-level preparation.',
    quizDomainId: 'accounting-finance-operations',
    coursePath: '/courses/finance-operations/',
    articleLinks: [
      { label: 'Risk management in banking', path: '/blog/risk-management-in-banking/' },
      { label: 'Finance operations portfolio projects for freshers', path: '/blog/finance-operations-portfolio-projects-freshers/' },
    ],
  }),
  createRoleIntent({
    id: 'banking-risk-operations-role',
    kind: 'specialist',
    label: 'Banking Risk Operations',
    canonicalPath: '/blog/risk-management-in-banking/',
    primaryQuestion: 'How does risk management work in banking operations?',
    searchQuestions: [
      'How does risk management work in banking operations?',
      'What are the main types of banking risk?',
      'How do controls reduce operational risk in banking?',
      'Which skills help with banking risk operations roles?',
    ],
    summary: 'A specialist path for banking-risk categories, control design, incident and issue handling, operational examples, evidence, and escalation.',
    quizDomainId: 'risk-management-operations',
    coursePath: '/courses/finance-operations/',
    articleLinks: [
      { label: 'Finance process associate duties and skills', path: '/blog/finance-process-associate-role/' },
      { label: 'Loan operations roles, skills, and career path', path: '/blog/loan-operations-banking-roles-skills-career-path/' },
    ],
  }),
  createRoleIntent({
    id: 'aml-analyst-role', kind: 'guide', label: 'AML Analyst', guideId: 'aml-analyst',
    canonicalPath: '/career-guides/aml-analyst/', primaryQuestion: 'What does an AML analyst do?',
    searchQuestions: ['What does an AML analyst do?', 'What skills do AML analyst jobs require?', 'Can a graduate apply for AML analyst jobs?', 'How does an AML case analyst document a review?'],
    summary: 'A role guide to AML alert and case workflows, evidence handling, case notes, confidentiality, escalation, and graduate preparation.',
    quizDomainId: 'financial-crime-compliance', coursePath: '/courses/kyc-aml/', coursePathLabel: 'Explore the KYC / AML Masterclass module',
  }),
  createRoleIntent({
    id: 'client-onboarding-analyst-role', kind: 'guide', label: 'Client Onboarding Analyst', guideId: 'client-onboarding-analyst',
    canonicalPath: '/career-guides/client-onboarding-analyst/', primaryQuestion: 'What does a client onboarding analyst do?',
    searchQuestions: ['What does a client onboarding analyst do?', 'What documents do onboarding analysts review?', 'How is client onboarding connected to KYC?', 'Can a graduate apply for onboarding analyst jobs?'],
    summary: 'A role guide to onboarding records, completeness checks, KYC hand-offs, case tracking, customer data, and approval boundaries.',
    quizDomainId: 'financial-crime-compliance', coursePath: '/courses/kyc-aml/', coursePathLabel: 'Explore the KYC / AML Masterclass module',
  }),
  createRoleIntent({
    id: 'payment-operations-analyst-role', kind: 'guide', label: 'Payment Operations Analyst', guideId: 'payment-operations-analyst',
    canonicalPath: '/career-guides/payment-operations-analyst/', primaryQuestion: 'What does a payment operations analyst do?',
    searchQuestions: ['What does a payment operations analyst do?', 'How are payment exceptions investigated?', 'What skills are useful in payment operations?', 'Can a fresher apply for payment operations jobs?'],
    summary: 'A role guide to payment instructions, transaction statuses, reconciliation, exceptions, deadlines, and controlled operations.',
    quizDomainId: 'digital-payments-operations', coursePath: '/courses/digital-payments/', coursePathLabel: 'Explore the Digital Payments module',
  }),
  createRoleIntent({
    id: 'upi-operations-analyst-role', kind: 'guide', label: 'UPI Operations Analyst', guideId: 'upi-operations-analyst',
    canonicalPath: '/career-guides/upi-operations-analyst/', primaryQuestion: 'What does a UPI operations analyst do?',
    searchQuestions: ['What does a UPI operations analyst do?', 'How are UPI transaction issues reviewed?', 'What skills help with UPI operations jobs?', 'Can graduates apply for UPI operations roles?'],
    summary: 'A role guide to UPI transaction records, status checks, reconciliation, service cases, and operations boundaries.',
    quizDomainId: 'digital-payments-operations', coursePath: '/courses/digital-payments/', coursePathLabel: 'Explore the Digital Payments module',
    articleLinks: [{ label: 'Explore the UPI payment lifecycle', path: '/blog/upi-payment-lifecycle/' }],
  }),
  createRoleIntent({
    id: 'payment-disputes-analyst-role', kind: 'guide', label: 'Payment Disputes Analyst', guideId: 'payment-disputes-analyst',
    canonicalPath: '/career-guides/payment-disputes-analyst/', primaryQuestion: 'What does a payment disputes analyst do?',
    searchQuestions: ['What does a payment disputes analyst do?', 'What does a chargeback analyst review?', 'Which skills are useful in payment disputes?', 'How are payment dispute cases documented?'],
    summary: 'A role guide to dispute intake, evidence review, case deadlines, reconciliation, authorised decisions, and case quality.',
    quizDomainId: 'digital-payments-operations', coursePath: '/courses/digital-payments/', coursePathLabel: 'Explore the Digital Payments module',
  }),
  createRoleIntent({
    id: 'branch-operations-analyst-role', kind: 'guide', label: 'Bank Branch Operations', guideId: 'branch-operations-analyst',
    canonicalPath: '/career-guides/branch-operations-analyst/', primaryQuestion: 'What does a bank branch operations analyst do?',
    searchQuestions: ['What does a bank branch operations analyst do?', 'What are branch operations responsibilities?', 'Which skills help graduates enter branch banking?', 'How is branch operations different from relationship management?'],
    summary: 'A role guide to retail banking service requests, document checks, transaction support, records, controls, and escalation.',
    quizDomainId: 'retail-banking-operations', coursePath: '/courses/retail-banking/', coursePathLabel: 'Explore the Retail Banking module',
  }),
  createRoleIntent({
    id: 'banking-relationship-manager-role', kind: 'guide', label: 'Banking Relationship Manager', guideId: 'banking-relationship-manager',
    canonicalPath: '/career-guides/banking-relationship-manager/', primaryQuestion: 'What does a banking relationship manager do?',
    searchQuestions: ['What does a banking relationship manager do?', 'What skills do bank relationship manager jobs require?', 'Is relationship management a sales role?', 'How do relationship managers coordinate customer requests?'],
    summary: 'A role guide to customer relationships, product conversations, servicing, team coordination, and responsible role boundaries.',
    quizDomainId: 'retail-banking-operations', coursePath: '/courses/retail-banking/', coursePathLabel: 'Explore the Retail Banking module',
  }),
  createRoleIntent({
    id: 'nbfc-operations-analyst-role', kind: 'guide', label: 'NBFC Operations Analyst', guideId: 'nbfc-operations-analyst',
    canonicalPath: '/career-guides/nbfc-operations-analyst/', primaryQuestion: 'What does an NBFC operations analyst do?',
    searchQuestions: ['What does an NBFC operations analyst do?', 'Which NBFC operations jobs can graduates explore?', 'What skills help with NBFC back-office roles?', 'How do loan and repayment workflows connect in an NBFC?'],
    summary: 'A role guide to NBFC lending and service operations, loan records, repayment reconciliation, exceptions, and controls.',
    quizDomainId: 'lending-credit-operations', coursePath: '/courses/finance-operations/', coursePathLabel: 'Explore the Finance Operations module',
  }),
  createRoleIntent({
    id: 'fintech-operations-analyst-role', kind: 'guide', label: 'FinTech Operations Analyst', guideId: 'fintech-operations-analyst',
    canonicalPath: '/career-guides/fintech-operations-analyst/', primaryQuestion: 'What does a FinTech operations analyst do?',
    searchQuestions: ['What does a FinTech operations analyst do?', 'What skills do FinTech operations jobs require?', 'Can a graduate apply for FinTech operations jobs in India?', 'How do FinTech operations teams handle payment exceptions?'],
    summary: 'A role guide to digital finance workflows, payment and account records, operational cases, controls, cross-team hand-offs, and graduate preparation.',
    quizDomainId: 'digital-payments-operations', coursePath: '/courses/digital-payments/', coursePathLabel: 'Explore the Digital Payments module',
  }),
]);

export function getRoleIntentByGuideId(guideId) {
  return ROLE_INTENTS.find((intent) => intent.guideId === guideId) || null;
}

export function getRoleIntentById(intentId) {
  return ROLE_INTENTS.find((intent) => intent.id === intentId) || null;
}

export function getRoleIntentByCanonicalPath(canonicalPath) {
  return ROLE_INTENTS.find((intent) => intent.canonicalPath === canonicalPath) || null;
}
