import { getSeoRoute } from './seoRoutes.js';
import { getAuthorityTarget } from '../content/seo/authorityBuilding.js';

// Route IDs describe the site's information architecture. Link labels are taken
// from each route's existing H1 so navigation stays aligned with page meaning.
export const INTERNAL_LINK_ARCHITECTURE = Object.freeze({
  home: Object.freeze(['courses', 'courses-banking-courses', 'courses-banking-and-finance', 'career-guides', 'career-guide-reconciliation-analyst', 'resources', 'resource-bank-reconciliation-process', 'india', 'placements', 'comparison-best-finance-institutes-india', 'lead-best-investment-banking-course-india', 'lead-online-finance-course-placement', 'blog', 'faqs', 'lucknow-location', 'contact', 'privacy-policy']),
  blog: Object.freeze(['career-guides', 'resources', 'india', 'courses', 'placements', 'comparison-best-finance-institutes-india', 'faqs', 'contact']),
  'career-guides': Object.freeze(['courses', 'courses-banking-courses', 'blog', 'resources', 'india', 'comparison-investment-banking-operations', 'comparison-best-finance-institutes-india', 'comparison-finance-operations-vs-financial-modelling-cfa', 'comparison-investment-banking-operations-vs-financial-analyst', 'comparison-banking-vs-finance-careers', 'placements', 'faqs', 'lucknow-location', 'contact', 'career-guide-investment-banking-operations', 'career-guide-investment-banking-operations-roles', 'career-guide-trade-support-analyst', 'career-guide-securities-operations', 'career-guide-reconciliation-analyst', 'career-guide-what-is-investment-banking', 'career-guide-kyc-aml-analyst', 'career-guide-finance-operations', 'career-guide-trade-lifecycle', 'career-guide-finance-careers-after-graduation', 'career-guide-retail-banking-operations', 'career-guide-digital-payments-operations', 'career-guide-financial-operations-faq', 'career-guide-choosing-finance-career-course', 'career-guide-fintech-operations', 'career-guide-risk-operations-analyst', 'career-guide-credit-analyst', 'career-guide-business-analyst-in-banking', 'career-guide-custody-operations', 'career-guide-credit-operations-analyst', 'career-guide-transaction-monitoring-analyst', 'career-guide-middle-office-operations', 'career-guide-back-office-banking-jobs', 'career-guide-settlement-analyst', 'career-guide-finance-learning-roadmap', 'career-guide-operations-analyst-banking', 'resource-investment-banking-interview-questions']),
  resources: Object.freeze(['courses', 'courses-finance-operations-training', 'career-guides', 'career-guide-reconciliation-analyst', 'india', 'comparison-investment-banking-operations', 'comparison-best-finance-institutes-india', 'comparison-finance-operations-vs-financial-modelling-cfa', 'resource-investment-banking-interview-questions', 'resource-finance-gk', 'resource-accounting-basics', 'resource-accounting-interview-questions', 'resource-reconciliation-in-finance', 'resource-bank-reconciliation-process', 'resource-cost-accounting-finance-operations', 'resource-financial-accounting-banking', 'resource-financial-statement-analysis', 'resource-corporate-actions-workflow', 'resource-capital-market-operations', 'resource-financial-system-india', 'resource-kyc-aml-compliance-guide', 'quiz', 'placements', 'faqs', 'lucknow-location', 'contact']),
  quiz: Object.freeze(['resources', 'courses', 'career-guides', 'resource-investment-banking-interview-questions', 'resource-finance-gk', 'comparison-best-finance-institutes-india', 'india', 'faqs', 'placements', 'contact']),
  courses: Object.freeze([
    'investment-banking-operations',
    'courses-banking-courses',
    'courses-banking-and-finance',
    'courses-finance-operations-training',
    'courses-finance-operations-syllabus',
    'courses-finance-course-fees-eligibility',
    'courses-finance-course-for-graduates',
    'lead-job-oriented-finance-course-india',
    'lead-investment-banking-operations-course-placement',
    'retail-banking',
    'finance-operations',
    'kyc-aml-compliance',
    'digital-payments',
    'fintech-neo-banking',
    'placements',
    'faqs',
    'lucknow-location',
    'career-guides',
    'comparison-investment-banking-operations',
    'comparison-best-finance-institutes-india',
    'comparison-finance-operations-vs-financial-modelling-cfa',
    'comparison-online-vs-offline-finance-training',
    'comparison-investment-banking-operations-vs-financial-analyst',
    'comparison-banking-vs-finance-careers',
    'faqs-finance-program',
    'career-guide-choosing-finance-career-course',
    'career-guide-investment-banking-operations',
    'career-guide-retail-banking-operations',
    'career-guide-finance-operations',
    'career-guide-kyc-aml-analyst',
    'career-guide-digital-payments-operations',
    'career-guide-fintech-operations',
    'career-guide-finance-careers-after-graduation',
    'resources',
    'india',
    'resource-investment-banking-interview-questions',
    'resource-finance-gk',
    'resource-bank-reconciliation-process',
    'resource-financial-accounting-banking',
    'resource-financial-statement-analysis',
    'contact',
    'privacy-policy',
  ]),
  'investment-banking-operations': Object.freeze([
    'courses',
    'courses-finance-course-fees-eligibility',
    'courses-finance-operations-syllabus',
    'india-bengaluru',
    'india-mumbai',
    'resource-corporate-actions-workflow',
    'courses-banking-courses',
    'retail-banking',
    'finance-operations',
    'placements',
    'faqs',
    'lucknow-location',
    'career-guides',
    'career-guide-investment-banking-operations',
    'career-guide-investment-banking-operations-roles',
    'career-guide-trade-support-analyst',
    'career-guide-securities-operations',
    'resources',
    'india',
    'resource-investment-banking-interview-questions',
    'resource-finance-gk',
    'contact',
  ]),
  'retail-banking': Object.freeze([
    'courses',
    'investment-banking-operations',
    'finance-operations',
    'placements',
    'faqs',
    'lucknow-location',
    'career-guides',
    'career-guide-retail-banking-operations',
    'resources',
    'india',
    'resource-investment-banking-interview-questions',
    'contact',
  ]),
  'finance-operations': Object.freeze([
    'courses',
    'courses-finance-operations-training',
    'investment-banking-operations',
    'retail-banking',
    'placements',
    'faqs',
    'lucknow-location',
    'career-guides',
    'career-guide-finance-operations',
    'career-guide-reconciliation-analyst',
    'resource-financial-accounting-banking',
    'resource-financial-statement-analysis',
    'resources',
    'india',
    'resource-investment-banking-interview-questions',
    'contact',
  ]),
  'kyc-aml-compliance': Object.freeze(['courses', 'career-guide-kyc-aml-analyst', 'career-guide-fintech-operations', 'india-mumbai', 'resources', 'resource-investment-banking-interview-questions', 'placements', 'faqs', 'contact']),
  'digital-payments': Object.freeze(['courses', 'career-guide-digital-payments-operations', 'career-guide-fintech-operations', 'resources', 'india', 'placements', 'faqs', 'contact']),
  'fintech-neo-banking': Object.freeze(['courses', 'career-guide-fintech-operations', 'career-guide-digital-payments-operations', 'career-guide-finance-careers-after-graduation', 'resources', 'placements', 'faqs', 'contact']),
  placements: Object.freeze(['courses', 'career-guides', 'resources', 'india', 'comparison-best-finance-institutes-india', 'lead-finance-course-placement', 'lead-finance-course-job-guarantee', 'about', 'faqs', 'contact']),
  about: Object.freeze(['courses', 'career-guides', 'resources', 'india', 'placements', 'lucknow-location', 'contact']),
  contact: Object.freeze(['lucknow-location', 'courses', 'career-guides', 'resources', 'india', 'placements', 'faqs', 'privacy-policy']),
  'lucknow-location': Object.freeze(['contact', 'courses', 'career-guides', 'resources', 'india', 'placements', 'lead-finance-institute-lucknow-placement', 'faqs']),
  faqs: Object.freeze(['courses', 'faqs-finance-program', 'career-guides', 'resources', 'india', 'resource-investment-banking-interview-questions', 'placements', 'lucknow-location', 'contact']),
  india: Object.freeze(['courses', 'courses-banking-courses', 'courses-banking-and-finance', 'courses-finance-operations-training', 'courses-finance-operations-syllabus', 'courses-finance-course-fees-eligibility', 'courses-finance-course-for-graduates', 'investment-banking-operations', 'retail-banking', 'finance-operations', 'kyc-aml-compliance', 'digital-payments', 'fintech-neo-banking', 'career-guides', 'comparison-investment-banking-operations', 'comparison-best-finance-institutes-india', 'lead-finance-course-cities-india', 'resources', 'resource-investment-banking-interview-questions', 'resource-finance-gk', 'placements', 'faqs', 'lucknow-location', 'contact', 'india-delhi-ncr', 'india-bengaluru', 'india-mumbai', 'india-pune', 'india-hyderabad']),
  'india-delhi-ncr': Object.freeze(['india', 'courses', 'courses-banking-and-finance', 'investment-banking-operations', 'career-guides', 'career-guide-finance-operations', 'career-guide-kyc-aml-analyst', 'resources', 'resource-investment-banking-interview-questions', 'placements', 'lucknow-location', 'faqs', 'contact']),
  'india-bengaluru': Object.freeze(['india', 'courses', 'investment-banking-operations', 'career-guides', 'career-guide-investment-banking-operations', 'career-guide-digital-payments-operations', 'career-guide-finance-operations', 'resources', 'resource-investment-banking-interview-questions', 'placements', 'lucknow-location', 'faqs', 'contact']),
  'india-mumbai': Object.freeze(['india', 'courses', 'kyc-aml-compliance', 'career-guides', 'career-guide-kyc-aml-analyst', 'career-guide-investment-banking-operations', 'career-guide-trade-lifecycle', 'resources', 'resource-investment-banking-interview-questions', 'placements', 'lucknow-location', 'faqs', 'contact']),
  'india-pune': Object.freeze(['india', 'courses', 'career-guides', 'career-guide-finance-operations', 'career-guide-fintech-operations', 'career-guide-digital-payments-operations', 'resources', 'placements', 'faqs', 'contact']),
  'india-hyderabad': Object.freeze(['india', 'courses', 'career-guides', 'career-guide-fintech-operations', 'career-guide-kyc-aml-analyst', 'resources', 'placements', 'faqs', 'contact']),
  'privacy-policy': Object.freeze(['home', 'contact', 'courses', 'terms-and-conditions', 'cookie-policy', 'refund-cancellation-policy', 'disclaimer']),
  'terms-and-conditions': Object.freeze(['privacy-policy', 'refund-cancellation-policy', 'cookie-policy', 'disclaimer', 'courses', 'contact']),
  'cookie-policy': Object.freeze(['privacy-policy', 'terms-and-conditions', 'refund-cancellation-policy', 'disclaimer', 'contact']),
  'refund-cancellation-policy': Object.freeze(['privacy-policy', 'terms-and-conditions', 'cookie-policy', 'disclaimer', 'courses', 'placements', 'contact']),
  disclaimer: Object.freeze(['privacy-policy', 'terms-and-conditions', 'cookie-policy', 'refund-cancellation-policy', 'courses', 'contact']),
  'comparison-investment-banking-operations': Object.freeze(['courses', 'courses-banking-and-finance', 'career-guides', 'resources', 'comparison-best-finance-institutes-india', 'comparison-finance-operations-vs-financial-modelling-cfa', 'comparison-online-vs-offline-finance-training', 'india', 'resource-investment-banking-interview-questions', 'placements', 'faqs', 'contact']),
  'comparison-best-finance-institutes-india': Object.freeze(['courses', 'courses-banking-courses', 'courses-banking-and-finance', 'lead-best-finance-course-placement', 'courses-finance-course-for-graduates', 'courses-finance-course-fees-eligibility', 'career-guide-choosing-finance-career-course', 'placements', 'india', 'resources', 'contact']),
  'career-guide-investment-banking-operations': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'resources', 'india', 'india-bengaluru', 'resource-corporate-actions-workflow', 'resource-investment-banking-interview-questions', 'career-guide-trade-lifecycle', 'career-guide-finance-operations', 'career-guide-finance-careers-after-graduation', 'placements']),
  'career-guide-kyc-aml-analyst': Object.freeze(['career-guides', 'courses', 'kyc-aml-compliance', 'resources', 'india', 'india-mumbai', 'resource-investment-banking-interview-questions', 'career-guide-finance-operations', 'career-guide-retail-banking-operations', 'career-guide-digital-payments-operations', 'placements', 'faqs']),
  'career-guide-finance-operations': Object.freeze(['career-guides', 'courses', 'courses-finance-operations-training', 'finance-operations', 'resources', 'resource-financial-accounting-banking', 'resource-financial-statement-analysis', 'india', 'india-delhi-ncr', 'resource-investment-banking-interview-questions', 'career-guide-reconciliation-analyst', 'career-guide-investment-banking-operations', 'career-guide-kyc-aml-analyst', 'career-guide-finance-careers-after-graduation', 'placements']),
  'career-guide-trade-lifecycle': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-settlement-analyst', 'resources', 'india', 'resource-investment-banking-interview-questions', 'career-guide-investment-banking-operations', 'career-guide-finance-operations', 'career-guide-digital-payments-operations', 'faqs']),
  'career-guide-finance-careers-after-graduation': Object.freeze(['career-guides', 'courses', 'lead-best-finance-course-after-bcom', 'lead-best-finance-course-after-graduation', 'resources', 'india', 'resource-investment-banking-interview-questions', 'career-guide-investment-banking-operations', 'career-guide-finance-operations', 'career-guide-kyc-aml-analyst', 'career-guide-retail-banking-operations', 'contact']),
  'career-guide-retail-banking-operations': Object.freeze(['career-guides', 'courses', 'retail-banking', 'resources', 'india', 'resource-investment-banking-interview-questions', 'career-guide-kyc-aml-analyst', 'career-guide-finance-operations', 'career-guide-finance-careers-after-graduation', 'faqs']),
  'career-guide-digital-payments-operations': Object.freeze(['career-guides', 'courses', 'digital-payments', 'career-guide-fintech-operations', 'resources', 'india', 'resource-investment-banking-interview-questions', 'career-guide-kyc-aml-analyst', 'career-guide-trade-lifecycle', 'career-guide-retail-banking-operations', 'faqs', 'contact']),
  'career-guide-financial-operations-faq': Object.freeze(['career-guides', 'courses', 'resources', 'india', 'resource-investment-banking-interview-questions', 'career-guide-finance-careers-after-graduation', 'career-guide-investment-banking-operations', 'career-guide-kyc-aml-analyst', 'career-guide-finance-operations', 'placements']),
  'career-guide-choosing-finance-career-course': Object.freeze(['career-guides', 'courses', 'lead-which-finance-course-right', 'comparison-investment-banking-operations', 'comparison-best-finance-institutes-india', 'career-guide-finance-careers-after-graduation', 'career-guide-investment-banking-operations', 'career-guide-kyc-aml-analyst', 'resource-investment-banking-interview-questions', 'placements', 'faqs', 'contact']),
  'career-guide-fintech-operations': Object.freeze(['career-guides', 'courses', 'fintech-neo-banking', 'digital-payments', 'career-guide-digital-payments-operations', 'career-guide-finance-careers-after-graduation', 'career-guide-finance-operations', 'resources', 'india', 'resource-investment-banking-interview-questions', 'placements', 'contact']),
  'resource-investment-banking-interview-questions': Object.freeze(['resources', 'courses', 'investment-banking-operations', 'career-guides', 'india', 'career-guide-investment-banking-operations', 'career-guide-trade-lifecycle', 'career-guide-kyc-aml-analyst', 'career-guide-finance-operations', 'resource-finance-gk', 'resource-accounting-basics', 'resource-reconciliation-in-finance', 'faqs', 'placements', 'contact']),
  'resource-finance-gk': Object.freeze(['resources', 'courses', 'india', 'career-guides', 'career-guide-finance-operations', 'career-guide-digital-payments-operations', 'career-guide-trade-lifecycle', 'resource-investment-banking-interview-questions', 'resource-accounting-basics', 'resource-reconciliation-in-finance', 'placements', 'contact']),
  'resource-accounting-basics': Object.freeze(['resources', 'courses', 'india', 'career-guides', 'career-guide-finance-operations', 'resource-finance-gk', 'resource-reconciliation-in-finance', 'resource-accounting-interview-questions', 'resource-investment-banking-interview-questions', 'placements', 'contact']),
  'resource-accounting-interview-questions': Object.freeze(['resources', 'resource-accounting-basics', 'resource-reconciliation-in-finance', 'resource-investment-banking-interview-questions', 'career-guide-finance-operations', 'courses', 'contact']),
  'resource-reconciliation-in-finance': Object.freeze(['resources', 'resource-bank-reconciliation-process', 'courses', 'india', 'career-guides', 'career-guide-reconciliation-analyst', 'career-guide-finance-operations', 'career-guide-trade-lifecycle', 'resource-finance-gk', 'resource-accounting-basics', 'resource-accounting-interview-questions', 'resource-investment-banking-interview-questions', 'placements', 'contact']),
  'career-guide-reconciliation-analyst': Object.freeze(['career-guides', 'courses', 'courses-finance-operations-training', 'resources', 'resource-bank-reconciliation-process', 'resource-reconciliation-in-finance', 'career-guide-finance-operations', 'resource-investment-banking-interview-questions', 'placements', 'contact']),
  'career-guide-investment-banking-operations-roles': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-trade-support-analyst', 'career-guide-securities-operations', 'career-guide-what-is-investment-banking', 'resource-investment-banking-interview-questions', 'resources', 'placements', 'contact']),
  'career-guide-trade-support-analyst': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-investment-banking-operations-roles', 'career-guide-securities-operations', 'career-guide-trade-lifecycle', 'resource-reconciliation-in-finance', 'resource-investment-banking-interview-questions', 'placements']),
  'career-guide-securities-operations': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-investment-banking-operations-roles', 'career-guide-trade-support-analyst', 'career-guide-trade-lifecycle', 'resource-reconciliation-in-finance', 'resource-investment-banking-interview-questions', 'placements']),
  'career-guide-what-is-investment-banking': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-investment-banking-operations-roles', 'comparison-finance-operations-vs-financial-modelling-cfa', 'resource-investment-banking-interview-questions', 'contact']),
  'resource-bank-reconciliation-process': Object.freeze(['resources', 'resource-reconciliation-in-finance', 'resource-accounting-basics', 'career-guide-reconciliation-analyst', 'career-guide-finance-operations', 'courses-finance-operations-training', 'courses', 'contact']),
  'resource-cost-accounting-finance-operations': Object.freeze(['resources', 'resource-financial-accounting-banking', 'resource-financial-statement-analysis', 'career-guide-finance-operations', 'courses-finance-operations-training', 'courses', 'contact']),
  'resource-financial-accounting-banking': Object.freeze(['resources', 'resource-bank-reconciliation-process', 'resource-accounting-basics', 'career-guide-finance-operations', 'courses-finance-operations-training', 'resource-financial-statement-analysis', 'courses', 'contact']),
  'resource-financial-statement-analysis': Object.freeze(['resources', 'resource-financial-accounting-banking', 'career-guide-finance-operations', 'courses-finance-operations-training', 'comparison-finance-operations-vs-financial-modelling-cfa', 'courses', 'contact']),
  'courses-banking-courses': Object.freeze(['courses', 'courses-banking-and-finance', 'retail-banking', 'investment-banking-operations', 'career-guide-investment-banking-operations-roles', 'career-guide-finance-operations', 'placements', 'faqs-finance-program', 'contact']),
  'courses-banking-and-finance': Object.freeze(['courses', 'courses-banking-courses', 'lead-banking-finance-course-placement', 'courses-finance-operations-training', 'career-guides', 'comparison-finance-operations-vs-financial-modelling-cfa', 'faqs-finance-program', 'placements', 'india-delhi-ncr', 'contact']),
  'courses-finance-operations-training': Object.freeze(['courses', 'courses-banking-and-finance', 'finance-operations', 'career-guide-finance-operations', 'career-guide-reconciliation-analyst', 'resource-financial-accounting-banking', 'resource-financial-statement-analysis', 'resource-cost-accounting-finance-operations', 'placements', 'contact']),
  'comparison-finance-operations-vs-financial-modelling-cfa': Object.freeze(['courses', 'courses-finance-operations-training', 'lead-finance-course-vs-mba-cfa-modelling', 'courses-banking-and-finance', 'career-guide-finance-operations', 'resource-financial-statement-analysis', 'faqs-finance-program', 'contact']),
  'comparison-online-vs-offline-finance-training': Object.freeze(['courses', 'lead-online-finance-course-placement', 'india', 'lucknow-location', 'faqs-finance-program', 'placements', 'contact']),
  'faqs-finance-program': Object.freeze(['courses', 'courses-banking-and-finance', 'courses-banking-courses', 'placements', 'comparison-online-vs-offline-finance-training', 'contact']),
  'career-guide-risk-operations-analyst': Object.freeze(['career-guides', 'courses', 'finance-operations', 'career-guide-finance-operations', 'career-guide-reconciliation-analyst', 'career-guide-operations-analyst-banking', 'resources', 'contact']),
  'career-guide-credit-analyst': Object.freeze(['career-guides', 'courses', 'finance-operations', 'career-guide-credit-operations-analyst', 'resource-financial-statement-analysis', 'resource-financial-accounting-banking', 'contact']),
  'career-guide-business-analyst-in-banking': Object.freeze(['career-guides', 'courses', 'retail-banking', 'career-guide-retail-banking-operations', 'career-guide-operations-analyst-banking', 'comparison-banking-vs-finance-careers', 'contact']),
  'career-guide-custody-operations': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-securities-operations', 'career-guide-settlement-analyst', 'resource-capital-market-operations', 'resource-corporate-actions-workflow', 'contact']),
  'career-guide-credit-operations-analyst': Object.freeze(['career-guides', 'courses', 'finance-operations', 'career-guide-credit-analyst', 'career-guide-finance-operations', 'resource-financial-statement-analysis', 'contact']),
  'career-guide-transaction-monitoring-analyst': Object.freeze(['career-guides', 'courses', 'kyc-aml-compliance', 'career-guide-kyc-aml-analyst', 'resource-kyc-aml-compliance-guide', 'career-guide-risk-operations-analyst', 'contact']),
  'career-guide-middle-office-operations': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-trade-support-analyst', 'career-guide-back-office-banking-jobs', 'career-guide-investment-banking-operations-roles', 'contact']),
  'career-guide-back-office-banking-jobs': Object.freeze(['career-guides', 'courses', 'career-guide-finance-operations', 'career-guide-middle-office-operations', 'career-guide-operations-analyst-banking', 'comparison-banking-vs-finance-careers', 'resources', 'contact']),
  'career-guide-settlement-analyst': Object.freeze(['career-guides', 'courses', 'investment-banking-operations', 'career-guide-trade-lifecycle', 'career-guide-custody-operations', 'career-guide-trade-support-analyst', 'resource-capital-market-operations', 'contact']),
  'career-guide-finance-learning-roadmap': Object.freeze(['career-guides', 'courses', 'courses-finance-operations-syllabus', 'courses-finance-course-for-graduates', 'career-guide-finance-careers-after-graduation', 'career-guide-choosing-finance-career-course', 'resources', 'contact']),
  'career-guide-operations-analyst-banking': Object.freeze(['career-guides', 'courses', 'retail-banking', 'finance-operations', 'career-guide-finance-operations', 'career-guide-retail-banking-operations', 'career-guide-back-office-banking-jobs', 'contact']),
  'resource-corporate-actions-workflow': Object.freeze(['resources', 'courses', 'investment-banking-operations', 'career-guide-investment-banking-operations', 'career-guide-custody-operations', 'career-guide-trade-lifecycle', 'resource-capital-market-operations', 'contact']),
  'resource-capital-market-operations': Object.freeze(['resources', 'courses', 'investment-banking-operations', 'career-guide-securities-operations', 'career-guide-settlement-analyst', 'career-guide-custody-operations', 'resource-corporate-actions-workflow', 'contact']),
  'resource-financial-system-india': Object.freeze(['resources', 'courses', 'india', 'resource-finance-gk', 'resource-capital-market-operations', 'career-guides', 'contact']),
  'resource-kyc-aml-compliance-guide': Object.freeze(['resources', 'courses', 'kyc-aml-compliance', 'career-guide-kyc-aml-analyst', 'career-guide-transaction-monitoring-analyst', 'career-guide-risk-operations-analyst', 'contact']),
  'courses-finance-operations-syllabus': Object.freeze(['courses', 'lead-finance-course-duration', 'courses-finance-course-for-graduates', 'courses-finance-course-fees-eligibility', 'career-guide-finance-learning-roadmap', 'career-guide-finance-operations', 'resource-financial-accounting-banking', 'faqs-finance-program', 'contact']),
  'courses-finance-course-fees-eligibility': Object.freeze(['courses', 'lead-finance-course-fees-india', 'lead-finance-course-eligibility', 'courses-finance-operations-syllabus', 'courses-finance-course-for-graduates', 'faqs-finance-program', 'placements', 'comparison-best-finance-institutes-india', 'comparison-online-vs-offline-finance-training', 'contact']),
  'courses-finance-course-for-graduates': Object.freeze(['courses', 'lead-best-finance-course-after-graduation', 'courses-finance-operations-syllabus', 'courses-finance-course-fees-eligibility', 'career-guide-finance-learning-roadmap', 'career-guide-finance-careers-after-graduation', 'courses-banking-and-finance', 'contact']),
  'comparison-investment-banking-operations-vs-financial-analyst': Object.freeze(['courses', 'investment-banking-operations', 'career-guide-investment-banking-operations', 'career-guide-finance-operations', 'resource-financial-statement-analysis', 'comparison-finance-operations-vs-financial-modelling-cfa', 'contact']),
  'comparison-banking-vs-finance-careers': Object.freeze(['courses', 'courses-banking-and-finance', 'career-guide-finance-careers-after-graduation', 'career-guide-retail-banking-operations', 'career-guide-finance-operations', 'resource-financial-system-india', 'contact']),
  'lead-best-finance-course-placement': Object.freeze(['comparison-best-finance-institutes-india', 'courses', 'placements', 'courses-finance-course-fees-eligibility', 'career-guide-choosing-finance-career-course', 'contact']),
  'lead-best-investment-banking-course-india': Object.freeze(['courses', 'investment-banking-operations', 'comparison-investment-banking-operations', 'career-guide-investment-banking-operations', 'placements', 'contact']),
  'lead-best-finance-course-after-graduation': Object.freeze(['courses-finance-course-for-graduates', 'courses', 'career-guide-finance-careers-after-graduation', 'career-guide-choosing-finance-career-course', 'contact']),
  'lead-best-finance-course-after-bcom': Object.freeze(['career-guide-finance-careers-after-graduation', 'courses-finance-course-for-graduates', 'courses', 'courses-finance-operations-training', 'placements', 'contact']),
  'lead-finance-course-placement': Object.freeze(['placements', 'courses', 'comparison-online-vs-offline-finance-training', 'faqs-finance-program', 'contact']),
  'lead-finance-course-job-guarantee': Object.freeze(['placements', 'courses', 'faqs-finance-program', 'courses-finance-course-fees-eligibility', 'contact']),
  'lead-finance-course-fees-india': Object.freeze(['courses-finance-course-fees-eligibility', 'courses', 'comparison-online-vs-offline-finance-training', 'faqs-finance-program', 'contact']),
  'lead-finance-course-duration': Object.freeze(['courses-finance-operations-syllabus', 'courses', 'comparison-online-vs-offline-finance-training', 'contact']),
  'lead-finance-course-eligibility': Object.freeze(['courses-finance-course-fees-eligibility', 'courses-finance-course-for-graduates', 'courses', 'comparison-online-vs-offline-finance-training', 'contact']),
  'lead-online-finance-course-placement': Object.freeze(['courses', 'india', 'placements', 'comparison-online-vs-offline-finance-training', 'contact']),
  'lead-job-oriented-finance-course-india': Object.freeze(['courses', 'courses-finance-operations-training', 'career-guide-finance-operations', 'career-guide-choosing-finance-career-course', 'placements', 'contact']),
  'lead-banking-finance-course-placement': Object.freeze(['courses-banking-and-finance', 'courses-banking-courses', 'placements', 'comparison-best-finance-institutes-india', 'contact']),
  'lead-investment-banking-operations-course-placement': Object.freeze(['courses', 'investment-banking-operations', 'comparison-investment-banking-operations', 'career-guide-trade-lifecycle', 'placements', 'contact']),
  'lead-finance-institute-lucknow-placement': Object.freeze(['lucknow-location', 'placements', 'comparison-online-vs-offline-finance-training', 'courses', 'contact']),
  'lead-finance-course-cities-india': Object.freeze(['india', 'india-delhi-ncr', 'india-bengaluru', 'comparison-online-vs-offline-finance-training', 'placements', 'contact']),
  'lead-finance-course-vs-mba-cfa-modelling': Object.freeze(['comparison-finance-operations-vs-financial-modelling-cfa', 'courses-finance-operations-training', 'resource-financial-statement-analysis', 'career-guide-choosing-finance-career-course', 'contact']),
  'lead-which-finance-course-right': Object.freeze(['career-guide-choosing-finance-career-course', 'quiz', 'comparison-best-finance-institutes-india', 'courses', 'contact']),
});

export function getInternalLinks(routeId) {
  const targetRouteIds = INTERNAL_LINK_ARCHITECTURE[routeId] || [];

  return targetRouteIds.map((targetRouteId) => {
    const targetRoute = getSeoRoute(targetRouteId);
    return {
      routeId: targetRouteId,
      to: targetRoute.path,
      label: targetRoute.h1,
      authorityTier: getAuthorityTarget(targetRouteId)?.tier || 'supporting',
    };
  });
}
