import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import analyze_top_pages as top_pages
import create_seo_keyword_plan as base


CSV_PATH = Path(r'C:\Users\Virat Singh\Downloads\TopPages_imarticus-org_9_27_2026_SEO (1).csv')
base.OUTPUT = base.ROOT / 'SEO_Competitor_TopPages_Addon_2026-09-27.xlsx'


def pick(rows, fragment=None, url_fragment=None):
    matches = []
    for row in rows:
        if fragment and fragment.lower() not in (row['Title'] + ' ' + row['Top KW']).lower():
            continue
        if url_fragment and url_fragment.lower() not in row['Url'].lower():
            continue
        matches.append(row)
    return max(matches, key=lambda row: (row['Est Monthly SEO Clicks'], row['Top KW Clicks']), default=None)


def metric(row):
    if not row:
        return 'No matching row in supplied top-page export'
    return f"{int(row['Est Monthly SEO Clicks'])} est. SEO clicks; {row['Top KW']} at position {int(row['Top KW Position'])}; volume {int(row['Top KW Search Volume'])}; {int(row['Top KW Clicks'])} top-keyword clicks"


def build():
    all_rows = top_pages.load(CSV_PATH)
    relevant = [row for row in all_rows if top_pages.RELEVANT.search(row['Title'] + ' ' + row['Top KW']) and not top_pages.NOISE.search(row['Title'] + ' ' + row['Top KW'])]

    observation_defs = [
        ('Reconciliation', pick(relevant, url_fragment='/blog/reconciliation-meaning/'), 'Definition + process + steps', 'Retain the canonical reconciliation resource; expand with finance examples, break investigation, controls and interview prompts.', '/resources/reconciliation-in-finance/', 'Refresh immediately', 'Do not publish a second reconciliation URL.'),
        ('Golden rules of accounting', pick(relevant, url_fragment='/blog/golden-rules-of-accounting/'), 'How-to + examples', 'Adapt as a finance-operations foundation page and link into accounting basics, reconciliation and interview preparation.', '/resources/accounting-basics/', 'Refresh immediately', 'Keep the content educational; do not turn accounting basics into a generic course sales page.'),
        ('CFA certification', pick(relevant, url_fragment='/chartered-financial-analyst-certification-program/'), 'Credential landing page', 'Do not copy the credential model. Use the observation only to understand how a competitor packages a high-intent finance qualification.', 'Exclude from core plan', 'Do not copy', 'Never imply CFA Institute affiliation or delivery.'),
        ('FRM certification', pick(relevant, url_fragment='/frm-certification-course/'), 'Credential landing page', 'Do not copy the certification product. Use risk-management information within the published Finance Operations module instead.', 'Risk-management article/module', 'Do not copy', 'Do not imply FRM preparation or credential delivery.'),
        ('Investment banking course', pick(relevant, url_fragment='/certified-investment-banking-operations-program/'), 'Commercial course page', 'Use one authoritative /courses/ page with curriculum, module map, eligibility, fees/current cohort questions, access, terms and practical outcomes.', '/courses/', 'Refresh immediately', 'Do not create separate pages for classes, training and certification variants.'),
        ('Cost accounting', pick(relevant, url_fragment='/blog/cost-and-cost-accounting-techniques/'), 'Concepts + methods + examples', 'Refresh existing cost-accounting article and connect it to accounting foundations, finance operations and interview preparation.', '/blog/cost-accounting-methods-examples/', 'Refresh in Wave 2', 'Use original worked examples and explain relevance to the actual curriculum.'),
        ('Trade life cycle', pick(relevant, url_fragment='/blog/trade-life-cycle/'), 'Process + stages', 'Strengthen the existing trade-lifecycle guide with execution-to-settlement stages, ownership, exceptions and reconciliation.', '/career-guides/trade-lifecycle/', 'Refresh in Wave 1', 'Use fictional records; distinguish operations from front-office investment banking.'),
        ('Accounting principles', pick(relevant, url_fragment='/blog/accounting-principles/'), 'Beginner guide', 'Use the existing accounting resource and blog cluster to attract finance learners, then route to reconciliation and finance operations.', '/resources/accounting-basics/', 'Refresh in Wave 2', 'Avoid duplicate definitions across multiple accounting pages.'),
        ('What is investment banking?', pick(relevant, url_fragment='/blog/what-is-investment-banking/'), 'Definition + roles + career scope', 'Own the broad definition in the investment-banking operations guide/blog, then clearly explain the operations pathway.', '/career-guides/investment-banking-operations/', 'Refresh in Wave 1', 'Do not imply all investment-banking roles are part of the Masterclass.'),
        ('What is accounting?', pick(relevant, url_fragment='/blog/what-is-accounting/'), 'Definition + principles + career scope', 'Cover accounting foundations only where they support finance-operations learners; link to the existing accounting resource.', '/resources/accounting-basics/', 'Consolidate into existing cluster', 'Do not create a thin page for every accounting definition.'),
        ('Corporate finance', pick(relevant, url_fragment='/blog/what-is-corporate-finance/'), 'Definition + functions', 'Use a sourced finance-management explainer only if it helps learners understand the difference between corporate finance, operations and banking workflows.', '/blog/financial-management-decisions-controls/', 'Optional Wave 3', 'Do not present corporate-finance advisory as a course module unless approved.'),
        ('Financial products', pick(relevant, url_fragment='/blog/financial-products-in-depth-guide-for-beginners/'), 'Beginner glossary / product map', 'Create a finance-products explainer tied to retail banking, lending, payments and investment operations; use it as a discovery page.', '/resources/finance-gk/', 'Optional Wave 3', 'Use current authoritative definitions; no financial advice.'),
        ('Financial systems', pick(relevant, url_fragment='/blog/overview-of-financial-systems/'), 'System overview', 'Refresh the finance/BFSI concepts hub and link to the six actual Masterclass modules.', '/resources/finance-gk/', 'Refresh in Wave 2', 'Keep scope educational and India-relevant without inventing employer facts.'),
        ('Investment banker career path', pick(relevant, url_fragment='/blog/how-to-become-an-investment-banker-in-india-career-path-skills-certification-guide/'), 'Career path + skills', 'Adapt to an honest operations-focused career path: role families, workflow skills, employer descriptions and interview preparation.', '/career-guides/investment-banking-operations/', 'Refresh in Wave 1', 'Do not promise an investment-banker title or salary.'),
        ('Financial statement analysis', pick(relevant, url_fragment='/blog/what-is-financial-statement-analysis-and-how-is-it-different-from-financial-analysis/'), 'Definition + comparison + example', 'Add an original article connected to accounting, credit analysis and finance operations. Use this to qualify learners for the Finance Operations module.', '/blog/financial-statement-analysis-for-banking-operations/', 'Create in Wave 3', 'Do not call it a dedicated Financial Analyst course unless the offer exists.'),
        ('Fund accounting and NAV', pick(relevant, url_fragment='/blog/fund-accounting-and-nav-calculation/'), 'Step-by-step workflow', 'Refresh the existing fund-accounting article with NAV checks, reconciliations and role skills; link to IB Operations.', '/blog/fund-accounting-nav-workflow-career-skills/', 'Refresh in Wave 2', 'Use fictional examples and state assumptions.'),
        ('Investment banking salary', pick(relevant, url_fragment='/blog/investment-banking-salary-in-india/'), 'Salary + role research', 'Keep as a late-stage, dated article. Explain role, city, employer, experience and source differences instead of using a promotional number.', '/blog/investment-banking-salary-in-india/', 'Defer until sources are approved', 'Never use a salary figure as a course or job guarantee.'),
        ('Risk management', pick(relevant, url_fragment='/blog/risk-management-meaning-features-and-importance/'), 'Definition + risk types', 'Build a banking-risk article and link to Finance Operations, credit and interview preparation.', '/blog/risk-management-in-banking/', 'Create in Wave 3', 'Regulatory and risk terminology must be source-dated.'),
        ('Retail banking', pick(relevant, url_fragment='/blog/what-is-retail-banking/'), 'Definition + services + roles', 'Strengthen the existing Retail Banking guide/module with meaning, services, branch operations, lending and role skills.', '/career-guides/retail-banking-operations/', 'Refresh in Wave 2', 'Do not imply bank employment or a separate retail-banking class.'),
        ('Financial markets', pick(relevant, url_fragment='/blog/what-are-financial-markets-and-how-does-it-function/'), 'Market overview', 'Use the existing financial-markets article to lead into trade lifecycle and investment operations without offering investment advice.', '/blog/financial-markets-instruments-participants-operations/', 'Refresh in Wave 2', 'No recommendations, trading calls or financial advice.'),
        ('Investment banks in India', pick(relevant, url_fragment='/blog/investment-banking-companies-in-india/'), 'Employer / industry research', 'Create a cautious employer-research article that explains functions and operations roles, with dated official sources.', '/blog/investment-banks-in-india/', 'Create in Wave 3', 'Do not list companies as hiring partners without current approval.'),
        ('Financial services', pick(relevant, url_fragment='/blog/types-of-financial-services/'), 'Beginner taxonomy', 'Map banking, lending, payments, insurance, investments and FinTech to the actual six modules and career directions.', '/resources/finance-gk/', 'Refresh in Wave 2', 'Keep the scope broad but route each topic to a real page.'),
        ('Process associate', pick(relevant, url_fragment='/blog/process-associate/'), 'Role / duties / skills', 'Add a finance-process-associate section to the Finance Operations guide or create one supporting article if the section becomes substantial.', '/career-guides/finance-operations/', 'Add as section in Wave 1', 'Do not target generic BPO process-associate traffic without finance context.'),
    ]

    observations = []
    for index, (pattern, row, fmt, adapt, owner, action, guardrail) in enumerate(observation_defs, start=1):
        observations.append([index, pattern, row['Title'] if row else '', row['Url'] if row else '', metric(row), fmt, adapt, owner, action, guardrail])

    blueprint = [
        [1, 'Wave 1', 99, 'Refresh existing', '/courses/', 'Single commercial authority page', 'investment banking course / banking and finance course / job-oriented finance course', 'Program promise; six modules; curriculum depth; who it suits; delivery; current cohort; fees question; eligibility; projects; interview preparation; terms; FAQs; conversion CTA.', 'One Financial Operations Masterclass containing modules; not six separate courses.', 'Primary CTA: request current cohort/fees/terms. Secondary CTA: relevant module guide.', 'Competitor commercial page: 350 est. clicks; top keyword “investment banking courses”; position 2.', 'Course + Organization + BreadcrumbList + visible FAQs where maintained.', '/placements/; all six module pages; /career-guides/; /resources/investment-banking-interview-questions/; /contact/', 'Do not create or imply standalone classes, external certifications or city classrooms.', 'Highest impact; do first'],
        [2, 'Wave 1', 98, 'Refresh existing', '/career-guides/investment-banking-operations/', 'Definition-to-career pillar', 'what is investment banking / investment banking operations / investment banking career', 'Definition; front/middle/back office; operations teams; trade lifecycle; settlements; reconciliation; corporate actions; fund accounting; skills; entry roles; interview questions; course bridge.', 'Investment Banking Operations is a published module and career direction within the Masterclass.', 'CTA after answer: explore the Masterclass and interview resource.', 'Competitor definition page: 155 est. clicks; investment banking volume 18,700.', 'Article + BreadcrumbList + FAQPage only for visible maintained FAQs.', '/courses/; /career-guides/trade-lifecycle/; /resources/reconciliation-in-finance/; /resources/investment-banking-interview-questions/', 'Do not promise the reader becomes an investment banker or receives a specific title.', 'Highest impact; do first'],
        [3, 'Wave 1', 97, 'Refresh existing', '/resources/reconciliation-in-finance/', 'Workflow authority resource', 'reconciliation meaning / reconciliation process / reconciliation steps', 'Short answer; types; source-to-ledger matching; breaks; exception queue; evidence; escalation; banking and investment-operations examples; interview prompts; worksheet CTA.', 'Reconciliation is explicitly in Investment Banking Operations and Digital Payments modules.', 'CTA: practice worksheet, then relevant module/course.', 'Competitor page: 1,245 est. clicks; 21,500 top-keyword volume; position 6.', 'LearningResource + Article + BreadcrumbList.', '/career-guides/finance-operations/; /career-guides/investment-banking-operations/; /courses/digital-payments/; /resources/investment-banking-interview-questions/', 'Do not create another reconciliation blog or use confidential records.', 'Traffic and relevance leader'],
        [4, 'Wave 1', 96, 'Refresh existing', '/career-guides/trade-lifecycle/', 'Process-and-stages guide', 'trade life cycle / trade lifecycle in investment banking / settlement process', 'Trade capture; confirmation; matching; settlement; failed settlement; reconciliation; controls; role ownership; interview questions; fictional example.', 'Trade settlements and reconciliation are published Investment Banking Ops topics.', 'CTA: IB Operations module and interview resource.', 'Competitor trade-life-cycle page: 299 est. clicks; top keyword volume 3,800; position 3.', 'Article + LearningResource + BreadcrumbList.', '/courses/; /career-guides/investment-banking-operations/; /resources/reconciliation-in-finance/; /blog/corporate-actions-analyst-career-path/', 'Do not present front-office trading instruction or investment advice.', 'High-priority refresh'],
        [5, 'Wave 1', 95, 'Refresh existing', '/resources/accounting-basics/', 'Accounting foundations hub', 'golden rules of accounting / accounting principles / what is accounting', 'Definitions; journal/ledger examples; golden rules; controls; common mistakes; connection to reconciliation, financial statements and finance operations interviews.', 'Accounting supports Finance Operations, Credit Analysis and Reconciliation topics.', 'CTA: accounting interview resource and Finance Operations guide.', 'Competitor golden-rules page: 849 est. clicks; 12,300 volume; 155 top-keyword clicks.', 'LearningResource + BreadcrumbList.', '/resources/reconciliation-in-finance/; /career-guides/finance-operations/; /resources/accounting-interview-questions/', 'Do not create multiple thin pages for each accounting rule.', 'High-priority refresh'],
        [6, 'Wave 2', 92, 'Refresh existing', '/blog/financial-accounting-statements-process-examples/', 'Financial statements explainer', 'financial accounting / balance sheet / financial statements', 'Accounting cycle; balance sheet; income statement; cash flow; fictional transaction; reporting hand-offs; relevance to finance operations and credit.', 'Finance Operations includes reporting, credit and risk context; this is informational support.', 'CTA: Finance Operations guide and accounting interview resource.', 'Competitor balance-sheet page: 658 est. clicks; 33,800 volume; 360 top-keyword clicks.', 'Article + BreadcrumbList + LearningResource.', '/resources/accounting-basics/; /career-guides/finance-operations/; /resources/reconciliation-in-finance/', 'Do not claim accounting qualification or financial advice.', 'High-reach informational feeder'],
        [7, 'Wave 2', 91, 'Refresh existing', '/blog/cost-accounting-methods-examples/', 'Cost accounting example guide', 'cost accounting / cost accounting methods', 'Cost behavior; allocation; worked example; controls; difference from management accounting; where the concept appears in finance work.', 'Informational finance foundation; not a separate Masterclass module.', 'CTA: Finance Operations guide, not a cost-accounting course claim.', 'Competitor page: 277 est. clicks; 10,800 volume; position 8.', 'Article + BreadcrumbList.', '/resources/accounting-basics/; /career-guides/finance-operations/; /blog/financial-accounting-statements-process-examples/', 'Do not create a course landing page for a product you do not offer.', 'High-reach support'],
        [8, 'Wave 2', 90, 'Refresh existing', '/blog/corporate-actions-analyst-career-path/', 'Corporate-actions workflow guide', 'corporate actions / corporate action process / analyst career', 'Dividends; splits; rights; event notices; entitlement checks; reconciliation; exception handling; role skills; fictional case.', 'Corporate Actions is published within Investment Banking Operations.', 'CTA: IB Operations module and trade lifecycle guide.', 'Competitor corporate-actions page: 20 est. clicks; 2,500 volume; position 57; opportunity is relevance rather than current traffic.', 'Article + BreadcrumbList + LearningResource.', '/courses/investment-banking-operations/; /career-guides/trade-lifecycle/; /resources/reconciliation-in-finance/', 'Do not imply live corporate-action processing or employer access.', 'Authority-depth addition'],
        [9, 'Wave 2', 89, 'Refresh existing', '/blog/fund-accounting-nav-workflow-career-skills/', 'Fund-accounting workflow', 'fund accounting / NAV calculation / fund accounting skills', 'NAV inputs; pricing; checks; reconciliations; exceptions; role skills; interview questions; fictional NAV example.', 'Fund Accounting is published within Investment Banking Operations.', 'CTA: IB Operations guide and interview resource.', 'Competitor page: 76 est. clicks; 1,700 volume; position 5.', 'Article + BreadcrumbList + LearningResource.', '/career-guides/investment-banking-operations/; /resources/reconciliation-in-finance/; /resources/investment-banking-interview-questions/', 'Use fictional figures and state assumptions.', 'Strong topical fit'],
        [10, 'Wave 2', 88, 'Refresh existing', '/career-guides/retail-banking-operations/', 'Retail banking information pillar', 'what is retail banking / retail banking meaning / retail banking operations', 'Meaning; products/services; branch operations; relationship manager; loan officer; NRI banking; process controls; role skills; interview prompts.', 'Retail Banking is a published module and career direction.', 'CTA: Retail Banking module and Finance Operations guide.', 'Competitor retail banking pages: 56 and 47 est. clicks; 3,100 volume; position 16.', 'Article + BreadcrumbList + FAQPage if maintained.', '/courses/retail-banking/; /blog/commercial-banks-services-operations/; /career-guides/finance-careers-after-graduation/', 'Do not claim a retail-banking class or bank placement.', 'High-fit information page'],
        [11, 'Wave 2', 87, 'Refresh existing', '/career-guides/finance-operations/', 'Finance role and process hub', 'finance operations career / process associate / finance executive / operations analyst', 'Role definitions; process associate duties; controls; reporting; accounting; loan processing; credit analysis; risk; skills; interview preparation.', 'Finance Operations is a published module and central job direction.', 'CTA: Finance Operations module and course/terms page.', 'Competitor process-associate page: 164 est. clicks; operations-management page: 103 est. clicks.', 'Article + BreadcrumbList + FAQPage if maintained.', '/courses/finance-operations/; /blog/financial-accounting-statements-process-examples/; /blog/risk-management-in-banking/; /resources/investment-banking-interview-questions/', 'Keep finance/BFSI modifiers; do not chase generic operations-management traffic.', 'High-fit role hub'],
        [12, 'Wave 2', 86, 'Refresh existing', '/career-guides/finance-careers-after-graduation/', 'BCom/BBA decision guide', 'BCom jobs in finance / finance careers after graduation / banking jobs after BCom', 'Role map; skill gaps; workflow examples; comparison of IB Ops, retail, KYC/AML, payments, credit, FinTech; course-selection checklist.', 'Leads into the complete Masterclass and module choice, not separate courses.', 'CTA: choose a finance direction, then request current cohort/terms.', 'Competitor BCom page: 703 est. clicks; 14,900 volume; 220 top-keyword clicks.', 'Article + BreadcrumbList + FAQPage if maintained.', '/courses/; /career-guides/choosing-finance-career-course/; all role guides; /india/', 'Do not guarantee a role solely from a degree or course.', 'High-reach lead feeder'],
        [13, 'Wave 2', 85, 'Refresh existing', '/resources/investment-banking-interview-questions/', 'Role-specific interview resource', 'investment banking interview questions / finance interview questions / operations interview questions', 'Questions by workflow; answer structure; reconciliation/settlement/KYC scenarios; self-score rubric; project explanation.', 'Interview preparation is published support; keep resource distinct from course page.', 'CTA: course/module and current support terms.', 'Competitor interview page: 28 est. clicks in top-page export, but 1,000 top-keyword volume and position 7.', 'LearningResource + BreadcrumbList.', '/career-guides/investment-banking-operations/; /career-guides/trade-lifecycle/; /resources/reconciliation-in-finance/; /courses/', 'Use original practice prompts; no fabricated employer questions.', 'Job-intent bridge'],
        [14, 'Wave 3', 84, 'Create', '/blog/financial-statement-analysis-for-banking-operations/', 'Financial statement analysis support article', 'financial statement analysis / financial analysis basics', 'Definition; ratio categories; limitations; credit/lending context; fictional example; what an operations learner should know.', 'Supports Finance Operations / Credit Analysis; not a dedicated analyst course.', 'CTA: Finance Operations module and finance-careers guide.', 'Competitor page: 76 est. clicks; 6,500 volume; 75 top-keyword clicks.', 'Article + BreadcrumbList.', '/career-guides/finance-operations/; /resources/accounting-basics/; /career-guides/finance-careers-after-graduation/', 'No “financial analyst course” claim unless offer is approved.', 'New support article'],
        [15, 'Wave 3', 83, 'Create', '/blog/financial-products-and-services-banking/', 'Financial products and services map', 'financial products / types of financial services', 'Bank accounts; lending; payments; investments; insurance; FinTech; service workflows; where each module fits.', 'Supports Retail Banking, Finance Operations, Digital Payments and FinTech modules.', 'CTA to choose a module and then the Masterclass.', 'Competitor financial-products page: 114 est. clicks; 1,400 volume; position 4.', 'Article + BreadcrumbList + LearningResource.', '/resources/finance-gk/; /courses/retail-banking/; /courses/digital-payments/; /courses/fintech/', 'No product recommendations or financial advice.', 'New support article'],
        [16, 'Wave 3', 82, 'Create', '/blog/financial-market-intermediaries/', 'Financial market intermediaries explained', 'financial intermediaries / market participants', 'Banks; brokers; custodians; exchanges; clearing; fund administrators; how operations hand-offs work.', 'Supports Investment Banking Operations and Trade Lifecycle.', 'CTA: trade lifecycle and IB Operations guide.', 'Competitor page: 57 est. clicks; 2,000 volume; position 10.', 'Article + BreadcrumbList.', '/career-guides/trade-lifecycle/; /career-guides/investment-banking-operations/; /resources/finance-gk/', 'Use authoritative sources; no investment recommendations.', 'New authority article'],
        [17, 'Wave 3', 81, 'Refresh existing', '/blog/financial-markets-instruments-participants-operations/', 'Financial markets and instruments', 'financial markets / financial instruments / market participants', 'Use the existing post as a broad glossary that leads to operations; include a clear definition block and workflow section.', 'Supports Investment Banking Operations and Financial GK resource.', 'CTA: trade lifecycle and IB Operations.', 'Competitor pages: financial market 45 est. clicks; financial instruments 52 est. clicks.', 'Article + BreadcrumbList.', '/career-guides/trade-lifecycle/; /resources/finance-gk/; /career-guides/investment-banking-operations/', 'Educational only; no investment advice.', 'Existing content refresh'],
        [18, 'Wave 3', 80, 'Create', '/blog/finance-process-associate-role/', 'Finance process associate duties and skills', 'finance process associate / process associate in banking', 'Daily duties; queues; data checks; SLAs; exception handling; escalation; Excel; communication; interview prompts.', 'Supports Finance Operations and job-oriented intent.', 'CTA: Finance Operations guide, interview resource and course.', 'Competitor process-associate page: 164 est. clicks; top keyword process associate meaning at position 2.', 'Article + BreadcrumbList + FAQPage if maintained.', '/career-guides/finance-operations/; /resources/investment-banking-interview-questions/; /courses/finance-operations/', 'Do not target generic BPO roles without finance context.', 'New job-information article'],
        [19, 'Wave 3', 79, 'Create', '/blog/risk-management-in-banking/', 'Risk management in banking', 'risk management / credit risk management / operational risk', 'Risk types; controls; credit/operational risk; monitoring; escalation; entry-level roles; fictional case.', 'Supports Finance Operations, Credit Analysis and Risk Management topics.', 'CTA: Finance Operations module and interview resource.', 'Competitor risk page: 60 est. clicks; 19,700 volume; position 63; credit-risk page 20 est. clicks.', 'Article + BreadcrumbList.', '/career-guides/finance-operations/; /courses/finance-operations/; /resources/investment-banking-interview-questions/', 'Date regulatory references; no risk advice.', 'New support article'],
        [20, 'Wave 4', 65, 'Defer / evidence gate', '/blog/investment-banking-salary-in-india/', 'Investment banking salary research', 'investment banker salary in India / finance operations salary', 'Role, location, experience, employer and source methodology; separate operations from front office.', 'Career research only; not a course claim.', 'CTA: career guide, not a salary promise.', 'Competitor page: 64 est. clicks; 1,400 volume; position 12.', 'Article + BreadcrumbList.', '/career-guides/finance-careers-after-graduation/; /career-guides/investment-banking-operations/', 'Must use dated sources and never equate salary with guarantee.', 'Only after source approval'],
    ]

    course_map = [
        ['Investment Banking Operations', 'Published module in Financial Operations Masterclass', 'What is investment banking operations; trade lifecycle; settlements; reconciliation; corporate actions; fund accounting; middle/back office; interview questions', '/courses/investment-banking-operations/ + /career-guides/investment-banking-operations/', 'Explore the Masterclass and ask about current cohort, practice and terms.', 'Do not sell a separate investment-banking class or imply front-office training.'],
        ['Retail Banking', 'Published module in Financial Operations Masterclass', 'Retail banking meaning; services; branch operations; relationship manager; loan officer; NRI banking; customer/process controls', '/courses/retail-banking/ + /career-guides/retail-banking-operations/', 'Explore the module inside the Masterclass.', 'Do not promise bank employment or create a fake local branch.'],
        ['KYC / AML Compliance', 'Published module in Financial Operations Masterclass', 'KYC meaning; AML meaning; CDD/EDD; onboarding; screening; transaction monitoring; SAR; case writing; interview questions', '/courses/kyc-aml/ + /career-guides/kyc-aml-analyst/', 'Explore the module and ask for current cohort details.', 'Do not claim regulatory certification or legal advice.'],
        ['Digital Payments', 'Published module in Financial Operations Masterclass', 'UPI/IMPS/RTGS/SWIFT concepts; payment lifecycle; disputes; fraud operations; wallet reconciliation; exceptions; controls', '/courses/digital-payments/ + /career-guides/digital-payments-operations/', 'Explore the payments module and reconciliation resource.', 'Do not claim a standalone payments qualification or current system fact without sources.'],
        ['Finance Operations / Credit', 'Published module in Financial Operations Masterclass', 'Accounting; financial statements; loan processing; credit analysis; risk management; process associate work; reporting; controls', '/courses/finance-operations/ + /career-guides/finance-operations/', 'Explore the finance-operations module and course terms.', 'Do not label it a dedicated Financial Analyst course unless approved.'],
        ['FinTech & Neo-Banking', 'Published module in Financial Operations Masterclass', 'FinTech meaning; neo-banking; digital lending; product operations; compliance analyst; customer success; payments overlap', '/courses/fintech/ + /career-guides/fintech-operations/', 'Explore the module and compare it with payments/finance operations.', 'Do not call every fintech product a bank or make regulatory claims without current sources.'],
    ]

    format_playbook = [
        ['Definition + career scope', 'What is Investment Banking; What is Accounting; What is Retail Banking', 'Answer in first 40-60 words; definitions; role map; skills; FAQ; next step.', 'Career guide or learning resource', 'Relevant module guide after answer', 'No unverified salary, job or credential claims.'],
        ['Process + steps', 'Reconciliation; Trade Life Cycle; Golden Rules step-by-step', 'Process diagram; inputs; stages; exceptions; controls; fictional example; interview prompts.', 'Learning resource / workflow guide', 'Worksheet or interview resource, then course/module', 'No confidential records or copied competitor examples.'],
        ['Course + placement', 'Certified Investment Banking Course with Placement', 'One commercial page: syllabus, module map, access, eligibility, duration, fees question, support terms, FAQs.', 'Courses hub', 'Current cohort / terms CTA', 'Do not clone separate class pages or make unsupported placement promises.'],
        ['Beginner guide + examples', 'Accounting principles; financial products; financial systems', 'Glossary; table; worked example; source notes; role relevance.', 'Resource/blog cluster', 'Module selection CTA', 'Do not produce thin AI-style definitions.'],
        ['Interview preparation', 'Interview Prep Guide for IB Operations Roles', 'Question groups; answer frameworks; workflow scenarios; scoring rubric; project explanation.', 'Resource', 'Course/module after useful content', 'Use practice questions, not claimed employer questions.'],
        ['Career path + skills', 'Investment Banker Career Path; Process Associate; Finance Executive', 'Role duties; workflow; skills; degree context; employer-description checklist; interview path.', 'Career guide/blog', 'Finance careers guide and Masterclass', 'Avoid guaranteeing a title or employer.'],
        ['Salary / market research', 'Investment Banking Salary in India; CFA Salary', 'Dated source methodology; role/location/experience segmentation; limitations.', 'Optional blog', 'Career guide only', 'Use only after editorial review; never use salary as a promise.'],
        ['Local online-access guide', 'Competitor city/campus pages', 'City job-market signals; exact online access; local areas; roles; FAQs; no fake premises.', 'Existing regional guide', 'India hub / relevant module / contact', 'Do not mass-create doorway pages; keep the existing selective set.'],
    ]

    internal_links = [
        ['Reconciliation resource', '/resources/reconciliation-in-finance/', 'IB Operations guide', '/career-guides/investment-banking-operations/', 'Investment banking operations workflow', 'Informational topic to career pillar', 'High'],
        ['Reconciliation resource', '/resources/reconciliation-in-finance/', 'Finance Operations guide', '/career-guides/finance-operations/', 'Finance operations careers', 'Workflow to role intent', 'High'],
        ['Reconciliation resource', '/resources/reconciliation-in-finance/', 'Interview resource', '/resources/investment-banking-interview-questions/', 'Reconciliation interview questions', 'Workflow to job intent', 'High'],
        ['Trade lifecycle guide', '/career-guides/trade-lifecycle/', 'Courses', '/courses/', 'Investment Banking Operations module', 'Career guide to course', 'High'],
        ['Trade lifecycle guide', '/career-guides/trade-lifecycle/', 'Corporate actions article', '/blog/corporate-actions-analyst-career-path/', 'Corporate actions workflow', 'Topic depth', 'Medium'],
        ['Trade lifecycle guide', '/career-guides/trade-lifecycle/', 'Fund accounting article', '/blog/fund-accounting-nav-workflow-career-skills/', 'Fund accounting and NAV workflow', 'Topic depth', 'Medium'],
        ['Accounting basics', '/resources/accounting-basics/', 'Financial accounting blog', '/blog/financial-accounting-statements-process-examples/', 'Financial accounting and statements', 'Foundation depth', 'High'],
        ['Accounting basics', '/resources/accounting-basics/', 'Finance Operations guide', '/career-guides/finance-operations/', 'Finance operations roles', 'Foundation to career', 'High'],
        ['Financial accounting blog', '/blog/financial-accounting-statements-process-examples/', 'Reconciliation resource', '/resources/reconciliation-in-finance/', 'Reconciliation in finance', 'Statements to controls', 'High'],
        ['Financial accounting blog', '/blog/financial-accounting-statements-process-examples/', 'Financial statement analysis article', '/blog/financial-statement-analysis-for-banking-operations/', 'Financial statement analysis', 'Foundation depth', 'Medium'],
        ['Retail banking guide', '/career-guides/retail-banking-operations/', 'Retail Banking module', '/courses/retail-banking/', 'Retail Banking module', 'Guide to course', 'High'],
        ['Retail banking guide', '/career-guides/retail-banking-operations/', 'Commercial bank blog', '/blog/commercial-banks-services-operations/', 'Commercial bank services and operations', 'Topic depth', 'Medium'],
        ['Finance Operations guide', '/career-guides/finance-operations/', 'Process associate article', '/blog/finance-process-associate-role/', 'Finance process associate duties', 'Role depth', 'High'],
        ['Finance Operations guide', '/career-guides/finance-operations/', 'Risk management article', '/blog/risk-management-in-banking/', 'Risk management in banking', 'Role depth', 'High'],
        ['Finance Operations guide', '/career-guides/finance-operations/', 'Finance Operations module', '/courses/finance-operations/', 'Finance Operations module', 'Guide to course', 'High'],
        ['IB Operations guide', '/career-guides/investment-banking-operations/', 'Courses', '/courses/', 'Investment Banking Operations course', 'Career to commercial', 'High'],
        ['IB Operations guide', '/career-guides/investment-banking-operations/', 'Interview resource', '/resources/investment-banking-interview-questions/', 'Investment banking operations interview questions', 'Career to job intent', 'High'],
        ['Financial products article', '/blog/financial-products-and-services-banking/', 'Retail Banking module', '/courses/retail-banking/', 'Retail Banking topics', 'Product taxonomy to module', 'Medium'],
        ['Financial products article', '/blog/financial-products-and-services-banking/', 'Payments module', '/courses/digital-payments/', 'Digital Payments topics', 'Product taxonomy to module', 'Medium'],
        ['Financial markets article', '/blog/financial-markets-instruments-participants-operations/', 'Trade lifecycle guide', '/career-guides/trade-lifecycle/', 'Trade lifecycle in investment banking', 'Markets to operations', 'High'],
        ['Financial market intermediaries', '/blog/financial-market-intermediaries/', 'IB Operations guide', '/career-guides/investment-banking-operations/', 'Investment banking operations', 'Markets to role', 'Medium'],
        ['BCom career guide', '/career-guides/finance-careers-after-graduation/', 'Choosing-a-course guide', '/career-guides/choosing-finance-career-course/', 'How to choose a finance career course', 'Decision support', 'High'],
        ['BCom career guide', '/career-guides/finance-careers-after-graduation/', 'Courses', '/courses/', 'Financial Operations Masterclass', 'Career to commercial', 'High'],
        ['Every new informational article', 'Blog/resource cluster', 'Contact', '/contact/', 'Ask about the current cohort and terms', 'Qualified conversion after answer', 'Medium'],
    ]

    metadata = [
        ['Wave 1', '/courses/', 'Investment banking operations course', 'Investment Banking Operations Course | Centaur Careers', 'Explore investment banking operations, banking workflows and six finance modules within the Financial Operations Masterclass.', 'Investment Banking Operations Course and Financial Operations Masterclass', 'Course + Organization + BreadcrumbList', 'One canonical commercial owner; include current access and terms.'],
        ['Wave 1', '/career-guides/investment-banking-operations/', 'what is investment banking operations', 'What Is Investment Banking Operations? | Centaur Careers', 'Understand trade support, settlements, reconciliation, corporate actions, fund accounting and entry-level operations skills.', 'What Is Investment Banking Operations?', 'Article + BreadcrumbList', 'Answer definition intent before the course CTA.'],
        ['Wave 1', '/resources/reconciliation-in-finance/', 'reconciliation meaning', 'Reconciliation Meaning in Finance: Process and Example', 'Learn reconciliation types, matching, breaks, exception handling and finance-operations controls with a practical example.', 'What Is Reconciliation in Finance?', 'LearningResource + BreadcrumbList', 'Protect one canonical reconciliation URL.'],
        ['Wave 1', '/career-guides/trade-lifecycle/', 'trade lifecycle in investment banking', 'Trade Lifecycle in Investment Banking: Steps and Roles', 'Follow trade capture, confirmation, settlement, reconciliation and exception handling with operations-focused examples.', 'Trade Lifecycle in Investment Banking', 'Article + LearningResource', 'Avoid front-office or investment-advice framing.'],
        ['Wave 2', '/resources/accounting-basics/', 'golden rules of accounting', 'Golden Rules of Accounting: Examples for Finance Beginners', 'Learn accounting rules and connect them to reconciliation, reporting and finance-operations interview preparation.', 'Golden Rules of Accounting', 'LearningResource + BreadcrumbList', 'Keep one accounting foundation hub.'],
        ['Wave 2', '/blog/financial-accounting-statements-process-examples/', 'financial accounting', 'Financial Accounting: Statements, Process and Example', 'Understand the accounting cycle, financial statements and their relevance to banking and finance operations.', 'Financial Accounting: Process and Statements', 'Article + BreadcrumbList', 'Use fictional examples and date updates.'],
        ['Wave 2', '/blog/cost-accounting-methods-examples/', 'cost accounting', 'Cost Accounting Methods and a Worked Example', 'Learn cost accounting methods, allocation and finance-workflow relevance with a clear worked example.', 'Cost Accounting Methods and Examples', 'Article + BreadcrumbList', 'No standalone course claim.'],
        ['Wave 2', '/career-guides/retail-banking-operations/', 'retail banking operations', 'Retail Banking Operations: Meaning, Roles and Career Path', 'Understand retail banking services, branch operations, lending support and entry-level role skills.', 'Retail Banking Operations: Meaning and Careers', 'Article + BreadcrumbList', 'No bank-placement promise.'],
        ['Wave 2', '/career-guides/finance-operations/', 'finance operations career', 'Finance Operations Careers: Roles, Skills and Entry Routes', 'Explore process associate, reporting, accounting, lending, credit and risk-support work in finance operations.', 'Finance Operations Careers for Graduates', 'Article + BreadcrumbList', 'Keep finance/BFSI intent explicit.'],
        ['Wave 3', '/blog/financial-statement-analysis-for-banking-operations/', 'financial statement analysis', 'Financial Statement Analysis for Banking Operations', 'Learn statement-analysis basics, ratios, limitations and credit/operations context using an educational example.', 'Financial Statement Analysis for Banking Operations', 'Article + BreadcrumbList', 'Do not call this a Financial Analyst course.'],
        ['Wave 3', '/blog/financial-products-and-services-banking/', 'financial products', 'Financial Products and Banking Services Explained', 'Map banking, lending, payments, investment, insurance and FinTech products to finance workflows and career directions.', 'Financial Products and Banking Services', 'Article + BreadcrumbList', 'No financial advice.'],
        ['Wave 3', '/blog/financial-market-intermediaries/', 'financial intermediaries', 'Financial Market Intermediaries and Their Roles', 'Understand banks, brokers, custodians, exchanges, clearing and operations hand-offs in financial markets.', 'Financial Market Intermediaries', 'Article + BreadcrumbList', 'Use current authoritative sources.'],
        ['Wave 3', '/blog/finance-process-associate-role/', 'finance process associate', 'Finance Process Associate: Duties, Skills and Interview Preparation', 'Learn process-associate workflows, data checks, queues, exceptions, escalation and interview preparation in finance.', 'Finance Process Associate: Duties and Skills', 'Article + BreadcrumbList', 'Avoid generic BPO targeting.'],
        ['Wave 3', '/blog/risk-management-in-banking/', 'risk management in banking', 'Risk Management in Banking: Types, Controls and Roles', 'Understand credit, operational and process risk with examples for finance-operations learners.', 'Risk Management in Banking', 'Article + BreadcrumbList', 'Date regulation-sensitive content.'],
    ]

    sequence = [
        [1, 'Protect ownership', 'Do not add separate class URLs', 'Keep the single /courses/ page as the commercial owner; information pages explain the work and link to it.', 'No duplicate course/class/training pages.'],
        [2, 'Wave 1', 'Refresh /courses/', 'Use the competitor course-page structure: scope, eligibility, modules, access, current cohort, terms, FAQs and proof.', 'Commercial page answers course and lead intent without unsupported claims.'],
        [3, 'Wave 1', 'Refresh reconciliation', 'This is the clearest competitor traffic win; expand process, examples, controls, worksheet and role bridge.', 'One canonical resource with links to three relevant conversion destinations.'],
        [4, 'Wave 1', 'Refresh IB operations and trade lifecycle', 'Merge broad definition demand with operations-specific career and process information.', 'Pages distinguish front office, operations, settlement and controls.'],
        [5, 'Wave 2', 'Refresh accounting and retail/finance operations clusters', 'Use competitor accounting and retail pages to attract learners, then route them into real modules.', 'No thin definition pages; each page has a unique intent and role bridge.'],
        [6, 'Wave 2', 'Refresh corporate actions and fund accounting', 'Expand practical module topics with fictional cases, controls and interview prompts.', 'Original examples, source log and module links.'],
        [7, 'Wave 2', 'Strengthen interview and BCom career pages', 'Make job preparation and graduate decision support the main lead bridges.', 'Practice questions and course terms are visible.'],
        [8, 'Wave 3', 'Create authority support articles', 'Financial statements, products/services, intermediaries, process associate and risk pages.', 'Each new page has evidence, owner, CTA and internal links before publishing.'],
        [9, 'Wave 4', 'Defer salary/credential expansion', 'Salary pages require dated sources; CFA/FRM/CA/CPA/ACCA pages are not part of the offer.', 'No brand/credential misrepresentation or stale salary claims.'],
        [10, 'Measurement', 'Validate with GA4 and Search Console', 'Measure landing page, query, region, CTA and lead quality; prioritize actual opportunity rather than competitor traffic alone.', '28-day and 56-day review recorded.'],
    ]

    do_not_copy = [
        ['CFA / FRM / CA / CPA / ACCA certification pages', 'High competitor clicks and volume', 'Not your published product; credential/brand and trust risk.', 'Exclude from core architecture; if comparison is useful, link to official credential owners and state differences.'],
        ['Partner-branded certification claims', 'Competitor uses KPMG/partner wording', 'Cannot be copied without documented current relationship and exact award terms.', 'Use only approved current partnership evidence.'],
        ['Separate “classes” for every module', 'Competitor has course pages and variants', 'Your current offer is one Financial Operations Masterclass with modules.', 'One /courses/ authority page plus module information pages.'],
        ['City pages that imply local classrooms', 'Competitor has city/campus-style pages', 'Your published physical location is Lucknow; other locations are online access guides.', 'Keep the existing selective regional set and exact wording.'],
        ['Generic “operations management” pages', 'Competitor ranks for broad operations terms', 'Broad traffic may not be finance-job qualified.', 'Use Finance Operations with BFSI/process modifiers.'],
        ['Salary pages as lead promises', 'Competitor uses salary/career titles', 'Salary changes by role, location, employer and time.', 'Publish only with dated sources and no guarantee implication.'],
        ['Investment advice / product recommendations', 'Competitor has derivatives, financial products and market pages', 'Not the purpose of your training site; regulatory and trust risk.', 'Educational definitions only; source current facts.'],
        ['Copied competitor titles or article structures', 'Top pages reveal formats', 'Duplicate wording weakens originality and trust.', 'Adapt intent and depth; write original examples and source logs.'],
    ]

    source_notes = [
        ['TopPages_imarticus-org_9_27_2026_SEO (1).csv', 'Competitor top-page performance export', len(all_rows), '', len(relevant), '', 'Title, URL, keyword count, estimated monthly SEO clicks, top keyword, position, volume and clicks.', 'Estimated competitor clicks are directional; they are not your forecast and should not be added to previous exports.'],
        ['Strongest transferable page', 'Reconciliation', '', '', '', '', metric(pick(relevant, url_fragment='/blog/reconciliation-meaning/')), 'Highest directly relevant estimated clicks in the supplied export.'],
        ['Strongest commercial page', 'Investment banking course', '', '', '', '', metric(pick(relevant, url_fragment='/certified-investment-banking-operations-program/')), 'Use the page structure, not unsupported product claims.'],
        ['Strongest foundation page', 'Golden rules of accounting', '', '', '', '', metric(pick(relevant, url_fragment='/blog/golden-rules-of-accounting/')), 'Use as finance-operations discovery content.'],
        ['Current Centaur positioning', 'Live site and source code', '', '', '', '', 'One six-week Financial Operations Masterclass; modules include IB Ops, Retail Banking, KYC/AML, Payments, Finance Operations and FinTech; online across India and in-person in Lucknow.', 'Confirm live terms, cohort, employer references and guarantee wording before each release.'],
    ]

    summary = [
        ['What the competitor is doing well', 'Building complete answer pages around definitions, processes, examples, career scope, interviews and one commercial program page.'],
        ['What we should copy', 'The information architecture and depth: answer the question fully, show workflow examples, then route qualified readers to the matching module and Masterclass.'],
        ['What we should not copy', 'CFA/FRM/CA/CPA/ACCA products, partner-branded credentials, fake city classrooms, or separate classes that are not part of your offer.'],
        ['First three changes', 'Refresh /courses/, refresh reconciliation, and refresh the Investment Banking Operations + Trade Lifecycle information cluster.'],
        ['Lead strategy', 'Every information page should answer first, prove topical relevance second, then use a contextual CTA: module, interview resource, current cohort/terms or contact.'],
        ['Quality rule', 'One page per intent, original examples, source dates for changing facts, and no unsupported job/salary/partner promises.'],
    ]
    return summary, observations, blueprint, course_map, format_playbook, internal_links, metadata, sequence, do_not_copy, source_notes


def main():
    summary, observations, blueprint, course_map, format_playbook, internal_links, metadata, sequence, do_not_copy, source_notes = build()
    sheets = [
        ('Addon Summary', 'Competitor top-page add-on plan. This workbook supplements the existing SEO Keyword Implementation Plan and does not replace its ownership map.', ['Area', 'Decision'], summary),
        ('Top Page Observations', 'Selected competitor pages ranked by estimated monthly SEO clicks, mapped to what Centaur should adapt, consolidate or exclude.', ['Rank', 'Pattern', 'Competitor title', 'Competitor URL', 'Performance evidence', 'Page format', 'What to adapt', 'Centaur owner', 'Action', 'Guardrail'], observations),
        ('Addon Page Blueprint', 'Pages and page expansions designed around your actual course modules and information expertise. “Module” means a topic taught within the one Masterclass, not a separate class product.', ['Seq', 'Wave', 'Priority', 'Action', 'Recommended URL', 'Page role', 'Primary intent', 'Information to cover', 'Course/module relationship', 'Lead path', 'Competitor evidence', 'Metadata direction', 'Schema', 'Internal links', 'Do not claim', 'Status'], blueprint),
        ('Course Info Map', 'Information topics to publish at depth for each real subject area, with a safe lead path.', ['Course/module area', 'Offer status', 'Information topics', 'Canonical owner pages', 'Lead path', 'Do not claim'], course_map),
        ('SERP Format Playbook', 'Reusable content formats observed in the top-page export and the safe way to adapt them.', ['Competitor pattern', 'Observed example', 'On-page structure to adapt', 'Recommended page type', 'Lead bridge', 'No-go rule'], format_playbook),
        ('Addon Internal Links', 'Additional internal-link edges to implement alongside the previous workbook.', ['Source page', 'Source URL', 'Destination page', 'Destination URL', 'Anchor text', 'Purpose', 'Priority'], internal_links),
        ('Addon Metadata', 'Proposed titles, descriptions, H1s and schema directions for the add-on pages.', ['Wave', 'URL', 'Primary keyword', 'Proposed title', 'Proposed meta description', 'Proposed H1', 'Schema', 'Implementation note'], metadata),
        ('Addon Sequence', 'Execution sequence for the competitor-informed improvements.', ['Seq', 'Wave', 'Task', 'Implementation direction', 'Acceptance criteria'], sequence),
        ('Do Not Copy', 'Competitor patterns that are deliberately excluded because they do not match the current offer or create trust/compliance risk.', ['Pattern', 'Why competitor traffic is not enough', 'Risk for Centaur', 'Safe decision'], do_not_copy),
        ('Source Notes', 'Audit trail for the supplied CSV and current Centaur positioning.', ['Source / scope', 'Type', 'Rows / value', 'Columns', 'Relevant rows', 'Unique / overlap', 'Evidence / contribution', 'Limitation'], source_notes),
    ]
    base.write_workbook(sheets)
    print(f'Created {base.OUTPUT}')


if __name__ == '__main__':
    main()
