SET LOCAL search_path TO lms, public;

-- Schema generated by Better Auth 1.7.6 from src/lib/auth-schema.ts.
create table "user" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "role" text, "privacyAccepted" boolean not null, "termsAccepted" boolean not null, "privacyNoticeVersion" text not null, "termsVersion" text not null, "privacyAcceptedAt" timestamptz, "termsAcceptedAt" timestamptz);

create table "session" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" uuid not null references "user" ("id") on delete cascade);

create table "account" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "accountId" text not null, "providerId" text not null, "userId" uuid not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "auth_rate_limit" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

ALTER TABLE lms.courses ADD COLUMN is_sandbox BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE lms.course_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID NOT NULL REFERENCES lms.courses(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL CHECK (version_number > 0),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'retired')),
  overview TEXT NOT NULL DEFAULT '',
  estimated_minutes INTEGER CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (course_id, version_number),
  UNIQUE (course_id, id)
);

ALTER TABLE lms.courses ADD COLUMN current_version_id UUID;
ALTER TABLE lms.courses ADD CONSTRAINT courses_current_version_fk
  FOREIGN KEY (id, current_version_id) REFERENCES lms.course_versions(course_id, id);

CREATE TABLE lms.modules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_version_id UUID NOT NULL REFERENCES lms.course_versions(id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  summary TEXT NOT NULL DEFAULT '',
  position INTEGER NOT NULL CHECK (position > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (course_version_id, slug),
  UNIQUE (course_version_id, position)
);

CREATE TABLE lms.lessons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  module_id UUID NOT NULL REFERENCES lms.modules(id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  format TEXT NOT NULL DEFAULT 'text' CHECK (format IN ('text', 'worksheet', 'video')),
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  position INTEGER NOT NULL CHECK (position > 0),
  published BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (module_id, slug),
  UNIQUE (module_id, position)
);

CREATE TABLE lms.profiles (
  user_id UUID PRIMARY KEY REFERENCES lms."user"(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL CHECK (length(trim(display_name)) BETWEEN 1 AND 100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE lms.user_roles (
  user_id UUID NOT NULL REFERENCES lms."user"(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('learner', 'admin', 'course_editor', 'support')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role)
);

CREATE TABLE lms.enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES lms."user"(id) ON DELETE CASCADE,
  course_id UUID NOT NULL,
  course_version_id UUID NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  UNIQUE (user_id, course_id),
  FOREIGN KEY (course_id, course_version_id) REFERENCES lms.course_versions(course_id, id)
);

CREATE INDEX enrollments_user_status_idx ON lms.enrollments (user_id, status, enrolled_at DESC);
CREATE INDEX enrollments_course_idx ON lms.enrollments (course_id, enrolled_at DESC);

CREATE TABLE lms.lesson_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES lms."user"(id) ON DELETE CASCADE,
  lesson_id UUID NOT NULL REFERENCES lms.lessons(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, lesson_id)
);

CREATE TABLE lms.assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_version_id UUID NOT NULL REFERENCES lms.course_versions(id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  version_number INTEGER NOT NULL DEFAULT 1 CHECK (version_number > 0),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'retired')),
  pass_percent NUMERIC(5,2) CHECK (pass_percent IS NULL OR pass_percent BETWEEN 0 AND 100),
  rules JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (course_version_id, slug, version_number)
);

CREATE TABLE lms.assessment_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assessment_id UUID NOT NULL REFERENCES lms.assessments(id) ON DELETE CASCADE,
  position INTEGER NOT NULL CHECK (position > 0),
  question_type TEXT NOT NULL CHECK (question_type IN ('single_choice', 'multiple_choice', 'short_answer')),
  prompt JSONB NOT NULL,
  choices JSONB NOT NULL DEFAULT '[]'::jsonb,
  answer_key JSONB NOT NULL,
  explanation JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (assessment_id, position)
);

CREATE TABLE lms.assessment_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES lms."user"(id) ON DELETE CASCADE,
  assessment_id UUID NOT NULL REFERENCES lms.assessments(id) ON DELETE CASCADE,
  attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
  status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'submitted', 'abandoned')),
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  score_percent NUMERIC(5,2) CHECK (score_percent IS NULL OR score_percent BETWEEN 0 AND 100),
  passed BOOLEAN,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  submitted_at TIMESTAMPTZ,
  UNIQUE (user_id, assessment_id, attempt_number)
);

CREATE TABLE lms.certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id TEXT NOT NULL UNIQUE,
  user_id UUID NOT NULL REFERENCES lms."user"(id) ON DELETE RESTRICT,
  course_id UUID NOT NULL,
  course_version_id UUID NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  revocation_reason TEXT,
  FOREIGN KEY (course_id, course_version_id) REFERENCES lms.course_versions(course_id, id)
);

CREATE TABLE lms.account_deletion_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES lms."user"(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'cancelled')),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolution_note TEXT
);
CREATE UNIQUE INDEX one_open_account_deletion_request
  ON lms.account_deletion_requests (user_id) WHERE status IN ('pending', 'processing');

CREATE TABLE lms.audit_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_user_id UUID REFERENCES lms."user"(id) ON DELETE SET NULL,
  action TEXT NOT NULL CHECK (length(trim(action)) BETWEEN 1 AND 120),
  target_type TEXT NOT NULL CHECK (length(trim(target_type)) BETWEEN 1 AND 80),
  target_id TEXT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_events_actor_time_idx ON lms.audit_events (actor_user_id, created_at DESC);
CREATE INDEX audit_events_target_idx ON lms.audit_events (target_type, target_id, created_at DESC);

-- Defense in depth for learner-owned reads/writes. Application code sets this
-- transaction-local value only from the server-validated Better Auth session.
CREATE FUNCTION lms.current_learner_id() RETURNS UUID
LANGUAGE SQL STABLE
AS $$ SELECT NULLIF(current_setting('lms.current_learner_id', true), '')::uuid $$;

ALTER TABLE lms.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms.lesson_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms.assessment_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms.account_deletion_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE lms.audit_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY profiles_own_rows ON lms.profiles USING (user_id = lms.current_learner_id()) WITH CHECK (user_id = lms.current_learner_id());
CREATE POLICY roles_read_own ON lms.user_roles FOR SELECT USING (user_id = lms.current_learner_id());
CREATE POLICY roles_create_learner ON lms.user_roles FOR INSERT WITH CHECK (user_id = lms.current_learner_id() AND role = 'learner');
CREATE POLICY enrollments_own_rows ON lms.enrollments USING (user_id = lms.current_learner_id()) WITH CHECK (user_id = lms.current_learner_id());
CREATE POLICY lesson_progress_own_rows ON lms.lesson_progress USING (user_id = lms.current_learner_id()) WITH CHECK (user_id = lms.current_learner_id());
CREATE POLICY assessment_attempts_own_rows ON lms.assessment_attempts USING (user_id = lms.current_learner_id()) WITH CHECK (user_id = lms.current_learner_id());
CREATE POLICY certificates_read_own ON lms.certificates FOR SELECT USING (user_id = lms.current_learner_id());
CREATE POLICY deletion_requests_own_rows ON lms.account_deletion_requests USING (user_id = lms.current_learner_id()) WITH CHECK (user_id = lms.current_learner_id());
CREATE POLICY audit_events_own_rows ON lms.audit_events USING (actor_user_id = lms.current_learner_id()) WITH CHECK (actor_user_id = lms.current_learner_id());

-- The app role is created by db-migrate.mjs before migrations. It cannot own
-- schemas or course content and only receives the SQL permissions needed by
-- the LMS runtime. RLS policies scope learner-owned data to the active session.
REVOKE CREATE ON SCHEMA lms FROM PUBLIC;
GRANT USAGE ON SCHEMA lms TO lms_app;
GRANT USAGE ON SCHEMA lms_system TO lms_app;
GRANT SELECT ON lms_system.schema_migrations TO lms_app;
GRANT SELECT ON lms.courses, lms.course_versions, lms.modules, lms.lessons, lms.assessments, lms.assessment_questions TO lms_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON lms."user", lms."session", lms.account, lms.verification, lms.auth_rate_limit TO lms_app;
GRANT SELECT, INSERT, UPDATE ON lms.profiles TO lms_app;
GRANT SELECT, INSERT ON lms.user_roles TO lms_app;
GRANT SELECT, INSERT, UPDATE ON lms.enrollments, lms.lesson_progress, lms.assessment_attempts TO lms_app;
GRANT SELECT ON lms.certificates TO lms_app;
GRANT SELECT, INSERT ON lms.account_deletion_requests TO lms_app;
GRANT SELECT, INSERT ON lms.audit_events TO lms_app;
GRANT EXECUTE ON FUNCTION lms.current_learner_id() TO lms_app;

COMMENT ON TABLE lms."user" IS 'LMS-owned learner identities managed by the in-process Better Auth library.';
COMMENT ON TABLE lms.assessment_questions IS 'Answer keys remain server-side; never select this table into public page props.';
COMMENT ON COLUMN lms.courses.is_sandbox IS 'Only local development may enroll in sandbox records; never publish these.';
