// Ordered Phase 8 article queue. Semrush volumes are imported estimates; the
// source export did not identify its database, device, or locale.
export const BLOG_QUEUE_SERP_REVIEW = Object.freeze({
  status: 'provisional',
  market: 'India',
  language: 'English',
  note: 'The supplied export settings are unknown and direct Google India results were not independently captured. Treat volume/KD as candidates; manually review a logged Google India SERP before the next editorial refresh or any outreach.',
});

export const BLOG_KEYWORD_QUEUE = Object.freeze([
  Object.freeze({
    position: 1,
    postId: 'career-options-in-commerce-decision-map',
    targetPath: '/blog/career-options-in-commerce-decision-map/',
    primaryKeyword: 'career options in commerce',
    supportingKeywords: Object.freeze(['commerce career options', 'commerce careers', 'finance career paths']),
    reportedVolume: 14800,
    keywordDifficulty: 24,
    searchIntent: 'Commercial / informational',
    distinctIntentReview: 'Compared with the existing finance-careers-after-graduation guide: this post is a commerce-graduate decision map focused on comparing work styles and research steps, not a second general career-path directory.',
    reviewedExistingPaths: Object.freeze(['/career-guides/finance-careers-after-graduation/']),
    authorityAssetId: 'commerce-career-decision-map',
  }),
  Object.freeze({
    position: 2,
    postId: 'finance-interview-questions-freshers',
    targetPath: '/blog/finance-interview-questions-freshers/',
    primaryKeyword: 'interview questions with answers for freshers',
    supportingKeywords: Object.freeze(['finance interview questions', 'bank interview questions for freshers', 'operations interview preparation']),
    reportedVolume: 12100,
    keywordDifficulty: 29,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with the existing investment-banking-operations interview resource: this post is a cross-role fresher answer framework and self-scoring rubric, while the existing page is specific to investment-banking operations questions.',
    reviewedExistingPaths: Object.freeze(['/resources/investment-banking-interview-questions/']),
    authorityAssetId: 'fresher-interview-answer-rubric',
  }),
  Object.freeze({
    position: 3,
    postId: 'financial-accounting-statements-process-examples',
    targetPath: '/blog/financial-accounting-statements-process-examples/',
    primaryKeyword: 'financial accounting',
    supportingKeywords: Object.freeze(['financial accounting process', 'financial statements', 'accounting cycle']),
    reportedVolume: 14800,
    keywordDifficulty: 28,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with the accounting-basics resource: this post follows the accounting cycle into statements with a fictional transaction; the resource remains the owner of introductory debit-credit fundamentals.',
    reviewedExistingPaths: Object.freeze(['/resources/accounting-basics/']),
    authorityAssetId: 'financial-accounting-cycle-guide',
  }),
  Object.freeze({
    position: 4,
    postId: 'cost-accounting-methods-examples',
    targetPath: '/blog/cost-accounting-methods-examples/',
    primaryKeyword: 'cost accounting',
    supportingKeywords: Object.freeze(['cost accounting methods', 'cost and management accounting', 'cost allocation']),
    reportedVolume: 22200,
    keywordDifficulty: 29,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with the accounting-basics resource: this post focuses on cost behaviour, costing approaches and a worked cost-allocation example rather than general journal and ledger basics.',
    reviewedExistingPaths: Object.freeze(['/resources/accounting-basics/']),
    authorityAssetId: 'cost-accounting-worked-example',
  }),
  Object.freeze({
    position: 5,
    postId: 'investment-banking-teams-operations',
    targetPath: '/blog/investment-banking-teams-operations/',
    primaryKeyword: 'investment banking',
    supportingKeywords: Object.freeze(['what is investment banking', 'investment banking teams', 'investment banking operations']),
    reportedVolume: 33100,
    keywordDifficulty: 57,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with the investment-banking-operations career guide and existing comparison post: this is a broad team/function map and workflow explainer, not a role-entry or qualification guide.',
    reviewedExistingPaths: Object.freeze(['/career-guides/investment-banking-operations/', '/blog/investment-banking-operations-vs-cfa-financial-modelling/']),
    authorityAssetId: 'investment-banking-team-workflow',
  }),
  Object.freeze({
    position: 6,
    postId: 'commercial-banks-services-operations',
    targetPath: '/blog/commercial-banks-services-operations/',
    primaryKeyword: 'commercial bank',
    supportingKeywords: Object.freeze(['commercial bank meaning', 'commercial bank services', 'bank operations workflow']),
    reportedVolume: 18100,
    keywordDifficulty: 50,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with the retail-banking career guide and module page: this post explains commercial-bank categories, services and a sample service workflow, not a career path or course landing page.',
    reviewedExistingPaths: Object.freeze(['/career-guides/retail-banking-operations/', '/courses/retail-banking/']),
    authorityAssetId: 'commercial-bank-service-workflow',
  }),
  Object.freeze({
    position: 7,
    postId: 'trial-balance-format-errors-reconciliation',
    targetPath: '/blog/trial-balance-format-errors-reconciliation/',
    primaryKeyword: 'trial balance',
    supportingKeywords: Object.freeze(['what is trial balance', 'trial balance format', 'trial balance errors']),
    reportedVolume: 33100,
    keywordDifficulty: 49,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with accounting basics and reconciliation resources: this post owns the specific trial-balance format, limitations and error-check intent; the linked pages cover broader fundamentals and operational matching.',
    reviewedExistingPaths: Object.freeze(['/resources/accounting-basics/', '/resources/reconciliation-in-finance/']),
    downloadPath: '/downloads/trial-balance-review-worksheet.csv',
    authorityAssetId: 'trial-balance-check-example',
  }),
  Object.freeze({
    position: 8,
    postId: 'balance-sheet-meaning-format-example',
    targetPath: '/blog/balance-sheet-meaning-format-example/',
    primaryKeyword: 'balance sheet',
    supportingKeywords: Object.freeze(['balance sheet format', 'balance sheet meaning', 'assets liabilities and equity']),
    reportedVolume: 60500,
    keywordDifficulty: 63,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with accounting basics: this post focuses on statement meaning, structure and a complete fictional assets/liabilities/equity example, not the resource page’s wider introductory topic set.',
    reviewedExistingPaths: Object.freeze(['/resources/accounting-basics/']),
    authorityAssetId: 'balance-sheet-worked-example',
  }),
  Object.freeze({
    position: 9,
    postId: 'financial-markets-instruments-participants-operations',
    targetPath: '/blog/financial-markets-instruments-participants-operations/',
    primaryKeyword: 'financial market',
    supportingKeywords: Object.freeze(['financial markets', 'market participants', 'financial instruments']),
    reportedVolume: 12100,
    keywordDifficulty: 50,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with the trade-lifecycle guide: this post maps broad market instruments and participants, while the existing guide focuses on the operational lifecycle and related careers.',
    reviewedExistingPaths: Object.freeze(['/career-guides/trade-lifecycle/']),
    authorityAssetId: 'financial-markets-participant-map',
  }),
  Object.freeze({
    position: 10,
    postId: 'financial-management-decisions-controls',
    targetPath: '/blog/financial-management-decisions-controls/',
    primaryKeyword: 'financial management',
    supportingKeywords: Object.freeze(['financial management functions', 'financial planning', 'working capital management']),
    reportedVolume: 14800,
    keywordDifficulty: 53,
    searchIntent: 'Informational',
    distinctIntentReview: 'Compared with the finance-operations career guide: this post covers foundational organisation-level investment, financing, liquidity and control decisions, not job duties or a course syllabus.',
    reviewedExistingPaths: Object.freeze(['/career-guides/finance-operations/']),
    authorityAssetId: 'financial-management-decision-framework',
  }),
]);
