// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/courses": {
    params: {};
  };
  "/courses/investment-banking-operations": {
    params: {};
  };
  "/courses/retail-banking": {
    params: {};
  };
  "/courses/finance-operations": {
    params: {};
  };
  "/placements": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/locations/lucknow": {
    params: {};
  };
  "/faqs": {
    params: {};
  };
  "/404": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/courses" | "/courses/investment-banking-operations" | "/courses/retail-banking" | "/courses/finance-operations" | "/placements" | "/about" | "/contact" | "/locations/lucknow" | "/faqs" | "/404" | "/*";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/courses.jsx": {
    id: "routes/courses";
    page: "/courses";
  };
  "routes/investment-banking-operations.jsx": {
    id: "routes/investment-banking-operations";
    page: "/courses/investment-banking-operations";
  };
  "routes/retail-banking.jsx": {
    id: "routes/retail-banking";
    page: "/courses/retail-banking";
  };
  "routes/finance-operations.jsx": {
    id: "routes/finance-operations";
    page: "/courses/finance-operations";
  };
  "routes/placements.jsx": {
    id: "routes/placements";
    page: "/placements";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/lucknow-location.jsx": {
    id: "routes/lucknow-location";
    page: "/locations/lucknow";
  };
  "routes/faqs.jsx": {
    id: "routes/faqs";
    page: "/faqs";
  };
  "routes/not-found.jsx": {
    id: "routes/not-found";
    page: "/404";
  };
  "routes/catch-all.jsx": {
    id: "routes/catch-all";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "routes/home": typeof import("./src/routes/home.jsx");
  "routes/courses": typeof import("./src/routes/courses.jsx");
  "routes/investment-banking-operations": typeof import("./src/routes/investment-banking-operations.jsx");
  "routes/retail-banking": typeof import("./src/routes/retail-banking.jsx");
  "routes/finance-operations": typeof import("./src/routes/finance-operations.jsx");
  "routes/placements": typeof import("./src/routes/placements.jsx");
  "routes/about": typeof import("./src/routes/about.jsx");
  "routes/contact": typeof import("./src/routes/contact.jsx");
  "routes/lucknow-location": typeof import("./src/routes/lucknow-location.jsx");
  "routes/faqs": typeof import("./src/routes/faqs.jsx");
  "routes/not-found": typeof import("./src/routes/not-found.jsx");
  "routes/catch-all": typeof import("./src/routes/catch-all.jsx");
};